// <auto-generated />
using System;
using Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Data.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20250721043834_ReInitial")]
    partial class ReInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assignment")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Assignments.Models.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AssignmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Assignments", "assignment");
                });

            modelBuilder.Entity("Assignment.Assignments.Models.Assignment", b =>
                {
                    b.OwnsOne("Assignment.Assignments.ValueObjects.AssignmentDetail", "Detail", b1 =>
                        {
                            b1.Property<long>("AssignmentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("AssignmentMethod")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("AssignmentMethod");

                            b1.Property<string>("ExtApprStaff")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExtApprStaff");

                            b1.Property<string>("ExtApprStaffAssignmentType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExtApprStaffAssignmentType");

                            b1.Property<string>("ExternalCompanyAssignType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ExternalCompanyAssignType");

                            b1.Property<string>("ExternalCompanyID")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("ExternalCompanyID");

                            b1.Property<string>("IntApprStaff")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("IntApprStaff");

                            b1.Property<string>("IntApprStaffAssignmentType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("IntApprStaffAssignmentType");

                            b1.Property<string>("Remark")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Remark");

                            b1.Property<long>("ReqID")
                                .HasColumnType("bigint")
                                .HasColumnName("RequestId");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments", "assignment");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("Detail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
