// <auto-generated />
using System;
using Collateral.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Collateral.Migrations
{
    [DbContext(typeof(CollateralDbContext))]
    [Migration("20260628051758_RenameLandDetailBuildingValue")]
    partial class RenameLandDetailBuildingValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collateral")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collateral.CollateralMasters.Models.BlockReappraisalDue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAppraisedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OldAppraisalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("ProjectSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RemainingUnits")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollateralMasterId")
                        .IsUnique()
                        .HasDatabaseName("UX_BlockReappraisalDue_CollateralMasterId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_BlockReappraisalDue_Status");

                    b.ToTable("BlockReappraisalDue", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralBackfillReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppraisalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RunAt")
                        .HasDatabaseName("IX_CollateralBackfillReports_Status_RunAt");

                    b.ToTable("CollateralBackfillReports", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedWorkstation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedWorkstation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollateralMasterId")
                        .HasDatabaseName("IX_CollateralDocuments_CollateralMasterId")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("CollateralMasterId", "DocumentType")
                        .HasDatabaseName("IX_CollateralDocuments_DocumentType")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CollateralDocuments", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralEngagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppraisalCompanyCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("AppraisalCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppraisalCompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("AppraisalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AppraisalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppraisalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppraisalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("AppraisalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AppraisedCollateralType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("AppraiserUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("BuildingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConstructionInspectionFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal?>("ForcedSaleValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalAppraiserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LandAreaInSqWa")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("LandValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalCompanyId")
                        .HasDatabaseName("IX_CollateralEngagements_AppraisalCompanyId");

                    b.HasIndex("AppraisalId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollateralEngagements_Appraisal");

                    b.HasIndex("CollateralMasterId", "AppraisalDate")
                        .HasDatabaseName("IX_CollateralEngagements_Master_Date");

                    b.ToTable("CollateralEngagements", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralEngagementBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BuildingAge")
                        .HasColumnType("int");

                    b.Property<decimal?>("BuildingArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BuildingTypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("BuildingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EngagementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NumberOfFloors")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngagementId")
                        .HasDatabaseName("IX_CollateralEngagementBuildings_EngagementId");

                    b.HasIndex("EngagementId", "BuildingTypeCode")
                        .HasDatabaseName("IX_CollateralEngagementBuildings_Engagement_TypeCode");

                    b.ToTable("CollateralEngagementBuildings", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedWorkstation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ExcludedFromReappraisal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ExcludedFromReappraisalAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExcludedFromReappraisalBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HostCollateralId")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMaster")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedWorkstation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollateralType");

                    b.HasIndex("HostCollateralId")
                        .HasDatabaseName("IX_CollateralMasters_HostCollateralId")
                        .HasFilter("[HostCollateralId] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsMaster");

                    b.HasIndex("ParentMasterId")
                        .HasDatabaseName("IX_CollateralMasters_ParentMasterId");

                    b.ToTable("CollateralMasters", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMasterAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CollateralMasterId", "ChangedAt")
                        .HasDatabaseName("IX_CollateralMasterAuditLogs_Master_ChangedAt");

                    b.ToTable("CollateralMasterAuditLogs", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralResultLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppraisalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppraisalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollateralId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalId")
                        .IsUnique()
                        .HasDatabaseName("UX_CollateralResultLogs_Appraisal");

                    b.ToTable("CollateralResultLogs", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CondoDetail", b =>
                {
                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppraisalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BuildingAge")
                        .HasColumnType("int");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("BuildingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CondoName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CondoRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ConstructionYear")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FloorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LandOfficeCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RoomNumber");

                    b.Property<string>("SubDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UsableArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("CollateralMasterId");

                    b.HasIndex("CondoRegistrationNumber", "BuildingNumber", "FloorNumber", "RoomNumber", "Province", "District", "SubDistrict")
                        .IsUnique()
                        .HasDatabaseName("UX_CondoDetails_DedupKey_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("CondoDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.LandDetail", b =>
                {
                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AccessRoadWidth")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AppraisalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BuildingValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUnderConstructionAtLastAppraisal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LandOfficeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LandParcelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandShapeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandZoneType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("OverallConstructionProgressPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rawang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("RoadFrontage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SubDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurveyNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrbanPlanningType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CollateralMasterId");

                    b.HasIndex("IsUnderConstructionAtLastAppraisal")
                        .HasDatabaseName("IX_LandDetails_UnderConstruction")
                        .HasFilter("[IsUnderConstructionAtLastAppraisal] = 1");

                    b.HasIndex("LandOfficeCode", "TitleNumber")
                        .HasDatabaseName("IX_LandDetails_LandOffice_TitleNumber");

                    b.HasIndex("Province", "District", "SubDistrict", "TitleType", "TitleNumber", "SurveyNumber", "LandParcelNumber", "Rawang")
                        .IsUnique()
                        .HasDatabaseName("UX_LandDetails_DedupKey_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("LandDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.LeaseholdDetail", b =>
                {
                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LeaseRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("LeaseTermEnd")
                        .HasColumnType("date");

                    b.Property<int?>("LeaseTermMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LeaseTermStart")
                        .HasColumnType("date");

                    b.Property<string>("Lessee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Lessor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UnderlyingMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CollateralMasterId");

                    b.HasIndex("LeaseRegistrationNo")
                        .HasDatabaseName("IX_LeaseholdDetails_LeaseRegistrationNo");

                    b.HasIndex("UnderlyingMasterId")
                        .HasDatabaseName("IX_LeaseholdDetails_UnderlyingMasterId");

                    b.HasIndex("LeaseRegistrationNo", "UnderlyingMasterId", "Lessor", "Lessee", "LeaseTermStart")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaseholdDetails_DedupKey_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("LeaseholdDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.MachineDetail", b =>
                {
                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LifeYear")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("MachineRegistrationNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CollateralMasterId");

                    b.HasIndex("MachineRegistrationNo")
                        .IsUnique()
                        .HasDatabaseName("UX_MachineDetails_RegistrationNo_Active")
                        .HasFilter("[MachineRegistrationNo] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("SerialNo")
                        .HasDatabaseName("IX_MachineDetails_SerialNo");

                    b.HasIndex("SerialNo", "Brand", "Model", "Manufacturer")
                        .IsUnique()
                        .HasDatabaseName("UX_MachineDetails_Composite_Active")
                        .HasFilter("[MachineRegistrationNo] IS NULL AND [IsDeleted] = 0");

                    b.ToTable("MachineDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.PendingCollateralResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppraisalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppraisalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HostCollateralId")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentFileName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalId")
                        .IsUnique()
                        .HasDatabaseName("UX_PendingCollateralResults_Appraisal");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_PendingCollateralResults_SentAt")
                        .HasFilter("[SentAt] IS NULL");

                    b.ToTable("PendingCollateralResults", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.ProjectDetail", b =>
                {
                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Developer")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("ProjectSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RemainingUnits")
                        .HasColumnType("int");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.HasKey("CollateralMasterId");

                    b.ToTable("ProjectDetails", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.ProjectUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CollateralMasterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CondoRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedWorkstation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LastAppraisedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoanBankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModelType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int");

                    b.Property<string>("PlotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PurchaseBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("TowerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdatedWorkstation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UsableArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CollateralMasterId");

                    b.HasIndex("CollateralMasterId", "SequenceNumber")
                        .HasDatabaseName("IX_ProjectUnits_Master_Sequence");

                    b.ToTable("ProjectUnits", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Reappraisal.ReappraisalCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AoCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AoName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("BusinessSize")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("BusinessSizeDesc")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CarCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CifName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CifNumber")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("CollateralAddress")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CollateralCategory")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CollateralCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CollateralDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollateralId")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("CollateralName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CountAgeingDate")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CpNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal?>("CurrentValue")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveDateAppraisal")
                        .HasColumnType("date");

                    b.Property<string>("ExternalValuerName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FacilityCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("FacilityLimit")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("FacilitySequence")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<string>("FlagGreaterAge4Y")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("FlagLessAge4Y")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Group")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IBGRetail")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalExternal")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("InternalValuerName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("MortgageAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("PastDueDay")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SllDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SllOver100M")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateOnly>("SourceFileDate")
                        .HasColumnType("date");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Stage")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SurveyNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TitleNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("ValuationDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ReviewDate")
                        .HasDatabaseName("IX_ReappraisalCandidate_ReviewDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ReappraisalCandidate_Status_Pending")
                        .HasFilter("[Status] = 'Pending'");

                    b.HasIndex("SourceFileDate", "CollateralId", "SurveyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ReappraisalCandidate_FileDate_CollateralId_SurveyNumber");

                    b.ToTable("ReappraisalCandidates", "collateral");
                });

            modelBuilder.Entity("Shared.Data.Lease.BackgroundServiceLease", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LeasedUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BackgroundServiceLease", "collateral");
                });

            modelBuilder.Entity("Shared.Data.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerType")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MessageId", "ConsumerType");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_InboxMessage_Cleanup");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("IX_InboxMessage_StaleProcessing");

                    b.ToTable("InboxMessage", "collateral");
                });

            modelBuilder.Entity("Shared.Data.Outbox.IntegrationEventOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Polling");

                    b.HasIndex("Status", "ProcessedAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Cleanup");

                    b.HasIndex("Status", "RetryCount")
                        .HasDatabaseName("IX_IntegrationEventOutbox_DeadLetter");

                    b.HasIndex("CorrelationId", "Status", "OccurredAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Correlation");

                    b.ToTable("IntegrationEventOutbox", "collateral");
                });

            modelBuilder.Entity("Shared.Scheduling.JobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("UX_JobSchedules_JobId");

                    b.ToTable("JobSchedules", "collateral");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralDocument", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithMany("Documents")
                        .HasForeignKey("CollateralMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollateralDocuments_CollateralMasters");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralEngagement", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithMany("Engagements")
                        .HasForeignKey("CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralEngagementBuilding", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralEngagement", null)
                        .WithMany("Buildings")
                        .HasForeignKey("EngagementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CollateralEngagementBuildings_Engagement");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMaster", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithMany()
                        .HasForeignKey("ParentMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CollateralMasters_ParentMaster");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMasterAuditLog", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CondoDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("CondoDetail")
                        .HasForeignKey("Collateral.CollateralMasters.Models.CondoDetail", "CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.CollateralMasters.Models.AppraisalSummary", "AppraisalSummary", b1 =>
                        {
                            b1.Property<Guid>("CondoDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LastAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LastAppraisalId");

                            b1.Property<string>("LastAppraisalNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastAppraisalNumber");

                            b1.Property<DateTime?>("LastAppraisedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastAppraisedDate");

                            b1.HasKey("CondoDetailCollateralMasterId");

                            b1.ToTable("CondoDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("CondoDetailCollateralMasterId");
                        });

                    b.Navigation("AppraisalSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.LandDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("LandDetail")
                        .HasForeignKey("Collateral.CollateralMasters.Models.LandDetail", "CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.CollateralMasters.Models.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("LandDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Street")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street");

                            b1.Property<string>("Village")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Village");

                            b1.HasKey("LandDetailCollateralMasterId");

                            b1.ToTable("LandDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("LandDetailCollateralMasterId");
                        });

                    b.OwnsOne("Collateral.CollateralMasters.Models.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("LandDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal?>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitude");

                            b1.HasKey("LandDetailCollateralMasterId");

                            b1.ToTable("LandDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("LandDetailCollateralMasterId");
                        });

                    b.OwnsOne("Collateral.CollateralMasters.Models.AppraisalSummary", "AppraisalSummary", b1 =>
                        {
                            b1.Property<Guid>("LandDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LastAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LastAppraisalId");

                            b1.Property<string>("LastAppraisalNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastAppraisalNumber");

                            b1.Property<DateTime?>("LastAppraisedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastAppraisedDate");

                            b1.HasKey("LandDetailCollateralMasterId");

                            b1.ToTable("LandDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("LandDetailCollateralMasterId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AppraisalSummary")
                        .IsRequired();

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.LeaseholdDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("LeaseholdDetail")
                        .HasForeignKey("Collateral.CollateralMasters.Models.LeaseholdDetail", "CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithMany()
                        .HasForeignKey("UnderlyingMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LeaseholdDetails_UnderlyingMaster");

                    b.OwnsOne("Collateral.CollateralMasters.Models.AppraisalSummary", "AppraisalSummary", b1 =>
                        {
                            b1.Property<Guid>("LeaseholdDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LastAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LastAppraisalId");

                            b1.Property<string>("LastAppraisalNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastAppraisalNumber");

                            b1.Property<DateTime?>("LastAppraisedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastAppraisedDate");

                            b1.HasKey("LeaseholdDetailCollateralMasterId");

                            b1.ToTable("LeaseholdDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("LeaseholdDetailCollateralMasterId");
                        });

                    b.Navigation("AppraisalSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.MachineDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("MachineDetail")
                        .HasForeignKey("Collateral.CollateralMasters.Models.MachineDetail", "CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.CollateralMasters.Models.AppraisalSummary", "AppraisalSummary", b1 =>
                        {
                            b1.Property<Guid>("MachineDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LastAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LastAppraisalId");

                            b1.Property<string>("LastAppraisalNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastAppraisalNumber");

                            b1.Property<DateTime?>("LastAppraisedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastAppraisedDate");

                            b1.HasKey("MachineDetailCollateralMasterId");

                            b1.ToTable("MachineDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("MachineDetailCollateralMasterId");
                        });

                    b.Navigation("AppraisalSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.ProjectDetail", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.CollateralMaster", null)
                        .WithOne("ProjectDetail")
                        .HasForeignKey("Collateral.CollateralMasters.Models.ProjectDetail", "CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Collateral.CollateralMasters.Models.AppraisalSummary", "AppraisalSummary", b1 =>
                        {
                            b1.Property<Guid>("ProjectDetailCollateralMasterId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("LastAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("LastAppraisalId");

                            b1.Property<string>("LastAppraisalNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastAppraisalNumber");

                            b1.Property<DateTime?>("LastAppraisedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("LastAppraisedDate");

                            b1.HasKey("ProjectDetailCollateralMasterId");

                            b1.ToTable("ProjectDetails", "collateral");

                            b1.WithOwner()
                                .HasForeignKey("ProjectDetailCollateralMasterId");
                        });

                    b.Navigation("AppraisalSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.ProjectUnit", b =>
                {
                    b.HasOne("Collateral.CollateralMasters.Models.ProjectDetail", null)
                        .WithMany("Units")
                        .HasForeignKey("CollateralMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectUnits_CollateralMasters");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralEngagement", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.CollateralMaster", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CondoDetail");

                    b.Navigation("Documents");

                    b.Navigation("Engagements");

                    b.Navigation("LandDetail");

                    b.Navigation("LeaseholdDetail");

                    b.Navigation("MachineDetail");

                    b.Navigation("ProjectDetail");
                });

            modelBuilder.Entity("Collateral.CollateralMasters.Models.ProjectDetail", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
