namespace Request.Application.Features.RequestTitles.GetTitleDocumentsByTitleId;

public record GetLinkRequestTitleDocumentsByTitleIdQuery(Guid RequestId, Guid TitleId) : IQuery<GetLinkRequestTitleDocumentsByTitleIdResult>;