namespace Appraisal.Application.Features.MarketComparableTemplates.GetMarketComparableTemplateById;

public record GetMarketComparableTemplateByIdResponse(MarketComparableTemplateDetailDto Template);
