@baseUrl= https://localhost:7111
@requestId=B65E497C-D3E9-41E4-BC46-190AAB36A50C

PATCH {{baseUrl}}/requests/{{requestId}}
headers: localhost:7111
Content-Type: application/json

{
    "sessionId" : "991495AE-F065-4B2C-8249-B6BEF197CA13",
    "detail" :{
        "hasAppraisalBook" : false,
        "loanDetail" : 
        {
            "loanApplicationNo" : "01",
            "bankingSegment" : "RB",
            "facilityLimit" : 1700000,
            "additionalFacilityLimit" : 500000,
            "previousFacilityLimit" : 1200000,
            "totalSellingPrice" : 1200000
        },
        "prevAppraisalNo" : null,
        "address": 
        {
            "houseNo": "update 5/42",
            "roomNo": "string",
            "floorNo": "string",
            "buildingNo": "string",
            "projectName" : "string",
            "moo": "3",
            "soi": "string",
            "road": "string",
            "subDistrict": "string",
            "district": "string",
            "province": "string",
            "postcode": "string"
        },
        "contact" : 
        {
            "contactPersonName": "string",
            "contactPersonContactNo": "string",
            "projectCode": "string"
        },
        "appointment" : 
        {
            "appointmentDateTime" : "2025-06-20T08:39:32.515Z",
            "appointmentLocation" : "Q House Lumpini"
        },
        "fee" : 
        {
            "feeType" : "01",
            "feeNote" : "No additional fees",
            "bankAbsorbAmt" : 1
        }
    },
    "isPMA": false,
    "purpose" : "Test",
    "priority" : "High",
    "sourcesystem" : {
        "channel" : "CLS",
        "requestDate" : "2025-06-20T08:39:32.515Z",
        "requestBy" : "01",
        "requestByName" : "John",
        "createdDate" :  "2025-06-20T08:39:32.515Z",
        "creator" : "211",
        "creatorName" : "John"
    },
    "customers": [
        {
            "name": "abc",
            "contactNumber": "0123456789"
        },
        {
            "name": "Joe",
            "contactNumber": "0123456789"
        }
    ],
    "properties": [
        {
            "propertyType": "abc",
            "buildingType": "abc",
            "sellingPrice": 1
        }
    ],
    "documents": [
    ],
    "titles": [
    ]
}