# Delete Role Instance
# Delete a role instance.

### Variables for the request
@roleId = 9b054dc6-1ea6-4d05-8580-08ddfa72cbe8

### Delete Role Instance
DELETE {{baseUrl}}/auth/roles/{{roleId}} HTTP/1.1
Host: localhost:7111