### Get All Requests - Default pagination
GET {{baseUrl}}/requests
Host: localhost:7111
Content-Type: application/json

### Get All Requests - With pagination
GET {{baseUrl}}/requests?page=1&pageSize=10
Host: localhost:7111
Content-Type: application/json

### Get All Requests - Second page
GET {{baseUrl}}/requests?pageNumber=2&pageSize=10
Host: localhost:7111
Content-Type: application/json
