@requestId = 2EF682E6-2DA9-4EAE-B398-F68BC16DE48E

@commentId = 76080C67-FCD4-4052-B808-B8F8C72462C3

DELETE {{baseUrl}}/requests/{{requestId}}/comments/{{commentId}}
Host: localhost:7111
Content-Type: application/json

{
}