# Start a workflow instance using the workflow definition
# This request starts a workflow instance based on the provided definition.

### Variables for the request
@baseUrl = https://localhost:7111

### Create Workflow Definition
// @timeout = 30000 m
POST {{baseUrl}}/api/workflows/instances/start
Content-Type: application/json

{
  "workflowDefinitionId" : "ece65c7e-d5b6-47cb-b66b-36efa7f9c6f1",
  "instanceName" : "Collateral Appraisal Workflow",
  "startedBy" : "system",
  "initialVariables" : {
    "decisionTaken" : ""
  },
  "correlationId" : "1"
}