@baseUrl = https://localhost:7111
@requestId = E65DA0BB-2B24-4479-597E-08DE2BF89D72
PATCH {{baseUrl}}/requests/{{requestId}}/titles
Host: localhost:7111
Content-Type: application/json

{
    "requestTitleDtos":
    [
        {
            "id": "0BDE0758-5244-48CA-9111-F5907EF99BFA",
            "collateralType": "L",
            "collateralStatus": false,
            "titleNo": "Test",
            "deedType": "NorSor3",
            "titleDetail": "Test",
            "rawang": "Test",
            "landNo": "Test",
            "surveyNo": "Test",
            "areaRai": 0,
            "areaNgan": 0,
            "areaSquareWa": 0,
            "ownerName": "Test",
            "titleAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "dopaAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "notes": "Test",
            "requestTitleDocumentDtos":
            [
                {
                    "id": "773241B0-9456-4178-96B4-588C15AF4AEE",
                    "documentId": "84DCBD01-8544-41D9-8125-874C963C8003",
                    "documentType": "Test",
                    "filename": "Test",
                    "prefix": "Test",
                    "set": 1,
                    "documentDescription": "Update Test",
                    "filePath": "Test",
                    "createdWorkstation": "Test",
                    "isRequired": true,
                    "uploadedBy": "Test",
                    "uploadedByName": "Test"
                },
                {
                    "documentId": "84DCBD01-8544-41D9-8125-874C963C8005",
                    "documentType": "Test",
                    "filename": "Test",
                    "prefix": "Test",
                    "set": 1,
                    "documentDescription": "Update Test",
                    "filePath": "Test",
                    "createdWorkstation": "Test",
                    "isRequired": true,
                    "uploadedBy": "Test",
                    "uploadedByName": "Test"
                }
            ]
        }
    ]
}