@requestId = 2EF682E6-2DA9-4EAE-B398-F68BC16DE48E

@commentId = 10924CBD-0251-4E60-81D5-AB443FA3C15C

PATCH {{baseUrl}}/requests/{{requestId}}/comments/{{commentId}}
Host: localhost:7111
Content-Type: application/json

{
    "comment": "Update Hello World! x2",
    "commentedBy": "Update xxxxx1",
    "commentedByName": "Update John Doe"
}