@baseUrl= https://localhost:7111
@requestId=7038B133-76B3-4D69-ADF6-31E466DD4F8C?sessionId=8DAE3CDB-9DA2-430E-9024-B58DF78F0000

DELETE {{baseUrl}}/requests/{{requestId}}
headers: localhost:7111
Content-Type: application/json

{
}