@baseUrl= https://localhost:7111
@requestId=BB9640C6-3DBB-4161-B0DF-54CD2D4FA4C1

PATCH {{baseUrl}}/requests/{{requestId}}/draft
headers: localhost:7111
Content-Type: application/json

{
    "sessionId" : "991495AE-F065-4B2C-8249-B6BEF197CA13",
    "detail" :{
        "hasAppraisalBook" : false,
        "loanDetail" : 
        {
            "loanApplicationNo" : "01",
            "bankingSegment" : "RB",
            "facilityLimit" : 1700000,
            "additionalFacilityLimit" : 500000,
            "previousFacilityLimit" : 1200000,
            "totalSellingPrice" : 1200000
        },
        "prevAppraisalNo" : null,
        "address": 
        {
            "houseNo": "update 5/42",
            "roomNo": "string",
            "floorNo": "string",
            "buildingNo": "string",
            "projectName" : "string",
            "moo": "3",
            "soi": "string",
            "road": "string",
            "subDistrict": "string",
            "district": "string",
            "province": "string",
            "postcode": "string"
        },
        "contact" : 
        {
            "contactPersonName": "string",
            "contactPersonContactNo": "string",
            "projectCode": "string"
        },
        "appointment" : 
        {
            "appointmentDateTime" : "2025-06-20T08:39:32.515Z",
            "appointmentLocation" : "Q House Lumpini"
        },
        "fee" : 
        {
            "feeType" : "01",
            "feeNote" : "No additional fees",
            "bankAbsorbAmt" : 1
        }
    },
    "isPMA": false,
    "purpose" : "Test",
    "priority" : "High",
    "sourcesystem" : {
        "channel" : "CLS",
        "requestDate" : "2025-06-20T08:39:32.515Z",
        "requestBy" : "01",
        "requestByName" : "John",
        "createdDate" :  "2025-06-20T08:39:32.515Z",
        "creator" : "211",
        "creatorName" : "John"
    },
    "customers": [
        {
            "name": "abc",
            "contactNumber": "0123456789"
        },
        {
            "name": "Joe",
            "contactNumber": "0123456789"
        }
    ],
    "properties": [
        {
            "propertyType": "abc",
            "buildingType": "abc",
            "sellingPrice": 1
        }
    ],
    "documents": [
        {
            "id": "830E92CB-77FF-4FCE-A2D8-08DE31708C42",
            "documentId": "0d6c4968-d855-4bf8-a9c7-3196b14ea700",
            "documentClassification": 
            {
                "documentType": "Document",
                "isRequired": true
            },
            "fileName":"M-001 Map",
            "filePath":"C:/Users/Desktop/Document/Other",
            "prefix":"M-001",
            "set":1,
            "uploadInfo": 
            {
                "uploadedBy": "211",
                "uploadedByName": "John",
                "uploadedAt": "2025-06-20T08:39:32.515Z"
            },
            "documentDescription": "comment"
        }
    ],
    "comments": [
        {
            "comment": "This is the first comment.",
            "commentedBy": "211",
            "commentedByName": "John"
        },
        {
            "comment": "This is the second comment.",
            "commentedBy": "212",
            "commentedByName": "Doe"
        }
    ],
    "titles": [
        {
            "collateralType": "L",
            "collateralStatus": false,
            "titleAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "dopaAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "notes": "Test",
            "requestTitleDocumentDtos":
            [
                {
                    "documentId": "84DCBD01-8544-41D9-8125-874C963C8003",
                    "documentType": "Test Update",
                    "filename": "Test Update",
                    "prefix": "Test Update",
                    "set": 1,
                    "documentDescription": "Test Update",
                    "filePath": "Test Update",
                    "createdWorkstation": "Test Update",
                    "isRequired": true,
                    "uploadedBy": "Update",
                    "uploadedByName": "Test Update"
                }
            ]
        }
    ]
}