// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Request.Infrastructure;

#nullable disable

namespace Request.Infrastructure.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20260201090202_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("request")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "request");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage", "request");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "request");
                });

            modelBuilder.Entity("Request.Domain.RequestComments.RequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CommentedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestComments", "request");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.RequestTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("CollateralStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_TitleDeedInfo_RequestId");

                    b.ToTable("RequestTitles", "request");

                    b.HasDiscriminator<string>("CollateralType").HasValue("RequestTitle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Request.Domain.Requests.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPma")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Request_RequestedAt")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Requests", "request");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleBuilding", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("B");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleCondo", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("U");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLand", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("L");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLandBuilding", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("LB");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementBuilding", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("LSB");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementCondo", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("LSU");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementLand", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("LSL");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementLandBuilding", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("LS");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleMachine", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("MAC");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleVehicle", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("VEH");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleVessel", b =>
                {
                    b.HasBaseType("Request.Domain.RequestTitles.RequestTitle");

                    b.HasDiscriminator().HasValue("VES");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.RequestTitle", b =>
                {
                    b.OwnsOne("Request.Domain.Requests.Address", "DopaAddress", b1 =>
                        {
                            b1.Property<Guid>("RequestTitleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("District")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaDistrict");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("DopaHouseNumber");

                            b1.Property<string>("Moo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaMoo");

                            b1.Property<string>("Postcode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaPostcode");

                            b1.Property<string>("ProjectName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DopaProjectName");

                            b1.Property<string>("Province")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaProvince");

                            b1.Property<string>("Road")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaRoad");

                            b1.Property<string>("Soi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaSoi");

                            b1.Property<string>("SubDistrict")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaSubDistrict");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsOne("Request.Domain.Requests.Address", "TitleAddress", b1 =>
                        {
                            b1.Property<Guid>("RequestTitleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("District")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("District");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("HouseNumber");

                            b1.Property<string>("Moo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Moo");

                            b1.Property<string>("Postcode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Postcode");

                            b1.Property<string>("ProjectName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ProjectName");

                            b1.Property<string>("Province")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Province");

                            b1.Property<string>("Road")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Road");

                            b1.Property<string>("Soi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Soi");

                            b1.Property<string>("SubDistrict")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("SubDistrict");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsMany("Request.Domain.RequestTitles.TitleDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DocumentType")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("Filename")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Prefix")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("Set")
                                .HasColumnType("int");

                            b1.Property<Guid>("TitleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateTime?>("UpdatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("UploadedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UploadedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("UploadedByName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("TitleId", "DocumentId")
                                .IsUnique()
                                .HasDatabaseName("IX_TitleDocument_Title_Document")
                                .HasFilter("[DocumentId] IS NOT NULL");

                            b1.ToTable("RequestTitleDocuments", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleId");
                        });

                    b.Navigation("Documents");

                    b.Navigation("DopaAddress")
                        .IsRequired();

                    b.Navigation("TitleAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.Requests.Request", b =>
                {
                    b.OwnsOne("Shared.Models.UserInfo", "Creator", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Creator");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatorName");

                            b1.HasKey("RequestId");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Shared.Models.UserInfo", "Requestor", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Requestor");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("RequestorName");

                            b1.HasKey("RequestId");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("IX_Request_Requestor")
                                .HasFilter("[IsDeleted] = 0");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsMany("Request.Domain.Requests.RequestCustomer", "Customers", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("ContactNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContactNumber");

                            b1.Property<string>("Name")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("Name");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("Name")
                                .HasDatabaseName("IX_RequestCustomer_Name");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestCustomers", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Domain.Requests.RequestDetail", "Detail", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("HasAppraisalBook")
                                .HasColumnType("bit")
                                .HasColumnName("HasAppraisalBook");

                            b1.Property<Guid?>("PrevAppraisalId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PrevAppraisalId");

                            b1.HasKey("RequestId");

                            b1.ToTable("RequestDetails", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Request.Domain.Requests.Appointment", "Appointment", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime?>("AppointmentDateTime")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("AppointmentDateTime");

                                    b2.Property<string>("AppointmentLocation")
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("AppointmentLocation");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Domain.Requests.Contact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContactPersonName")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("ContactPersonName");

                                    b2.Property<string>("ContactPersonPhone")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("ContactPersonPhone");

                                    b2.Property<string>("DealerCode")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("DealerCode");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Domain.Requests.Fee", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal?>("AbsorbedAmount")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("AbsorbedAmount");

                                    b2.Property<string>("FeeNotes")
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("FeeNotes");

                                    b2.Property<string>("FeePaymentType")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("FeePaymentType");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Domain.Requests.LoanDetail", "LoanDetail", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal?>("AdditionalFacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("AdditionalFacilityLimit");

                                    b2.Property<string>("BankingSegment")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("BankingSegment");

                                    b2.Property<decimal?>("FacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("FacilityLimit");

                                    b2.Property<string>("LoanApplicationNumber")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("LoanApplicationNumber");

                                    b2.Property<decimal?>("PreviousFacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("PreviousFacilityLimit");

                                    b2.Property<decimal?>("TotalSellingPrice")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("TotalSellingPrice");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.HasIndex("LoanApplicationNumber")
                                        .HasDatabaseName("IX_Request_LoanApplicationNumber")
                                        .HasFilter("[LoanApplicationNumber] IS NOT NULL");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Domain.Requests.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("District")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("District");

                                    b2.Property<string>("HouseNumber")
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("HouseNumber");

                                    b2.Property<string>("Moo")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Moo");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("ProjectName")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("ProjectName");

                                    b2.Property<string>("Province")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Province");

                                    b2.Property<string>("Road")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Road");

                                    b2.Property<string>("Soi")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Soi");

                                    b2.Property<string>("SubDistrict")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("SubDistrict");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.Navigation("Address");

                            b1.Navigation("Appointment");

                            b1.Navigation("Contact");

                            b1.Navigation("Fee");

                            b1.Navigation("LoanDetail");
                        });

                    b.OwnsMany("Request.Domain.Requests.RequestDocument", "Documents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CreatedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateTime?>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("DocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DocumentType")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("FilePath")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("Notes")
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.Property<string>("Prefix")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<short?>("Set")
                                .HasColumnType("smallint");

                            b1.Property<string>("Source")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("UpdatedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<DateTime?>("UpdatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("UploadedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("UploadedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("UploadedByName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("RequestId", "DocumentId")
                                .IsUnique()
                                .HasDatabaseName("IX_RequestDocument_Request_Document")
                                .HasFilter("[DocumentId] IS NOT NULL");

                            b1.ToTable("RequestDocuments", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Domain.Requests.RequestNumber", "RequestNumber", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("RequestNumber");

                            b1.HasKey("RequestId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_Request_RequestNumber");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsMany("Request.Domain.Requests.RequestProperty", "Properties", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BuildingType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<string>("PropertyType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PropertyType");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("SellingPrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("SellingPrice");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyType")
                                .HasDatabaseName("IX_RequestProperty_PropertyType");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestProperties", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Domain.Requests.RequestStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Status");

                            b1.HasKey("RequestId");

                            b1.HasIndex("Code")
                                .HasDatabaseName("IX_Request_Status")
                                .HasFilter("[IsDeleted] = 0");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Domain.Requests.SoftDelete", "SoftDelete", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("DeletedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAt");

                            b1.Property<string>("DeletedBy")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DeletedBy");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("RequestId");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.Navigation("Creator")
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Detail");

                    b.Navigation("Documents");

                    b.Navigation("Properties");

                    b.Navigation("RequestNumber");

                    b.Navigation("Requestor")
                        .IsRequired();

                    b.Navigation("SoftDelete")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleBuilding", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.BuildingInfo", "BuildingInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<int?>("NumberOfBuilding")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("NumberOfBuilding");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleBuildingId");
                        });

                    b.Navigation("BuildingInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleCondo", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.CondoInfo", "CondoInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleCondoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BuildingNumber");

                            b1.Property<string>("CondoName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CondoName");

                            b1.Property<string>("FloorNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FloorNumber");

                            b1.Property<string>("RoomNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RoomNumber");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleCondoId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleCondoId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleCondoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleCondoId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleCondoId");
                        });

                    b.Navigation("CondoInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLand", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.LandArea", "LandArea", b1 =>
                        {
                            b1.Property<Guid>("TitleLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AreaNgan")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaNgan");

                            b1.Property<int?>("AreaRai")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaRai");

                            b1.Property<decimal?>("AreaSquareWa")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("AreaSquareWa");

                            b1.HasKey("TitleLandId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandLocationInfo", "LandLocationInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AerialMapName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapName");

                            b1.Property<string>("AerialMapNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapNumber");

                            b1.Property<string>("BookNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BookNumber");

                            b1.Property<string>("LandParcelNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LandParcelNumber");

                            b1.Property<string>("MapSheetNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MapSheetNumber");

                            b1.Property<string>("PageNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PageNumber");

                            b1.Property<string>("Rawang")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Rawang");

                            b1.Property<string>("SurveyNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SurveyNumber");

                            b1.HasKey("TitleLandId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleLandId");

                            b1.HasIndex("TitleNumber")
                                .HasDatabaseName("IX_TitleDeedInfo_TitleDeedNumber");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandId");
                        });

                    b.Navigation("LandArea")
                        .IsRequired();

                    b.Navigation("LandLocationInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLandBuilding", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.BuildingInfo", "BuildingInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<int?>("NumberOfBuilding")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("NumberOfBuilding");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandArea", "LandArea", b1 =>
                        {
                            b1.Property<Guid>("TitleLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AreaNgan")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaNgan");

                            b1.Property<int?>("AreaRai")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaRai");

                            b1.Property<decimal?>("AreaSquareWa")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("AreaSquareWa");

                            b1.HasKey("TitleLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandLocationInfo", "LandLocationInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AerialMapName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapName");

                            b1.Property<string>("AerialMapNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapNumber");

                            b1.Property<string>("BookNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BookNumber");

                            b1.Property<string>("LandParcelNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LandParcelNumber");

                            b1.Property<string>("MapSheetNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MapSheetNumber");

                            b1.Property<string>("PageNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PageNumber");

                            b1.Property<string>("Rawang")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Rawang");

                            b1.Property<string>("SurveyNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SurveyNumber");

                            b1.HasKey("TitleLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLandBuildingId");
                        });

                    b.Navigation("BuildingInfo")
                        .IsRequired();

                    b.Navigation("LandArea")
                        .IsRequired();

                    b.Navigation("LandLocationInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementBuilding", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.BuildingInfo", "BuildingInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<int?>("NumberOfBuilding")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("NumberOfBuilding");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleLeaseAgreementBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementBuildingId");
                        });

                    b.Navigation("BuildingInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementCondo", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.CondoInfo", "CondoInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementCondoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BuildingNumber");

                            b1.Property<string>("CondoName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CondoName");

                            b1.Property<string>("FloorNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FloorNumber");

                            b1.Property<string>("RoomNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RoomNumber");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleLeaseAgreementCondoId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementCondoId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementCondoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleLeaseAgreementCondoId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementCondoId");
                        });

                    b.Navigation("CondoInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementLand", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.LandArea", "LandArea", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AreaNgan")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaNgan");

                            b1.Property<int?>("AreaRai")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaRai");

                            b1.Property<decimal?>("AreaSquareWa")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("AreaSquareWa");

                            b1.HasKey("TitleLeaseAgreementLandId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandLocationInfo", "LandLocationInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AerialMapName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapName");

                            b1.Property<string>("AerialMapNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapNumber");

                            b1.Property<string>("BookNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BookNumber");

                            b1.Property<string>("LandParcelNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LandParcelNumber");

                            b1.Property<string>("MapSheetNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MapSheetNumber");

                            b1.Property<string>("PageNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PageNumber");

                            b1.Property<string>("Rawang")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Rawang");

                            b1.Property<string>("SurveyNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SurveyNumber");

                            b1.HasKey("TitleLeaseAgreementLandId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleLeaseAgreementLandId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandId");
                        });

                    b.Navigation("LandArea")
                        .IsRequired();

                    b.Navigation("LandLocationInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleLeaseAgreementLandBuilding", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.BuildingInfo", "BuildingInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BuildingType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<int?>("NumberOfBuilding")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("NumberOfBuilding");

                            b1.Property<decimal?>("UsableArea")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("UsableArea");

                            b1.HasKey("TitleLeaseAgreementLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandArea", "LandArea", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AreaNgan")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaNgan");

                            b1.Property<int?>("AreaRai")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("int")
                                .HasColumnName("AreaRai");

                            b1.Property<decimal?>("AreaSquareWa")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("AreaSquareWa");

                            b1.HasKey("TitleLeaseAgreementLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.LandLocationInfo", "LandLocationInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AerialMapName")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapName");

                            b1.Property<string>("AerialMapNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AerialMapNumber");

                            b1.Property<string>("BookNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("BookNumber");

                            b1.Property<string>("LandParcelNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LandParcelNumber");

                            b1.Property<string>("MapSheetNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("MapSheetNumber");

                            b1.Property<string>("PageNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("PageNumber");

                            b1.Property<string>("Rawang")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Rawang");

                            b1.Property<string>("SurveyNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("SurveyNumber");

                            b1.HasKey("TitleLeaseAgreementLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandBuildingId");
                        });

                    b.OwnsOne("Request.Domain.RequestTitles.TitleDeedInfo", "TitleDeedInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleLeaseAgreementLandBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TitleNumber")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("TitleNumber");

                            b1.Property<string>("TitleType")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TitleType");

                            b1.HasKey("TitleLeaseAgreementLandBuildingId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleLeaseAgreementLandBuildingId");
                        });

                    b.Navigation("BuildingInfo")
                        .IsRequired();

                    b.Navigation("LandArea")
                        .IsRequired();

                    b.Navigation("LandLocationInfo")
                        .IsRequired();

                    b.Navigation("TitleDeedInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleMachine", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.MachineInfo", "MachineInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleMachineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("InstallationStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("InstallationStatus");

                            b1.Property<string>("InvoiceNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("InvoiceNumber");

                            b1.Property<string>("MachineType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MachineType");

                            b1.Property<int?>("NumberOfMachine")
                                .HasColumnType("int")
                                .HasColumnName("NumberOfMachine");

                            b1.Property<string>("RegistrationNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("RegistrationNumber");

                            b1.HasKey("TitleMachineId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleMachineId");
                        });

                    b.Navigation("MachineInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleVehicle", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.VehicleInfo", "VehicleInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleVehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LicensePlateNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("LicensePlateNumber");

                            b1.Property<string>("VIN")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("VIN");

                            b1.Property<string>("VehicleLocation")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("VehicleLocation");

                            b1.Property<string>("VehicleType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("VehicleType");

                            b1.HasKey("TitleVehicleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleVehicleId");
                        });

                    b.Navigation("VehicleInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Domain.RequestTitles.TitleTypes.TitleVessel", b =>
                {
                    b.OwnsOne("Request.Domain.RequestTitles.VesselInfo", "VesselInfo", b1 =>
                        {
                            b1.Property<Guid>("TitleVesselId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HIN")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("HIN");

                            b1.Property<string>("VesselLocation")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("VesselLocation");

                            b1.Property<string>("VesselRegistrationNumber")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("VesselRegistrationNumber");

                            b1.Property<string>("VesselType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("VesselType");

                            b1.HasKey("TitleVesselId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("TitleVesselId");
                        });

                    b.Navigation("VesselInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
