namespace Appraisal.Application.Features.BlockVillage.GetVillageModels;

internal static class VillageModelMapper
{
    internal static VillageModelDto ToDto(VillageModel m) => new(
        Id: m.Id,
        AppraisalId: m.AppraisalId,
        ModelName: m.ModelName,
        ModelDescription: m.ModelDescription,
        NumberOfHouse: m.NumberOfHouse,
        StartingPrice: m.StartingPrice,
        UsableAreaMin: m.UsableAreaMin,
        UsableAreaMax: m.UsableAreaMax,
        StandardUsableArea: m.StandardUsableArea,
        LandAreaRai: m.LandAreaRai,
        LandAreaNgan: m.LandAreaNgan,
        LandAreaWa: m.LandAreaWa,
        StandardLandArea: m.StandardLandArea,
        FireInsuranceCondition: m.FireInsuranceCondition,
        ImageDocumentIds: m.ImageDocumentIds,
        BuildingType: m.BuildingType,
        BuildingTypeOther: m.BuildingTypeOther,
        NumberOfFloors: m.NumberOfFloors,
        DecorationType: m.DecorationType,
        DecorationTypeOther: m.DecorationTypeOther,
        IsEncroachingOthers: m.IsEncroachingOthers,
        EncroachingOthersRemark: m.EncroachingOthersRemark,
        EncroachingOthersArea: m.EncroachingOthersArea,
        BuildingMaterialType: m.BuildingMaterialType,
        BuildingStyleType: m.BuildingStyleType,
        IsResidential: m.IsResidential,
        BuildingAge: m.BuildingAge,
        ConstructionYear: m.ConstructionYear,
        ResidentialRemark: m.ResidentialRemark,
        ConstructionStyleType: m.ConstructionStyleType,
        ConstructionStyleRemark: m.ConstructionStyleRemark,
        StructureType: m.StructureType,
        StructureTypeOther: m.StructureTypeOther,
        RoofFrameType: m.RoofFrameType,
        RoofFrameTypeOther: m.RoofFrameTypeOther,
        RoofType: m.RoofType,
        RoofTypeOther: m.RoofTypeOther,
        CeilingType: m.CeilingType,
        CeilingTypeOther: m.CeilingTypeOther,
        InteriorWallType: m.InteriorWallType,
        InteriorWallTypeOther: m.InteriorWallTypeOther,
        ExteriorWallType: m.ExteriorWallType,
        ExteriorWallTypeOther: m.ExteriorWallTypeOther,
        FenceType: m.FenceType,
        FenceTypeOther: m.FenceTypeOther,
        ConstructionType: m.ConstructionType,
        ConstructionTypeOther: m.ConstructionTypeOther,
        UtilizationType: m.UtilizationType,
        UtilizationTypeOther: m.UtilizationTypeOther,
        Remark: m.Remark,
        AreaDetails: m.AreaDetails.Select(a => new VillageModelAreaDetailResultDto(a.Id, a.AreaDescription, a.AreaSize)).ToList(),
        Surfaces: m.Surfaces.Select(s => new VillageModelSurfaceResultDto(
            s.Id, s.FromFloorNumber, s.ToFloorNumber, s.FloorType,
            s.FloorStructureType, s.FloorStructureTypeOther, s.FloorSurfaceType, s.FloorSurfaceTypeOther)).ToList(),
        DepreciationDetails: m.DepreciationDetails.Select(d => new VillageModelDepreciationDetailResultDto(
            d.Id, d.DepreciationMethod, d.AreaDescription, d.Area, d.Year, d.IsBuilding,
            d.PricePerSqMBeforeDepreciation, d.PriceBeforeDepreciation, d.PricePerSqMAfterDepreciation,
            d.PriceAfterDepreciation, d.DepreciationYearPct, d.TotalDepreciationPct, d.PriceDepreciation,
            d.DepreciationPeriods.Select(p => new VillageModelDepreciationPeriodResultDto(
                p.Id, p.AtYear, p.ToYear, p.DepreciationPerYear, p.TotalDepreciationPct, p.PriceDepreciation)).ToList()
        )).ToList()
    );
}
