using Appraisal.Domain.Appraisals;
using Appraisal.Domain.Projects;
using Request.Contracts.Requests.Dtos;
using Shared.Identity;

namespace Appraisal.Application.Services;

/// <summary>
/// Service implementation for creating appraisals from request submissions.
/// Creates the appraisal aggregate with properties, groups, an initial assignment, fee, and appointment.
/// </summary>
public class AppraisalCreationService(
    IAppraisalRepository appraisalRepository,
    IAppraisalUnitOfWork unitOfWork,
    AppraisalDbContext dbContext,
    ICurrentUserService currentUserService,
    ILogger<AppraisalCreationService> logger) : IAppraisalCreationService
{
    public async Task<Guid> CreateAppraisalFromRequest(
        Guid requestId,
        List<RequestTitleDto> requestTitles,
        AppointmentDto? appointment = null,
        FeeDto? fee = null,
        ContactDto? contact = null,
        string? createdBy = null,
        string? priority = null,
        bool isPma = false,
        string? purpose = null,
        string? channel = null,
        string? bankingSegment = null,
        decimal? facilityLimit = null,
        bool hasAppraisalBook = false,
        string? requestedBy = null,
        DateTime? requestedAt = null,
        Guid? prevAppraisalId = null,
        string? appraisalType = null,
        CancellationToken cancellationToken = default)
    {
        logger.LogInformation("Creating appraisal from request {RequestId} with {TitleCount} titles",
            requestId, requestTitles.Count);

        // Step 1: Check idempotency - does an appraisal already exist for this request?
        var existingAppraisal = await appraisalRepository.GetByRequestIdAsync(requestId, cancellationToken);
        if (existingAppraisal is not null)
        {
            var existingId = existingAppraisal.Id;
            logger.LogInformation("Appraisal already exists for request {RequestId}: {AppraisalId}",
                requestId, existingId);
            return existingId;
        }

        // Step 2: Filter for supported collateral types via new 33-code parameter table
        var titlesToProcess = requestTitles
            .Where(t => CodeToAppraisalFamily.ContainsKey(t.CollateralType ?? ""))
            .ToList();

        var skipped = requestTitles.Except(titlesToProcess).ToList();
        foreach (var s in skipped)
            logger.LogWarning(
                "Skipping title {TitleNumber} with unsupported collateral type {Code} on request {RequestId}",
                s.TitleNumber, s.CollateralType, requestId);

        if (!titlesToProcess.Any())
            logger.LogWarning(
                "No supported titles found for request {RequestId}. Creating appraisal with no properties.",
                requestId);

        logger.LogInformation("Processing {TitleCount} titles for request {RequestId}",
            titlesToProcess.Count, requestId);

        var isConstructionInspection = appraisalType == AppraisalTypes.ConstructionInspection
                                       && prevAppraisalId.HasValue;

        // Step 3: Create Appraisal aggregate
        var resolvedAppraisalType = isConstructionInspection ? AppraisalTypes.ConstructionInspection : AppraisalTypes.New;
        var appraisal = Domain.Appraisals.Appraisal.Create(
            requestId,
            resolvedAppraisalType,
            priority ?? "Normal",
            7, // TODO: Default SLA of 30 days
            requestedBy ?? createdBy,
            isPma,
            purpose,
            channel,
            bankingSegment,
            facilityLimit,
            hasAppraisalBook,
            requestedAt);

        // AppraisalNumber is auto-generated by AppraisalUnitOfWork on SaveChangesAsync

        if (isConstructionInspection)
        {
            // Step 4 (CI path): Deep-copy properties from the prior appraisal.
            // ConstructionInspection detail is intentionally excluded — it stays empty for fresh CI tracking.
            await CopyPropertiesFromPriorAppraisalAsync(appraisal, prevAppraisalId!.Value, cancellationToken);
        }
        else
        {
            // Step 4 (normal path): Partition titles and create properties.
            //   - Land family (L, LB): collapse into ONE property; promote to LB if any LB present.
            //     All land titles merge into the single LandDetail.
            //   - Lease land family (LSL, LS): same rule, independent from non-lease family.
            //   - B, LSB: not auto-created (appraiser adds manually).
            //   - U, VEH, VES, MAC: one property per title.
            var landFamily = titlesToProcess.Where(t => GetAppraisalFamily(t) is "L" or "LB").ToList();
            var leaseLandFamily = titlesToProcess.Where(t => GetAppraisalFamily(t) is "LSL" or "LS").ToList();
            var notAutoCreated = titlesToProcess.Where(t => GetAppraisalFamily(t) is "B" or "LSB").ToList();

            foreach (var t in notAutoCreated)
                logger.LogInformation(
                    "Title {TitleNumber} ({Code}) will not be auto-created as a property; appraiser will add manually.",
                    t.TitleNumber, t.CollateralType);

            if (landFamily.Any())
                CreateLandFamilyProperty(appraisal, landFamily);

            if (leaseLandFamily.Any())
                CreateLeaseLandFamilyProperty(appraisal, leaseLandFamily);

            foreach (var title in titlesToProcess)
            {
                switch (GetAppraisalFamily(title))
                {
                    case "U":   CreateCondoProperty(appraisal, title); break;
                    case "VEH": CreateVehicleProperty(appraisal, title); break;
                    case "VES": CreateVesselProperty(appraisal, title); break;
                    case "MAC": CreateMachineryProperty(appraisal, title); break;
                }
            }
        }

        // Wrap all saves in an explicit transaction to prevent partial success.
        // Three phases: (1) appraisal + properties, (2) group + assignment, (3) fee + appointment.
        // Owned entities need a save to get DB-generated IDs; the assignment must exist in DB
        // before entities with FK references to it (Appointment, AppraisalFee) can be inserted.
        await unitOfWork.BeginTransactionAsync(cancellationToken);
        try
        {
            // Phase 1: Save appraisal + properties to get real IDs from NEWSEQUENTIALID()
            await appraisalRepository.AddAsync(appraisal, cancellationToken);
            await unitOfWork.SaveChangesAsync(cancellationToken);

            logger.LogInformation("Saved appraisal {AppraisalId} with {PropertyCount} properties (IDs assigned by DB)",
                appraisal.Id, appraisal.Properties.Count);

            // Pre-generate appendices from active AppendixType configuration
            var activeAppendixTypes = await dbContext.AppendixTypes
                .Where(t => t.IsActive)
                .OrderBy(t => t.SortOrder)
                .ToListAsync(cancellationToken);

            foreach (var appendixType in activeAppendixTypes)
            {
                var appendix = AppraisalAppendix.Create(
                    appraisal.Id, appendixType.Id, appendixType.SortOrder);
                dbContext.AppraisalAppendices.Add(appendix);
            }

            await unitOfWork.SaveChangesAsync(cancellationToken);

            logger.LogInformation("Pre-generated {Count} appendices for appraisal {AppraisalId}",
                activeAppendixTypes.Count, appraisal.Id);

            // Initialize Project for BlockLand (32) and BlockCondo (33)
            var projectTitles = titlesToProcess.Where(t => ProjectCodes.Contains(t.CollateralType ?? "")).ToList();
            if (projectTitles.Any())
            {
                var projectCode = projectTitles.First().CollateralType;
                var projectType = projectCode == "32" ? ProjectType.LandAndBuilding : ProjectType.Condo;
                var project = Project.Create(appraisal.Id, projectType);
                dbContext.Projects.Add(project);
                await unitOfWork.SaveChangesAsync(cancellationToken);
                logger.LogInformation("Initialized Project {ProjectId} (type={ProjectType}) for appraisal {AppraisalId}",
                    project.Id, projectType, appraisal.Id);
            }

            // Phase 2: Create group + assignment, then save so the assignment row exists in DB
            // before we create entities (Appointment, AppraisalFee) that FK-reference it.
            var initialGroup = appraisal.CreateGroup("Group 1", "Auto-generated group for all properties");

            foreach (var property in appraisal.Properties) initialGroup.AddProperty(property.Id);

            // var assignment = appraisal.Assign(
            //     "Internal",
            //     null,
            //     null,
            //     "Manual",
            //     assignedBy: createdBy ?? string.Empty);

            var assignment = appraisal.AssignAdmin();

            // Explicitly add assignment via DbSet so EF Core traverses the entity graph
            // (including OwnsOne value objects like AssignmentType/AssignmentStatus) and marks
            // everything as Added. Without this, DetectChanges discovers the assignment through
            // the aggregate's HasMany collection with a non-sentinel key + ValueGeneratedOnAdd,
            // causing EF Core to assume it already exists (UPDATE instead of INSERT).
            dbContext.AppraisalAssignments.Add(assignment);

            await unitOfWork.SaveChangesAsync(cancellationToken);

            logger.LogInformation(
                "Saved group and assignment {AssignmentId} for appraisal {AppraisalId}",
                assignment.Id, appraisal.Id);

            // Phase 3: Create fee shell + appointment (both FK to assignment, which now exists in DB)
            // The shell captures the 4 fee-context fields from the request.
            // Fee items (the calculated amount) are added later by IAssignmentFeeService
            // when the real assignee is known (internal/external/quotation event handler).
            if (fee is not null)
            {
                var appraisalFee = AppraisalFee.Create(
                    assignmentId: assignment.Id,
                    feePaymentType: fee.FeePaymentType,
                    feeNotes: fee.FeeNotes,
                    totalSellingPrice: fee.TotalSellingPrice);
                if (fee.AbsorbedAmount is > 0m)
                    appraisalFee.SetBankAbsorb(fee.AbsorbedAmount.Value);
                dbContext.AppraisalFees.Add(appraisalFee);

                logger.LogInformation(
                    "Appraisal fee created: shell fee {FeeId} for assignment {AssignmentId} (TotalSellingPrice={TotalSellingPrice})",
                    appraisalFee.Id, assignment.Id, fee.TotalSellingPrice);
            }

            if (appointment?.AppointmentDateTime.HasValue == true)
            {
                var appt = Appointment.Create(
                    assignment.Id,
                    appointment.AppointmentDateTime.Value,
                    createdBy ?? "",
                    appointment.AppointmentLocation,
                    contact?.ContactPersonName,
                    contact?.ContactPersonPhone);

                dbContext.Appointments.Add(appt);

                logger.LogInformation("Created appointment {AppointmentId} for assignment {AssignmentId}",
                    appt.Id, assignment.Id);
            }

            // Commit — saves fee + appointment then commits the entire transaction
            await unitOfWork.CommitTransactionAsync(cancellationToken);
        }
        catch
        {
            await unitOfWork.RollbackTransactionAsync(cancellationToken);
            throw;
        }

        logger.LogInformation(
            "Successfully created appraisal {AppraisalId} ({AppraisalNumber}) with {PropertyCount} properties for request {RequestId}",
            appraisal.Id, appraisal.AppraisalNumber, appraisal.Properties.Count, requestId);

        return appraisal.Id;
    }

    // Maps new 33-code parameter table codes to the appraisal family they belong to.
    // Family codes mirror the old letter codes used internally in the Appraisal domain.
    private static readonly Dictionary<string, string> CodeToAppraisalFamily = new()
    {
        ["01"] = "L",   ["13"] = "L",   ["14"] = "L",   ["17"] = "L",
        ["19"] = "L",   ["21"] = "L",   ["26"] = "L",   ["27"] = "L",
        ["02"] = "LB",  ["03"] = "LB",  ["04"] = "LB",  ["23"] = "LB",
        ["24"] = "LB",  ["32"] = "LB",
        ["05"] = "B",   ["06"] = "B",   ["07"] = "B",   ["15"] = "B",
        ["16"] = "B",   ["18"] = "B",   ["20"] = "B",   ["22"] = "B",
        ["08"] = "U",   ["33"] = "U",
        ["09"] = "LS",  ["25"] = "LS",  ["30"] = "LS",  ["31"] = "LS",
        ["10"] = "VEH",
        ["11"] = "MAC",
        ["12"] = "VES",
        ["28"] = "LSU",
        ["29"] = "LSL",
    };

    // Codes that require Project aggregate initialization alongside the Appraisal
    private static readonly HashSet<string> ProjectCodes = ["32", "33"];

    private static string GetAppraisalFamily(RequestTitleDto t) =>
        CodeToAppraisalFamily.TryGetValue(t.CollateralType ?? "", out var family) ? family : "";

    private void CreateLandFamilyProperty(Domain.Appraisals.Appraisal appraisal, List<RequestTitleDto> titles)
    {
        // Promote to LB family if any LB-mapped code exists; otherwise plain L. All land titles merge into one LandDetail.
        var hasLandAndBuilding = titles.Any(t => GetAppraisalFamily(t) == "LB");
        var property = hasLandAndBuilding
            ? appraisal.AddLandAndBuildingProperty()
            : appraisal.AddLandProperty();

        logger.LogInformation(
            "Added {PropertyKind} property {PropertyId} grouping {TitleCount} title(s)",
            hasLandAndBuilding ? "land+building" : "land", property.Id, titles.Count);

        var landDetail = property.LandDetail;
        if (landDetail == null) return;

        // Primary title supplies property-level fields (project/owner/address); prefer an LB-family title if any.
        var primary = titles.FirstOrDefault(t => GetAppraisalFamily(t) == "LB") ?? titles.First();
        UpdateLandDetailTopFields(landDetail, primary);

        foreach (var t in titles) AddLandTitleFromRequest(landDetail, t);
    }

    private void CreateLeaseLandFamilyProperty(Domain.Appraisals.Appraisal appraisal, List<RequestTitleDto> titles)
    {
        // Promote to LS if any LS-mapped code exists; otherwise plain LSL. Mirrors the non-lease rule.
        var hasLandAndBuilding = titles.Any(t => GetAppraisalFamily(t) == "LS");
        var property = hasLandAndBuilding
            ? appraisal.AddLeaseAgreementLandAndBuildingProperty()
            : appraisal.AddLeaseAgreementLandProperty();

        logger.LogInformation(
            "Added lease-agreement {PropertyKind} property {PropertyId} grouping {TitleCount} title(s)",
            hasLandAndBuilding ? "land+building" : "land", property.Id, titles.Count);

        var landDetail = property.LandDetail;
        if (landDetail == null) return;

        var primary = titles.FirstOrDefault(t => GetAppraisalFamily(t) == "LS") ?? titles.First();
        UpdateLandDetailTopFields(landDetail, primary);

        foreach (var t in titles) AddLandTitleFromRequest(landDetail, t);
        // BuildingDetail / LeaseAgreementDetail / RentalInfo stay empty — populated later by appraiser
    }

    private void CreateCondoProperty(Domain.Appraisals.Appraisal appraisal, RequestTitleDto requestTitle)
    {
        var property = appraisal.AddCondoProperty();

        logger.LogInformation("Added condo property {PropertyId} for title {TitleNumber}",
            property.Id, requestTitle.TitleNumber);

        var condoDetail = property.CondoDetail;
        if (condoDetail == null) return;

        var adminAddress = AdministrativeAddress.Create(
            requestTitle.TitleAddress?.SubDistrict,
            requestTitle.TitleAddress?.District,
            requestTitle.TitleAddress?.Province);

        condoDetail.Update(
            propertyName: requestTitle.TitleAddress?.ProjectName,
            condoName: requestTitle.CondoName,
            buildingNumber: requestTitle.BuildingNumber,
            roomNumber: requestTitle.RoomNumber,
            floorNumber: requestTitle.FloorNumber,
            usableArea: requestTitle.UsableArea,
            address: adminAddress,
            ownerName: requestTitle.OwnerName,
            street: requestTitle.TitleAddress?.Road,
            soi: requestTitle.TitleAddress?.Soi);
    }

    private void AddLandTitleFromRequest(LandAppraisalDetail landDetail, RequestTitleDto requestTitle)
    {
        var title = LandTitle.Create(
            landDetail.Id,
            requestTitle.TitleNumber ?? "N/A",
            requestTitle.TitleType ?? "Unknown");

        var landArea = LandArea.Create(
            requestTitle.AreaRai,
            requestTitle.AreaNgan,
            requestTitle.AreaSquareWa);

        title.Update(
            requestTitle.BookNumber,
            requestTitle.PageNumber,
            requestTitle.LandParcelNumber,
            requestTitle.SurveyNumber,
            requestTitle.MapSheetNumber,
            requestTitle.Rawang,
            requestTitle.AerialMapName,
            requestTitle.AerialMapNumber,
            landArea,
            null, null, null, null, null, null, null);

        landDetail.AddTitle(title);

        logger.LogInformation("Added land title {TitleDeedNumber} to land detail {LandDetailId}",
            title.TitleNumber, landDetail.Id);
    }

    private void UpdateLandDetailTopFields(LandAppraisalDetail landDetail, RequestTitleDto requestTitle)
    {
        var adminAddress = AdministrativeAddress.Create(
            requestTitle.TitleAddress?.SubDistrict,
            requestTitle.TitleAddress?.District,
            requestTitle.TitleAddress?.Province);

        landDetail.Update(
            requestTitle.TitleAddress?.ProjectName,
            address: adminAddress,
            ownerName: requestTitle.OwnerName,
            street: requestTitle.TitleAddress?.Road,
            soi: requestTitle.TitleAddress?.Soi,
            village: requestTitle.TitleAddress?.Moo,
            addressLocation: requestTitle.TitleAddress?.HouseNumber);
    }

    private void CreateVehicleProperty(Domain.Appraisals.Appraisal appraisal, RequestTitleDto requestTitle)
    {
        var property = appraisal.AddVehicleProperty();

        logger.LogInformation("Added vehicle property {PropertyId} for title {TitleNumber}",
            property.Id, requestTitle.TitleNumber);

        var vehicleDetail = property.VehicleDetail;
        if (vehicleDetail == null) return;

        vehicleDetail.Update(
            chassisNo: requestTitle.VIN,
            registrationNo: requestTitle.LicensePlateNumber,
            location: requestTitle.VehicleLocation,
            ownerName: requestTitle.OwnerName,
            vehiclePart: requestTitle.VehicleType);
    }

    private void CreateVesselProperty(Domain.Appraisals.Appraisal appraisal, RequestTitleDto requestTitle)
    {
        var property = appraisal.AddVesselProperty();

        logger.LogInformation("Added vessel property {PropertyId} for title {TitleNumber}",
            property.Id, requestTitle.TitleNumber);

        var vesselDetail = property.VesselDetail;
        if (vesselDetail == null) return;

        vesselDetail.Update(
            registrationNo: requestTitle.VesselRegistrationNumber,
            vesselType: requestTitle.VesselType,
            location: requestTitle.VesselLocation,
            ownerName: requestTitle.OwnerName,
            other: requestTitle.HIN is not null ? $"HIN={requestTitle.HIN}" : null);
    }

    private void CreateMachineryProperty(Domain.Appraisals.Appraisal appraisal, RequestTitleDto requestTitle)
    {
        var property = appraisal.AddMachineryProperty();

        logger.LogInformation("Added machinery property {PropertyId} for title {TitleNumber}",
            property.Id, requestTitle.TitleNumber);

        var machineryDetail = property.MachineryDetail;
        if (machineryDetail == null) return;

        var otherParts = new List<string>();
        otherParts.Add($"RegistrationStatus={requestTitle.RegistrationStatus}");
        if (requestTitle.InvoiceNumber is not null) otherParts.Add($"Invoice={requestTitle.InvoiceNumber}");
        if (requestTitle.InstallationStatus is not null) otherParts.Add($"InstallationStatus={requestTitle.InstallationStatus}");

        machineryDetail.Update(
            registrationNo: requestTitle.RegistrationNo,
            machineName: requestTitle.MachineType,
            quantity: requestTitle.NumberOfMachine,
            ownerName: requestTitle.OwnerName,
            other: string.Join("; ", otherParts));
    }

    /// <summary>
    /// Loads properties from the prior appraisal and deep-copies them into the new CI appraisal.
    /// Uses the same CopyFrom static factories as Appraisal.CopyProperty().
    /// ConstructionInspection detail is excluded — it starts empty for fresh CI tracking.
    /// </summary>
    private async Task CopyPropertiesFromPriorAppraisalAsync(
        Domain.Appraisals.Appraisal appraisal,
        Guid prevAppraisalId,
        CancellationToken cancellationToken)
    {
        var priorAppraisal = await dbContext.Appraisals
            .AsNoTracking()
            .AsSplitQuery()
            .Include(a => a.Properties)
                .ThenInclude(p => p.LandDetail)
                    .ThenInclude(l => l!.Titles)
            .Include(a => a.Properties)
                .ThenInclude(p => p.BuildingDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.CondoDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.VehicleDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.VesselDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.MachineryDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.LeaseAgreementDetail)
            .Include(a => a.Properties)
                .ThenInclude(p => p.RentalInfo)
            .Include(a => a.Properties)
                .ThenInclude(p => p.ConstructionInspection)
                    .ThenInclude(ci => ci!.WorkDetails)
            .FirstOrDefaultAsync(a => a.Id == prevAppraisalId, cancellationToken);

        if (priorAppraisal is null)
        {
            logger.LogWarning(
                "CI copy: prior appraisal {PrevAppraisalId} not found. Appraisal will have no properties.",
                prevAppraisalId);
            return;
        }

        foreach (var prior in priorAppraisal.Properties)
        {
            var pt = prior.PropertyType;
            AppraisalProperty? newProp = null;

            if (pt == PropertyType.Land)
            {
                newProp = appraisal.AddLandProperty();
                if (prior.LandDetail is not null)
                    newProp.SetLandDetail(LandAppraisalDetail.CopyFrom(prior.LandDetail, newProp.Id));
            }
            else if (pt == PropertyType.Building)
            {
                newProp = appraisal.AddBuildingProperty();
                if (prior.BuildingDetail is not null)
                    newProp.SetBuildingDetail(BuildingAppraisalDetail.CopyFrom(prior.BuildingDetail, newProp.Id));
            }
            else if (pt == PropertyType.LandAndBuilding)
            {
                newProp = appraisal.AddLandAndBuildingProperty();
                if (prior.LandDetail is not null && prior.BuildingDetail is not null)
                    newProp.SetLandAndBuildingDetails(
                        LandAppraisalDetail.CopyFrom(prior.LandDetail, newProp.Id),
                        BuildingAppraisalDetail.CopyFrom(prior.BuildingDetail, newProp.Id));
                else if (prior.LandDetail is not null)
                    newProp.SetLandDetail(LandAppraisalDetail.CopyFrom(prior.LandDetail, newProp.Id));
            }
            else if (pt == PropertyType.Condo)
            {
                newProp = appraisal.AddCondoProperty();
                if (prior.CondoDetail is not null)
                    newProp.SetCondoDetail(CondoAppraisalDetail.CopyFrom(prior.CondoDetail, newProp.Id));
            }
            else if (pt == PropertyType.Vehicle)
            {
                newProp = appraisal.AddVehicleProperty();
                if (prior.VehicleDetail is not null)
                    newProp.SetVehicleDetail(VehicleAppraisalDetail.CopyFrom(prior.VehicleDetail, newProp.Id));
            }
            else if (pt == PropertyType.Vessel)
            {
                newProp = appraisal.AddVesselProperty();
                if (prior.VesselDetail is not null)
                    newProp.SetVesselDetail(VesselAppraisalDetail.CopyFrom(prior.VesselDetail, newProp.Id));
            }
            else if (pt == PropertyType.Machinery)
            {
                newProp = appraisal.AddMachineryProperty();
                if (prior.MachineryDetail is not null)
                    newProp.SetMachineryDetail(MachineryAppraisalDetail.CopyFrom(prior.MachineryDetail, newProp.Id));
            }
            else if (pt == PropertyType.LeaseAgreementLand)
            {
                newProp = appraisal.AddLeaseAgreementLandProperty();
                if (prior.LandDetail is not null)
                    newProp.SetLandDetail(LandAppraisalDetail.CopyFrom(prior.LandDetail, newProp.Id));
                if (prior.LeaseAgreementDetail is not null)
                    newProp.SetLeaseAgreementDetail(LeaseAgreementDetail.CopyFrom(prior.LeaseAgreementDetail, newProp.Id));
                if (prior.RentalInfo is not null)
                    newProp.SetRentalInfo(RentalInfo.CopyFrom(prior.RentalInfo, newProp.Id));
            }
            else if (pt == PropertyType.LeaseAgreementBuilding)
            {
                newProp = appraisal.AddLeaseAgreementBuildingProperty();
                if (prior.BuildingDetail is not null)
                    newProp.SetBuildingDetail(BuildingAppraisalDetail.CopyFrom(prior.BuildingDetail, newProp.Id));
                if (prior.LeaseAgreementDetail is not null)
                    newProp.SetLeaseAgreementDetail(LeaseAgreementDetail.CopyFrom(prior.LeaseAgreementDetail, newProp.Id));
                if (prior.RentalInfo is not null)
                    newProp.SetRentalInfo(RentalInfo.CopyFrom(prior.RentalInfo, newProp.Id));
            }
            else if (pt == PropertyType.LeaseAgreementLandAndBuilding)
            {
                newProp = appraisal.AddLeaseAgreementLandAndBuildingProperty();
                if (prior.LandDetail is not null && prior.BuildingDetail is not null)
                    newProp.SetLandAndBuildingDetails(
                        LandAppraisalDetail.CopyFrom(prior.LandDetail, newProp.Id),
                        BuildingAppraisalDetail.CopyFrom(prior.BuildingDetail, newProp.Id));
                if (prior.LeaseAgreementDetail is not null)
                    newProp.SetLeaseAgreementDetail(LeaseAgreementDetail.CopyFrom(prior.LeaseAgreementDetail, newProp.Id));
                if (prior.RentalInfo is not null)
                    newProp.SetRentalInfo(RentalInfo.CopyFrom(prior.RentalInfo, newProp.Id));
            }
            else
            {
                logger.LogWarning(
                    "CI copy: skipping property {PropertyId} with unsupported type {PropertyType} from prior appraisal {PrevAppraisalId}",
                    prior.Id, pt.Code, prevAppraisalId);
                continue;
            }

            // Shift prior current progress → new previous progress; reset current for inspector to fill.
            if (prior.ConstructionInspection is not null)
                newProp.SetConstructionInspection(
                    ConstructionInspection.CopyForNextInspection(prior.ConstructionInspection, newProp.Id));

            logger.LogInformation(
                "CI copy: copied property {SourcePropertyId} ({PropertyType}) from prior appraisal {PrevAppraisalId}",
                prior.Id, pt.Code, prevAppraisalId);
        }
    }

}