version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=P@ssw0rd
    ports:
      - "5341:80"    # Web UI
      - "5342:5341"  # Ingestion port
    volumes:
      - seq_data:/data
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: cas-mq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: P@ssw0rd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    depends_on:
      - sqlserver
    command:
      start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: P@ssword
      KC_DB: mssql
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: P@ssw0rd
      KC_DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=CollateralAppraisal;encrypt=false
      KC_TRANSACTION_XA_ENABLED: false
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  sql_data:
  seq_data:
  rabbitmq_data:
