namespace Appraisal.Application.Features.BlockVillage.GetVillageProject;

public record GetVillageProjectResponse(
    Guid Id,
    Guid AppraisalId,
    string? ProjectName,
    string? ProjectDescription,
    string? Developer,
    DateTime? ProjectSaleLaunchDate,
    decimal? LandAreaRai,
    decimal? LandAreaNgan,
    decimal? LandAreaWa,
    int? UnitForSaleCount,
    int? NumberOfPhase,
    string? LandOffice,
    string? ProjectType,
    DateTime? LicenseExpirationDate,
    decimal? Latitude,
    decimal? Longitude,
    string? SubDistrict,
    string? District,
    string? Province,
    string? Postcode,
    string? LocationNumber,
    string? Road,
    string? Soi,
    List<string>? Utilities,
    string? UtilitiesOther,
    List<string>? Facilities,
    string? FacilitiesOther,
    string? Remark
);
