using Appraisal.Application.Features.BlockVillage.CreateVillageModel;

namespace Appraisal.Application.Features.BlockVillage.UpdateVillageModel;

[System.Diagnostics.CodeAnalysis.SuppressMessage("SonarQube", "S107:Methods should not have too many parameters")]
public record UpdateVillageModelCommand(
    Guid AppraisalId,
    Guid ModelId,
    string? ModelName = null,
    string? ModelDescription = null,
    int? NumberOfHouse = null,
    decimal? StartingPrice = null,
    decimal? UsableAreaMin = null,
    decimal? UsableAreaMax = null,
    decimal? StandardUsableArea = null,
    decimal? LandAreaRai = null,
    decimal? LandAreaNgan = null,
    decimal? LandAreaWa = null,
    decimal? StandardLandArea = null,
    string? FireInsuranceCondition = null,
    List<Guid>? ImageDocumentIds = null,
    string? BuildingType = null,
    string? BuildingTypeOther = null,
    decimal? NumberOfFloors = null,
    string? DecorationType = null,
    string? DecorationTypeOther = null,
    bool? IsEncroachingOthers = null,
    string? EncroachingOthersRemark = null,
    decimal? EncroachingOthersArea = null,
    string? BuildingMaterialType = null,
    string? BuildingStyleType = null,
    bool? IsResidential = null,
    int? BuildingAge = null,
    int? ConstructionYear = null,
    string? ResidentialRemark = null,
    string? ConstructionStyleType = null,
    string? ConstructionStyleRemark = null,
    List<string>? StructureType = null,
    string? StructureTypeOther = null,
    List<string>? RoofFrameType = null,
    string? RoofFrameTypeOther = null,
    List<string>? RoofType = null,
    string? RoofTypeOther = null,
    List<string>? CeilingType = null,
    string? CeilingTypeOther = null,
    List<string>? InteriorWallType = null,
    string? InteriorWallTypeOther = null,
    List<string>? ExteriorWallType = null,
    string? ExteriorWallTypeOther = null,
    List<string>? FenceType = null,
    string? FenceTypeOther = null,
    string? ConstructionType = null,
    string? ConstructionTypeOther = null,
    string? UtilizationType = null,
    string? UtilizationTypeOther = null,
    string? Remark = null,
    List<VillageModelAreaDetailDto>? AreaDetails = null,
    List<VillageModelSurfaceDto>? Surfaces = null,
    List<VillageModelDepreciationDetailDto>? DepreciationDetails = null
) : ICommand, ITransactionalCommand<IAppraisalUnitOfWork>;
