{
 "title": "CAS Provision",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CAS app routing match attempts total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "aspnetcore_routing_match_attempts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "filters": [
      { "id": "be9341b2", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Amount of logs per 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} [1m]))"
    }
   ]
  },
  {
   "title": "Log severity ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 1 | severity_number <= 4 [1m]))",
     "legendFormat": "Trace"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 5 | severity_number <= 8 [1m]))",
     "legendFormat": "Debug"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 9 | severity_number <= 12 [1m]))",
     "legendFormat": "Info"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 13 | severity_number <= 16 [1m]))",
     "legendFormat": "Warn"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 17 | severity_number <= 20 [1m]))",
     "legendFormat": "Error"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 21 | severity_number <= 24 [1m]))",
     "legendFormat": "Fatal"
    }
   ]
  },
  {
   "title": "Amount of logs (logarithmic scale)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} [1m]))",
     "legendFormat": "All logs"
    },
    {
     "direction": "backward",
     "expr": "count(rate({service_name=\"unknown_service:Api.exe\"} | severity_number >= 13 [1m]))",
     "legendFormat": "Warn, error, fatal logs"
    }
   ]
  },
  {
   "title": "Warn, error, fatal logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"unknown_service:Api.exe\"} | severity_number >= 13"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"unknown_service:Api.exe\"} |= ``"
    }
   ]
  }
 ]
}