# Start a workflow instance using the workflow definition
# This request starts a workflow instance based on the provided definition.

### Start Workflow Instance
// @timeout = 30000 m
POST {{baseUrl}}/api/workflows/instances/start
Content-Type: application/json

{
  "workflowDefinitionId": "6ce8e680-6f1d-42c9-b7cb-6d09357cee60",
  "instanceName": "Collateral Appraisal Workflow",
  "startedBy": "system",
  "initialVariables": {
    "test": "test"
  },
  "correlationId": "1"
}