@baseUrl = https://localhost:7111
@requestId = e65da0bb-2b24-4479-597e-08de2bf89d72
PATCH {{baseUrl}}/requests/{{requestId}}/titles
Host: localhost:7111
Content-Type: application/json

{
    "requestTitleDtos":
    [
        {
            "id": "66878d03-7329-4340-8efa-7769d0f14029",
            "collateralType": "Land",
            "collateralStatus": false,
            "titleNo": "DATA",
            "deedType": "NorSor3",
            "titleDetail": "DATA",
            "rawang": "DATA",
            "landNo": "DATA",
            "surveyNo": "DATA",
            "areaRai": 0,
            "areaNgan": 0,
            "areaSquareWa": 0,
            "ownerName": "DATA",
            "titleAddress":
            {
                "houseNo": "DATA",
                "projectName": "DATA",
                "moo": "DATA",
                "soi": "DATA",
                "road": "DATA",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "dopaAddress":
            {
                "houseNo": "DATA",
                "projectName": "DATA",
                "moo": "DATA",
                "soi": "DATA",
                "road": "DATA",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "notes": "",
            "requestTitleDocumentDtos":
            [
                {
                    "id": "fe9bd4ac-193d-42a4-b31f-c0616d64e02e",
                    "documentId": "c5f2d07a-9a9e-4b13-b9e2-0b8d0f5f1101",
                    "documentType": "Test",
                    "filename": "Test",
                    "prefix": "Test",
                    "set": 1,
                    "documentDescription": "Test",
                    "filePath": "Test",
                    "createdWorkstation": "Test",
                    "isRequired": false,
                    "uploadedBy": "Test",
                    "uploadedByName": "Test"
                },
                {
                    "id": "3fd566e2-1710-48b5-8d08-d1c70c34c799",
                    "documentId": "c5f2d07a-9a9e-4b13-b9e2-0b8d0f5f1102",
                    "documentType": "Test",
                    "filename": "Test",
                    "prefix": "Test",
                    "set": 1,
                    "documentDescription": "Test",
                    "filePath": "Test",
                    "createdWorkstation": "Test",
                    "isRequired": false,
                    "uploadedBy": "Test",
                    "uploadedByName": "Test"
                }
            ]
        }
    ]
}