@baseUrl = https://localhost:7111
@requestId = e65da0bb-2b24-4479-597e-08de2bf89d72
POST {{baseUrl}}/requests/{{requestId}}/titles
Host: localhost:7111
Content-Type: application/json

{
    "requestTitleDtos":
    [
        {
            "collateralType": "Machine",
            "collateralStatus": false,
            "registrationNumber": "Test",
            "machineStatus": "Test",
            "machineType": "Test",
            "installationStatus": "Test",
            "invoiceNumber": "Test",
            "numberOfMachine": 10,
            "titleAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "dopaAddress":
            {
                "houseNo": "Test",
                "projectName": "Test",
                "moo": "Test",
                "soi": "Test",
                "road": "00",
                "subDistrict": "00",
                "district": "00",
                "province": "00",
                "postcode": "00"
            },
            "notes": "Test",
            "requestTitleDocumentDtos":
            [
            ]
        }
    ]
}