<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>CasSecretTool</RootNamespace>
        <AssemblyName>CasSecretTool</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Shared/Shared/Shared.csproj"/>
    </ItemGroup>

</Project>
