namespace Appraisal.Domain.Appraisals;

/// <summary>
/// Admin data-correction payload for one <see cref="AppraisalProperty"/> on a Completed appraisal.
///
/// Every member is nullable and follows one rule: <b>null means "leave unchanged"</b>. An empty
/// string clears a string field; an empty list clears a multi-select. See
/// <see cref="CorrectionDiff"/>.
///
/// Scope: every field the appraiser can author on the property detail screens is correctable here.
/// Members mirror the detail value objects one-for-one, with the immutable value objects
/// (Address, GpsCoordinate, LandArea) flattened into their components so a caller can correct a
/// single part without resending the whole object.
///
/// GENERATED SHAPE — when a detail VO gains or loses a property, this file and the matching
/// ApplyCorrection method must change with it. `correctableFields.test.ts` on the frontend fails
/// when the two sides drift.
/// </summary>
public sealed record PropertyCorrectionData(
    string? Description,
    LandCorrection? Land,
    IReadOnlyList<LandTitleCorrection>? LandTitles,
    BuildingCorrection? Building,
    CondoCorrection? Condo,
    VehicleCorrection? Vehicle,
    VesselCorrection? Vessel,
    MachineryCorrection? Machinery,
    LeaseAgreementCorrection? LeaseAgreement);

/// <summary>
/// Land detail. Latitude/Longitude and the two address triples are flattened from their value objects.
/// </summary>
public sealed record LandCorrection(
    string? PropertyName = null,
    string? LandDescription = null,
    decimal? Latitude = null,
    decimal? Longitude = null,
    string? SubDistrict = null,
    string? District = null,
    string? Province = null,
    string? LandOffice = null,
    string? DopaSubDistrict = null,
    string? DopaDistrict = null,
    string? DopaProvince = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    string? HasObligation = null,
    string? ObligationDetails = null,
    bool? IsLandLocationVerified = null,
    string? LandCheckMethodType = null,
    string? LandCheckMethodTypeOther = null,
    string? Street = null,
    string? Soi = null,
    decimal? DistanceFromMainRoad = null,
    string? Village = null,
    string? AddressLocation = null,
    string? LandShapeType = null,
    string? LandShapeTypeOther = null,
    string? UrbanPlanningType = null,
    IReadOnlyList<string>? LandZoneType = null,
    string? LandZoneTypeOther = null,
    IReadOnlyList<string>? PlotLocationType = null,
    string? PlotLocationTypeOther = null,
    string? LandFillType = null,
    string? LandFillTypeOther = null,
    decimal? LandFillPercent = null,
    decimal? SoilLevel = null,
    decimal? AccessRoadWidth = null,
    short? RightOfWay = null,
    decimal? RoadFrontage = null,
    int? NumberOfSidesFacingRoad = null,
    string? RoadPassInFrontOfLand = null,
    string? LandAccessibilityType = null,
    string? LandAccessibilityRemark = null,
    string? RoadSurfaceType = null,
    string? RoadSurfaceTypeOther = null,
    bool? HasElectricity = null,
    decimal? ElectricityDistance = null,
    IReadOnlyList<string>? PublicUtilityType = null,
    string? PublicUtilityTypeOther = null,
    IReadOnlyList<string>? LandUseType = null,
    string? LandUseTypeOther = null,
    IReadOnlyList<string>? LandEntranceExitType = null,
    string? LandEntranceExitTypeOther = null,
    IReadOnlyList<string>? TransportationAccessType = null,
    string? TransportationAccessTypeOther = null,
    string? PropertyAnticipationType = null,
    string? PropertyAnticipationTypeOther = null,
    bool? IsExpropriated = null,
    string? ExpropriationRemark = null,
    bool? IsInExpropriationLine = null,
    string? ExpropriationLineRemark = null,
    string? RoyalDecree = null,
    bool? IsEncroached = null,
    string? EncroachmentRemark = null,
    decimal? EncroachmentArea = null,
    bool? IsLandlocked = null,
    string? LandlockedRemark = null,
    bool? IsForestBoundary = null,
    string? ForestBoundaryRemark = null,
    string? OtherLegalLimitations = null,
    IReadOnlyList<string>? EvictionType = null,
    string? EvictionTypeOther = null,
    string? AllocationType = null,
    string? NorthAdjacentArea = null,
    decimal? NorthBoundaryLength = null,
    string? SouthAdjacentArea = null,
    decimal? SouthBoundaryLength = null,
    string? EastAdjacentArea = null,
    decimal? EastBoundaryLength = null,
    string? WestAdjacentArea = null,
    decimal? WestBoundaryLength = null,
    decimal? PondArea = null,
    decimal? PondDepth = null,
    bool? HasBuilding = null,
    string? HasBuildingOther = null,
    string? Remark = null,
    bool? IsRentedOut = null);

/// <summary>
/// One land title (plot). <c>TitleId</c> identifies the existing row and is required — titles are corrected in place, never removed and re-added, because the audit trail references their ids. Area is flattened into Rai/Ngan/SquareWa.
/// </summary>
public sealed record LandTitleCorrection(
    Guid TitleId,
    string? TitleNumber = null,
    string? TitleType = null,
    string? BookNumber = null,
    string? PageNumber = null,
    string? LandParcelNumber = null,
    string? SurveyNumber = null,
    string? MapSheetNumber = null,
    string? Rawang = null,
    string? AerialMapName = null,
    string? AerialMapNumber = null,
    string? BoundaryMarkerType = null,
    string? BoundaryMarkerRemark = null,
    string? DocumentValidationResultType = null,
    bool? IsMissingFromSurvey = null,
    decimal? GovernmentPricePerSqWa = null,
    decimal? GovernmentPrice = null,
    string? Remark = null);

/// <summary>
/// Building detail.
/// </summary>
public sealed record BuildingCorrection(
    string? PropertyName = null,
    string? BuildingNumber = null,
    string? ModelName = null,
    string? BuiltOnTitleNumber = null,
    string? HouseNumber = null,
    string? NoHouseNumber = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    string? HasObligation = null,
    string? ObligationDetails = null,
    string? BuildingConditionType = null,
    string? BuildingConditionTypeOther = null,
    bool? IsUnderConstruction = null,
    DateTime? ConstructionLicenseExpirationDate = null,
    bool? IsAppraisable = null,
    string? BuildingType = null,
    string? BuildingTypeOther = null,
    decimal? NumberOfFloors = null,
    string? DecorationType = null,
    string? DecorationTypeOther = null,
    bool? IsEncroachingOthers = null,
    string? EncroachingOthersRemark = null,
    decimal? EncroachingOthersArea = null,
    string? BuildingMaterialType = null,
    string? BuildingStyleType = null,
    string? BuildingStyleTypeOther = null,
    bool? IsResidential = null,
    int? BuildingAge = null,
    int? ConstructionYear = null,
    string? ResidentialRemark = null,
    string? ConstructionStyleType = null,
    string? ConstructionStyleRemark = null,
    IReadOnlyList<string>? StructureType = null,
    string? StructureTypeOther = null,
    IReadOnlyList<string>? RoofFrameType = null,
    string? RoofFrameTypeOther = null,
    IReadOnlyList<string>? RoofType = null,
    string? RoofTypeOther = null,
    IReadOnlyList<string>? CeilingType = null,
    string? CeilingTypeOther = null,
    IReadOnlyList<string>? InteriorWallType = null,
    string? InteriorWallTypeOther = null,
    IReadOnlyList<string>? ExteriorWallType = null,
    string? ExteriorWallTypeOther = null,
    IReadOnlyList<string>? FenceType = null,
    string? FenceTypeOther = null,
    string? ConstructionType = null,
    string? ConstructionTypeOther = null,
    string? UtilizationType = null,
    string? UtilizationTypeOther = null,
    decimal? BuildingInsurancePrice = null,
    decimal? SellingPrice = null,
    decimal? ForcedSalePrice = null,
    string? Remark = null);

/// <summary>
/// Condominium unit detail. Coordinates and the two address triples are flattened.
/// </summary>
public sealed record CondoCorrection(
    string? PropertyName = null,
    string? CondoName = null,
    string? BuildingNumber = null,
    string? ModelName = null,
    string? BuiltOnTitleNumber = null,
    string? CondoRegistrationNumber = null,
    string? RoomNumber = null,
    string? FloorNumber = null,
    int? PhysicalFloorNumber = null,
    bool? IsUnderConstruction = null,
    string? TitleNumber = null,
    string? TitleType = null,
    decimal? Latitude = null,
    decimal? Longitude = null,
    string? SubDistrict = null,
    string? District = null,
    string? Province = null,
    string? LandOffice = null,
    string? DopaSubDistrict = null,
    string? DopaDistrict = null,
    string? DopaProvince = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    string? BuildingConditionType = null,
    string? BuildingConditionTypeOther = null,
    string? HasObligation = null,
    string? ObligationDetails = null,
    string? DocumentValidationResultType = null,
    string? LocationType = null,
    string? Street = null,
    string? Soi = null,
    decimal? DistanceFromMainRoad = null,
    decimal? AccessRoadWidth = null,
    short? RightOfWay = null,
    string? RoadSurfaceType = null,
    string? RoadSurfaceTypeOther = null,
    IReadOnlyList<string>? PublicUtilityType = null,
    string? PublicUtilityTypeOther = null,
    IReadOnlyList<string>? LandEntranceExitType = null,
    string? LandEntranceExitTypeOther = null,
    string? LandFillType = null,
    string? LandFillTypeOther = null,
    string? UrbanPlanningType = null,
    IReadOnlyList<string>? LandUseType = null,
    string? LandUseTypeOther = null,
    string? DecorationType = null,
    string? DecorationTypeOther = null,
    int? BuildingAge = null,
    int? ConstructionYear = null,
    decimal? NumberOfFloors = null,
    string? BuildingFormType = null,
    string? ConstructionMaterialType = null,
    string? RoomLayoutType = null,
    string? RoomLayoutTypeOther = null,
    IReadOnlyList<string>? LocationViewType = null,
    string? LocationViewTypeOther = null,
    string? GroundFloorMaterialType = null,
    string? GroundFloorMaterialTypeOther = null,
    string? UpperFloorMaterialType = null,
    string? UpperFloorMaterialTypeOther = null,
    string? BathroomFloorMaterialType = null,
    string? BathroomFloorMaterialTypeOther = null,
    IReadOnlyList<string>? RoofType = null,
    string? RoofTypeOther = null,
    bool? IsExpropriated = null,
    string? ExpropriationRemark = null,
    bool? IsInExpropriationLine = null,
    string? ExpropriationLineRemark = null,
    string? RoyalDecree = null,
    bool? IsForestBoundary = null,
    string? ForestBoundaryRemark = null,
    IReadOnlyList<string>? FacilityType = null,
    string? FacilityTypeOther = null,
    IReadOnlyList<string>? EnvironmentType = null,
    string? EnvironmentTypeOther = null,
    bool? IsMissingFromSurvey = null,
    decimal? GovernmentPricePerSqm = null,
    decimal? GovernmentPrice = null,
    string? FireInsuranceCondition = null,
    decimal? BuildingInsurancePrice = null,
    decimal? SellingPrice = null,
    decimal? ForcedSalePrice = null,
    string? Remark = null);

/// <summary>
/// Vehicle detail.
/// </summary>
public sealed record VehicleCorrection(
    string? PropertyName = null,
    string? VehicleName = null,
    string? EngineNo = null,
    string? ChassisNo = null,
    string? RegistrationNumber = null,
    string? Brand = null,
    string? Model = null,
    int? YearOfManufacture = null,
    string? CountryOfManufacture = null,
    DateTime? PurchaseDate = null,
    decimal? PurchasePrice = null,
    string? Capacity = null,
    decimal? Width = null,
    decimal? Length = null,
    decimal? Height = null,
    string? EnergyUse = null,
    string? EnergyUseRemark = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    bool? CanUse = null,
    string? Location = null,
    string? ConditionUse = null,
    string? VehicleCondition = null,
    int? VehicleAge = null,
    string? VehicleEfficiency = null,
    string? VehicleTechnology = null,
    string? UsePurpose = null,
    string? VehiclePart = null,
    string? Remark = null,
    string? Other = null,
    string? AppraiserOpinion = null);

/// <summary>
/// Vessel detail.
/// </summary>
public sealed record VesselCorrection(
    string? PropertyName = null,
    string? VesselName = null,
    string? EngineNo = null,
    string? RegistrationNumber = null,
    DateTime? RegistrationDate = null,
    string? Brand = null,
    string? Model = null,
    int? YearOfManufacture = null,
    string? PlaceOfManufacture = null,
    string? VesselType = null,
    string? ClassOfVessel = null,
    DateTime? PurchaseDate = null,
    decimal? PurchasePrice = null,
    string? EngineCapacity = null,
    decimal? Width = null,
    decimal? Length = null,
    decimal? Height = null,
    decimal? GrossTonnage = null,
    decimal? NetTonnage = null,
    string? EnergyUse = null,
    string? EnergyUseRemark = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    bool? CanUse = null,
    string? FormerName = null,
    string? VesselCurrentName = null,
    string? Location = null,
    string? ConditionUse = null,
    string? VesselCondition = null,
    int? VesselAge = null,
    string? VesselEfficiency = null,
    string? VesselTechnology = null,
    string? UsePurpose = null,
    string? VesselPart = null,
    string? Remark = null,
    string? Other = null,
    string? AppraiserOpinion = null);

/// <summary>
/// Machinery detail.
/// </summary>
public sealed record MachineryCorrection(
    string? PropertyName = null,
    string? MachineName = null,
    string? EngineNo = null,
    string? ChassisNo = null,
    string? RegistrationNumber = null,
    string? SerialNo = null,
    bool? RegistrationStatus = null,
    string? InstallationStatus = null,
    string? MachineType = null,
    string? InvoiceNumber = null,
    bool? IsPriceCertified = null,
    string? Brand = null,
    string? Model = null,
    string? Series = null,
    int? YearOfManufacture = null,
    string? Manufacturer = null,
    DateTime? PurchaseDate = null,
    decimal? PurchasePrice = null,
    string? Capacity = null,
    int? Quantity = null,
    string? MachineDimensions = null,
    decimal? Width = null,
    decimal? Length = null,
    decimal? Height = null,
    string? EnergyUse = null,
    string? EnergyUseRemark = null,
    string? OwnerName = null,
    bool? IsOwnerVerified = null,
    bool? IsOperational = null,
    string? Location = null,
    string? ConditionUse = null,
    string? MachineCondition = null,
    decimal? MachineAge = null,
    string? MachineEfficiency = null,
    string? MachineTechnology = null,
    string? UsagePurpose = null,
    string? MachineParts = null,
    decimal? ReplacementValue = null,
    decimal? ConditionValue = null,
    string? Remark = null,
    string? Other = null,
    string? AppraiserOpinion = null);

/// <summary>
/// Lease agreement detail.
/// </summary>
public sealed record LeaseAgreementCorrection(
    string? LesseeName = null,
    string? LessorName = null,
    decimal? LeasePeriodAsContract = null,
    decimal? RemainingLeaseAsAppraisalDate = null,
    string? ContractNo = null,
    DateTime? LeaseStartDate = null,
    DateTime? LeaseEndDate = null,
    decimal? LeaseRentFee = null,
    decimal? RentAdjust = null,
    string? Sublease = null,
    decimal? AdditionalExpenses = null,
    string? LeaseTerminate = null,
    string? ContractRenewal = null,
    string? RentalTermsImpactingPropertyUse = null,
    string? TerminationOfLease = null,
    string? Remark = null);

/// <summary>
/// What a correction actually changed. <paramref name="ChangedFields"/> is the JSON diff written to
/// the audit trail — "{}" when nothing changed.
/// </summary>
public readonly record struct PropertyCorrectionOutcome(int ChangedFieldCount, string ChangedFields);
