@baseUrl = https://localhost:7111

@requestId = 6A5D06E6-4E76-4C18-48D8-08DE21BB6FAC

POST {{baseUrl}}/requests/{{requestId}}/comments
Host: localhost:7111
Content-Type: application/json

{
    "comment": "Hello World!",
    "commentedBy": "xxxxx1",
    "commentedByName": "John Doe"
}