@baseUrl = https://localhost:7111

@requestId = 6D884C99-1F73-4F6C-86A4-08DE227BF8AC

@commentId = 1EF61A52-B24E-40A6-A4A0-B78090E23272

GET {{baseUrl}}/requests/{{requestId}}/comments
Host: localhost:7111
Content-Type: application/json

{

}