namespace Request.Application.Features.RequestDocuments.GetRequestDocumentsByRequestId;

public record GetRequestDocumentsByRequestIdQuery(Guid RequestId) : IQuery<GetRequestDocumentsByRequestIdResult>;
