@baseUrl = https://localhost:7111
@requestId = 6D884C99-1F73-4F6C-86A4-08DE227BF8AC
POST {{baseUrl}}/requests/{{requestId}}/titles
Host: localhost:7111
Content-Type: application/json

{
	"collateralType": "V",
	"collateralStatus": false,
    "registrationNumber": "1212312121",
    "vehicleType": "Car",
    "vehicleAppointmentLocation": "Q House",
    "chassisNumber": "55555555",
	"titleAddress":
	{
		"houseNo": "",
        "projectName": "",
        "moo": "",
        "soi": "",
        "road": "123456789",
        "subDistrict": "16",
        "district": "00",
        "province": "50",
        "postcode": "50000"
	},
	"dopaAddress":
	{
		"houseNo": "",
        "projectName": "",
        "moo": "",
        "soi": "",
        "road": "",
        "subDistrict": "16",
        "district": "00",
        "province": "50",
        "postcode": "50000"
	},
	"notes": ""
}