// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reporting.Data;

#nullable disable

namespace Reporting.Data.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260607084357_AddReportJobsAndOutbox")]
    partial class AddReportJobsAndOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Data.ReportDefinition", b =>
                {
                    b.Property<string>("ReportTypeKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayNameTh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ReportTypeKey");

                    b.ToTable("ReportDefinitions", "reporting");

                    b.HasData(
                        new
                        {
                            ReportTypeKey = "appointment-quotation-request",
                            Category = "Appointment",
                            DisplayNameEn = "Appointment Quotation Request",
                            DisplayNameTh = "แบบฟอร์มนัดหมายและใบเสนอราคา",
                            GenerationMode = "Sync",
                            IsEnabled = true,
                            TemplateId = "appointment-quotation-request",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "appraisal-summary-land-building",
                            Category = "AppraisalSummary",
                            DisplayNameEn = "Appraisal Summary – Land and Building",
                            DisplayNameTh = "ใบสรุปรายงานการประเมิน – ที่ดินและสิ่งปลูกสร้าง",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "appraisal-summary-land-building",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "appraisal-summary-condo",
                            Category = "AppraisalSummary",
                            DisplayNameEn = "Appraisal Summary – Condominium",
                            DisplayNameTh = "ใบสรุปรายงานการประเมิน – ห้องชุด (Condo)",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "appraisal-summary-condo",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "appraisal-summary-machine",
                            Category = "AppraisalSummary",
                            DisplayNameEn = "Appraisal Summary – Machinery",
                            DisplayNameTh = "ใบสรุปรายงานการประเมิน – เครื่องจักร",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "appraisal-summary-machine",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "appraisal-summary-construction",
                            Category = "AppraisalSummary",
                            DisplayNameEn = "Appraisal Summary – Construction Inspection",
                            DisplayNameTh = "สรุปรายงานการตรวจงานก่อสร้าง",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "appraisal-summary-construction",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "appraisal-summary-block",
                            Category = "AppraisalSummary",
                            DisplayNameEn = "Appraisal Summary – Block Project",
                            DisplayNameTh = "ใบสรุปรายงานการประเมิน – โครงการ (Block)",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "appraisal-summary-block",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "external-appraisal-report",
                            Category = "ExternalReport",
                            DisplayNameEn = "External Appraisal Report",
                            DisplayNameTh = "รายงานการประเมินราคา (บริษัทภายนอก)",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "external-appraisal-report",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "internal-report-construction",
                            Category = "InternalReport",
                            DisplayNameEn = "Internal Construction Inspection Report",
                            DisplayNameTh = "รายงานตรวจงานก่อสร้าง (ภายใน)",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "internal-report-construction",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "internal-report-block",
                            Category = "InternalReport",
                            DisplayNameEn = "Internal Block Project Report",
                            DisplayNameTh = "รายงานโครงการ (ภายใน)",
                            GenerationMode = "Async",
                            IsEnabled = true,
                            TemplateId = "internal-report-block",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "meeting-invitation",
                            Category = "Meeting",
                            DisplayNameEn = "Meeting Invitation",
                            DisplayNameTh = "หนังสือเชิญประชุม",
                            GenerationMode = "Sync",
                            IsEnabled = true,
                            TemplateId = "meeting-invitation",
                            Version = 1
                        },
                        new
                        {
                            ReportTypeKey = "meeting-minute",
                            Category = "Meeting",
                            DisplayNameEn = "Meeting Minute",
                            DisplayNameTh = "รายงานการประชุม",
                            GenerationMode = "Sync",
                            IsEnabled = true,
                            TemplateId = "meeting-minute",
                            Version = 1
                        });
                });

            modelBuilder.Entity("Reporting.Data.ReportGenerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("ReportName");

                    b.ToTable("ReportGenerationLogs", "reporting");
                });

            modelBuilder.Entity("Reporting.Data.ReportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportTypeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedBy");

                    b.ToTable("ReportJobs", "reporting");
                });

            modelBuilder.Entity("Shared.Data.Lease.BackgroundServiceLease", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LeasedUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BackgroundServiceLease", "reporting");
                });

            modelBuilder.Entity("Shared.Data.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerType")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MessageId", "ConsumerType");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_InboxMessage_Cleanup");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("IX_InboxMessage_StaleProcessing");

                    b.ToTable("InboxMessage", "reporting");
                });

            modelBuilder.Entity("Shared.Data.Outbox.IntegrationEventOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Polling");

                    b.HasIndex("Status", "ProcessedAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Cleanup");

                    b.HasIndex("Status", "RetryCount")
                        .HasDatabaseName("IX_IntegrationEventOutbox_DeadLetter");

                    b.HasIndex("CorrelationId", "Status", "OccurredAt")
                        .HasDatabaseName("IX_IntegrationEventOutbox_Correlation");

                    b.ToTable("IntegrationEventOutbox", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
