// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Request.Data;

#nullable disable

namespace Request.Data.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20251125085445_DataTypeRequestdoc")]
    partial class DataTypeRequestdoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("request")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Request.RequestComments.Models.RequestComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestComments", "request");
                });

            modelBuilder.Entity("Request.RequestDocuments.Models.RequestDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("DocumentDescription");

                    b.Property<bool>("DocumentFollowUp")
                        .HasColumnType("bit")
                        .HasColumnName("DocumentFollowUp");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FilePath");

                    b.Property<string>("Prefix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prefix");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short?>("Set")
                        .HasColumnType("smallint")
                        .HasColumnName("Set");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDocuments", "request");
                });

            modelBuilder.Entity("Request.RequestTitles.Models.RequestTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BuildingType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfBuilding")
                        .HasColumnType("int");

                    b.Property<string>("Owner")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleDetail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UsageArea")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.ToTable("RequestTitles", "request");
                });

            modelBuilder.Entity("Request.Requests.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPMA")
                        .HasColumnType("bit")
                        .HasColumnName("IsPMA");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Priority");

                    b.Property<string>("Purpose")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Purpose");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Requests", "request");
                });

            modelBuilder.Entity("Request.RequestDocuments.Models.RequestDocument", b =>
                {
                    b.HasOne("Request.Requests.Models.Request", null)
                        .WithMany("Documents")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Request.RequestDocuments.ValueObjects.DocumentClassification", "DocumentClassification", b1 =>
                        {
                            b1.Property<Guid>("RequestDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DocumentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DocumentType");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit")
                                .HasColumnName("IsRequire");

                            b1.HasKey("RequestDocumentId");

                            b1.ToTable("RequestDocuments", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestDocumentId");
                        });

                    b.OwnsOne("Request.RequestDocuments.ValueObjects.UploadInfo", "UploadInfo", b1 =>
                        {
                            b1.Property<Guid>("RequestDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("UploadedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("UploadedAt");

                            b1.Property<long?>("UploadedBy")
                                .HasColumnType("bigint")
                                .HasColumnName("UploadedBy");

                            b1.Property<string>("UploadedByName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("UploadedByName");

                            b1.HasKey("RequestDocumentId");

                            b1.ToTable("RequestDocuments", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestDocumentId");
                        });

                    b.Navigation("DocumentClassification")
                        .IsRequired();

                    b.Navigation("UploadInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.RequestTitles.Models.RequestTitle", b =>
                {
                    b.OwnsOne("Request.Requests.ValueObjects.Address", "DopaAddress", b1 =>
                        {
                            b1.Property<long>("RequestTitleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("BuildingNo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaBuildingNo");

                            b1.Property<string>("District")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaDistrict");

                            b1.Property<string>("FloorNo")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaFloorNo");

                            b1.Property<string>("HouseNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("DopaHouseNo");

                            b1.Property<string>("Moo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaMoo");

                            b1.Property<string>("Postcode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaPostcode");

                            b1.Property<string>("Province")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaProvince");

                            b1.Property<string>("Road")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaRoad");

                            b1.Property<string>("RoomNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("DopaRoomNo");

                            b1.Property<string>("Soi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("DopaSoi");

                            b1.Property<string>("SubDistrict")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("DopaSubDistrict");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.Address", "TitleAddress", b1 =>
                        {
                            b1.Property<long>("RequestTitleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("BuildingNo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("BuildingNo");

                            b1.Property<string>("District")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("District");

                            b1.Property<string>("FloorNo")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("FloorNo");

                            b1.Property<string>("HouseNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("HouseNo");

                            b1.Property<string>("Moo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Moo");

                            b1.Property<string>("Postcode")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Postcode");

                            b1.Property<string>("Province")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Province");

                            b1.Property<string>("Road")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Road");

                            b1.Property<string>("RoomNo")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("RoomNo");

                            b1.Property<string>("Soi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Soi");

                            b1.Property<string>("SubDistrict")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("SubDistrict");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsOne("Request.RequestTitles.ValueObjects.LandArea", "LandArea", b1 =>
                        {
                            b1.Property<long>("RequestTitleId")
                                .HasColumnType("bigint");

                            b1.Property<int?>("Ngan")
                                .HasColumnType("int")
                                .HasColumnName("Ngan");

                            b1.Property<int?>("Rai")
                                .HasColumnType("int")
                                .HasColumnName("Rai");

                            b1.Property<decimal?>("Wa")
                                .HasPrecision(4, 2)
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("Wa");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsOne("Request.RequestTitles.ValueObjects.Machine", "Machine", b1 =>
                        {
                            b1.Property<long>("RequestTitleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("MachineInvoiceNo")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("MachineInvoiceNo");

                            b1.Property<string>("MachineRegistrationNo")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("MachineRegistrationNo");

                            b1.Property<string>("MachineRegistrationStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MachineRegistrationStatus");

                            b1.Property<string>("MachineStatus")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MachineStatus");

                            b1.Property<string>("MachineType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("MachineType");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.OwnsOne("Request.RequestTitles.ValueObjects.Vehicle", "Vehicle", b1 =>
                        {
                            b1.Property<long>("RequestTitleId")
                                .HasColumnType("bigint");

                            b1.Property<string>("VehicleLocation")
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("VehicleLocation");

                            b1.Property<string>("VehicleRegistrationNo")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("VehicleRegistrationNo");

                            b1.Property<string>("VehicleType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("VehicleType");

                            b1.HasKey("RequestTitleId");

                            b1.ToTable("RequestTitles", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestTitleId");
                        });

                    b.Navigation("DopaAddress")
                        .IsRequired();

                    b.Navigation("LandArea")
                        .IsRequired();

                    b.Navigation("Machine")
                        .IsRequired();

                    b.Navigation("TitleAddress")
                        .IsRequired();

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Requests.Models.Request", b =>
                {
                    b.OwnsOne("Request.Requests.ValueObjects.AppraisalNumber", "AppraisalNo", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("RequestNumber");

                            b1.HasKey("RequestId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Request_RequestNumber");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsMany("Request.Requests.ValueObjects.RequestCustomer", "Customers", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("ContactNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContactNumber");

                            b1.Property<string>("Name")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("CustomerName");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("Name")
                                .HasDatabaseName("IX_RequestCustomer_Name");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestCustomers", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.RequestDetail", "Detail", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("HasAppraisalBook")
                                .HasColumnType("bit")
                                .HasColumnName("HasAppraisalBook");

                            b1.Property<long?>("PrevAppraisalNo")
                                .HasMaxLength(10)
                                .HasColumnType("bigint")
                                .HasColumnName("PrevAppraisalNo");

                            b1.HasKey("RequestId");

                            b1.ToTable("RequestDetails", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");

                            b1.OwnsOne("Request.Requests.ValueObjects.Appointment", "Appointment", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime?>("AppointmentDateTime")
                                        .HasColumnType("datetime2")
                                        .HasColumnName("AppointmentDateTime");

                                    b2.Property<string>("AppointmentLocation")
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("AppointmentLocation");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Contact", "Contact", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContactPersonName")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("ContactPersonName");

                                    b2.Property<string>("ContactPersonPhone")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("ContactPersonPhone");

                                    b2.Property<string>("ProjectCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("ProjectCode");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Fee", "Fee", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal?>("BankAbsorbAmt")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("BankAbsorbAmount");

                                    b2.Property<string>("FeeNotes")
                                        .HasMaxLength(4000)
                                        .HasColumnType("nvarchar(4000)")
                                        .HasColumnName("FeeRemark");

                                    b2.Property<string>("FeeType")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("FeeType");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.LoanDetail", "LoanDetail", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal?>("AdditionalFacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("AdditionalFacilityLimit");

                                    b2.Property<string>("BankingSegment")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("BankingSegment");

                                    b2.Property<decimal?>("FacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("FacilityLimit");

                                    b2.Property<string>("LoanApplicationNo")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("LoanApplicationNo");

                                    b2.Property<decimal?>("PreviousFacilityLimit")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("PreviousFacilityLimit");

                                    b2.Property<decimal?>("TotalSellingPrice")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("decimal(19,4)")
                                        .HasColumnName("TotalSellingPrice");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.HasIndex("LoanApplicationNo")
                                        .HasDatabaseName("IX_Request_LoanApplicationNumber")
                                        .HasFilter("[LoanApplicationNo] IS NOT NULL");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.OwnsOne("Request.Requests.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("RequestDetailRequestId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("District")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("District");

                                    b2.Property<string>("FloorNo")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("FloorNo");

                                    b2.Property<string>("HouseNo")
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("HouseNo");

                                    b2.Property<string>("Moo")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Moo");

                                    b2.Property<string>("Postcode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Postcode");

                                    b2.Property<string>("ProjectName")
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("LocationIdentifier");

                                    b2.Property<string>("Province")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("Province");

                                    b2.Property<string>("Road")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Road");

                                    b2.Property<string>("RoomNo")
                                        .HasMaxLength(30)
                                        .HasColumnType("nvarchar(30)")
                                        .HasColumnName("RoomNo");

                                    b2.Property<string>("Soi")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Soi");

                                    b2.Property<string>("SubDistrict")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)")
                                        .HasColumnName("SubDistrict");

                                    b2.HasKey("RequestDetailRequestId");

                                    b2.ToTable("RequestDetails", "request");

                                    b2.WithOwner()
                                        .HasForeignKey("RequestDetailRequestId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Appointment")
                                .IsRequired();

                            b1.Navigation("Contact")
                                .IsRequired();

                            b1.Navigation("Fee")
                                .IsRequired();

                            b1.Navigation("LoanDetail")
                                .IsRequired();
                        });

                    b.OwnsMany("Request.Requests.ValueObjects.RequestProperty", "Properties", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("BuildingType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("BuildingType");

                            b1.Property<string>("PropertyType")
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("PropertyType");

                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("SellingPrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("SellingPrice");

                            b1.HasKey("Id");

                            b1.HasIndex("PropertyType")
                                .HasDatabaseName("IX_RequestProperty_PropertyType");

                            b1.HasIndex("RequestId");

                            b1.ToTable("RequestProperties", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.RequestStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("Status");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("CompletedAt");

                            b1.Property<DateTime?>("SubmittedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("SubmittedAt");

                            b1.HasKey("RequestId");

                            b1.HasIndex("Code")
                                .HasDatabaseName("IX_Request_Status")
                                .HasFilter("[IsDeleted] = 0");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.SoftDelete", "SoftDelete", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DeletedBy")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DeletedBy");

                            b1.Property<DateTime?>("DeletedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedOn");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("bit")
                                .HasColumnName("IsDeleted");

                            b1.HasKey("RequestId");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.OwnsOne("Request.Requests.ValueObjects.SourceSystem", "SourceSystem", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Channel")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Channel");

                            b1.Property<DateTime?>("CreatedDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedDate");

                            b1.Property<string>("Creator")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Creator");

                            b1.Property<string>("CreatorName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CreatorName");

                            b1.Property<string>("RequestBy")
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("RequestBy");

                            b1.Property<string>("RequestByName")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("RequestByName");

                            b1.Property<DateTime?>("RequestDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("RequestDate");

                            b1.HasKey("RequestId");

                            b1.HasIndex("RequestBy")
                                .HasDatabaseName("IX_Request_RequestedBy")
                                .HasFilter("[IsDeleted] = 0");

                            b1.HasIndex("RequestDate")
                                .IsDescending()
                                .HasDatabaseName("IX_Request_RequestDate")
                                .HasFilter("[IsDeleted] = 0");

                            b1.ToTable("Requests", "request");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.Navigation("AppraisalNo")
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Detail")
                        .IsRequired();

                    b.Navigation("Properties");

                    b.Navigation("SoftDelete")
                        .IsRequired();

                    b.Navigation("SourceSystem")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("Request.Requests.Models.Request", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
