using Appraisal.Application.Features.Appraisals.CreateLandProperty;
using Appraisal.Domain.Appraisals;
using Appraisal.Infrastructure;
using Integration.Fixtures;
using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using AppraisalAggregate = Appraisal.Domain.Appraisals.Appraisal;

namespace Integration.Appraisal.Integration.Tests;

/// <summary>
/// Shared seed / send / reload helpers for the "every handler touched by the property-save change still
/// persists" tests. Every command goes through the real MediatR pipeline in its own scope and every
/// assertion reads from a FRESH scope, so only what was committed is visible.
/// </summary>
public abstract class AffectedHandlersBase(IntegrationTestFixture fixture)
{
    protected static CancellationToken Ct => TestContext.Current.CancellationToken;

    protected IServiceScope CreateScope()
        => fixture.IntegrationTestWebApplicationFactory.Services.CreateScope();

    protected static decimal RoundTo1000(decimal v) => Math.Round(v / 1000, MidpointRounding.AwayFromZero) * 1000;

    protected async Task<T> SendAsync<T>(IRequest<T> command)
    {
        using var scope = CreateScope();
        return await scope.ServiceProvider.GetRequiredService<ISender>().Send(command, Ct);
    }

    // ── seeding ─────────────────────────────────────────────────────────────────────────────

    protected static AppraisalAggregate NewAppraisal(bool pma = false)
    {
        var appraisal = AppraisalAggregate.Create(Guid.NewGuid(), "New", "Normal", DateTime.Now, isPma: pma);
        appraisal.SetAppraisalNumber($"QA-{Guid.NewGuid():N}"[..18]);
        return appraisal;
    }

    /// <summary>Saves an appraisal whose properties are built by <paramref name="build"/>.</summary>
    protected async Task<Guid> SeedAsync(Action<AppraisalAggregate> build, bool pma = false)
    {
        using var scope = CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppraisalDbContext>();
        var appraisal = NewAppraisal(pma);
        build(appraisal);
        db.Appraisals.Add(appraisal);
        await db.SaveChangesAsync(Ct);
        return appraisal.Id;
    }

    /// <summary>
    /// Saves an appraisal with properties from <paramref name="build"/> plus groups "G1".."Gn"; every
    /// property returned by <paramref name="build"/> is put in the FIRST group (groups: 0 = ungrouped). Ids are generated by the
    /// database, so group membership is added after the first save.
    /// </summary>
    protected async Task<(Guid AppraisalId, Guid[] GroupIds, Guid[] PropertyIds)> SeedGroupedAsync(
        Func<AppraisalAggregate, AppraisalProperty[]> build, int groups = 1, bool pma = false, bool placeInGroup = true)
    {
        using var scope = CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppraisalDbContext>();
        var appraisal = NewAppraisal(pma);
        var props = build(appraisal);
        var groupObjs = Enumerable.Range(1, groups).Select(i => appraisal.CreateGroup($"G{i}")).ToArray();
        db.Appraisals.Add(appraisal);
        await db.SaveChangesAsync(Ct);
        if (groupObjs.Length > 0 && placeInGroup)
        {
            foreach (var p in props) appraisal.AddPropertyToGroup(groupObjs[0].Id, p.Id);
            await db.SaveChangesAsync(Ct);
        }
        return (appraisal.Id, groupObjs.Select(g => g.Id).ToArray(), props.Select(p => p.Id).ToArray());
    }

    protected static LandTitle SeedTitle(LandAppraisalDetail land, string number, decimal rai)
    {
        var title = LandTitle.Create(land.Id, number, "DEED");
        title.Update(null, null, null, null, null, null, null, null, LandArea.Create(rai, 0m, 0m),
            null, null, null, null, null, null, null);
        title.SetSequenceNumber(land.Titles.Count + 1);
        land.AddTitle(title);
        return title;
    }

    protected static LandTitleItemData NewTitle(string number, decimal rai = 1m, Guid? id = null)
        => new(id, number, "DEED", Rai: rai, Ngan: 0m, SquareWa: 0m);

    // ── reload (fresh scope) ───────────────────────────────────────────────────────────────

    protected async Task<AppraisalAggregate> LoadAsync(Guid appraisalId)
    {
        using var scope = CreateScope();
        var appraisal = await scope.ServiceProvider.GetRequiredService<IAppraisalRepository>()
            .GetByIdWithPropertiesAsync(appraisalId, Ct);
        return appraisal ?? throw new InvalidOperationException($"Appraisal {appraisalId} not found after save");
    }

    protected async Task<AppraisalProperty> PropAsync(Guid appraisalId, Guid propertyId)
        => (await LoadAsync(appraisalId)).GetProperty(propertyId)
           ?? throw new InvalidOperationException($"Property {propertyId} not persisted");

    protected async Task<decimal?> InsuranceAsync(Guid appraisalId)
    {
        using var scope = CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppraisalDbContext>();
        var row = await db.ValuationAnalyses.AsNoTracking().FirstOrDefaultAsync(v => v.AppraisalId == appraisalId, Ct);
        Assert.NotNull(row);
        return row.InsuranceValue;
    }

    protected static void AssertInGroup(AppraisalAggregate appraisal, Guid groupId, Guid propertyId, int? position = null)
    {
        var group = Assert.Single(appraisal.Groups, g => g.Id == groupId);
        var item = Assert.Single(group.Items, i => i.AppraisalPropertyId == propertyId);
        if (position.HasValue) Assert.Equal(position.Value, item.SequenceInGroup);
    }
}
