namespace Appraisal.Application.Features.DecisionSummary.GetDecisionSummary;

public record GetDecisionSummaryResponse(
    IReadOnlyList<ApproachMatrixGroup> ApproachMatrix,
    decimal TotalAppraisalPrice,
    decimal ForceSellingPrice,
    // RESOLVED rate (e.g. 70.00 = 70%) — never null. DISPLAY-only; see ForceSellingRateOverride
    // for the value a save should round-trip.
    decimal ForceSellingRate,
    // RAW per-appraisal override, or null when using the resolved default/project rate.
    decimal? ForceSellingRateOverride,
    decimal BuildingInsurance,
    IReadOnlyList<GovernmentPriceRow> GovernmentPrices,
    decimal GovernmentPriceTotalArea,
    decimal GovernmentPriceSurveyedArea,
    decimal GovernmentPriceAvgPerSqWa,
    IReadOnlyList<CondoGovernmentPriceRow> CondoGovernmentPrices,
    decimal CondoGovernmentPriceTotalArea,
    decimal CondoGovernmentPriceAvgPerSqm,
    decimal? TotalAppraisalPriceReview,
    decimal? ForceSellingPriceReview,
    decimal BuildingInsuranceReview,
    string? CommitteeName,
    string? ReviewStatus,
    Guid? ReviewId,
    IReadOnlyList<DecisionApprovalListItem>? ApprovalList,
    Guid? DecisionId,
    bool? IsPriceVerified,
    string? ConditionType,
    string? Condition,
    string? RemarkType,
    string? Remark,
    string? ExternalAppraiserOpinionType,
    string? ExternalAppraiserOpinion,
    string? CommitteeOpinionType,
    string? CommitteeOpinion,
    string? InternalAppraiserOpinionType,
    string? InternalAppraiserOpinion,
    string? AdditionalAssumptions,
    bool IsBlock,
    IReadOnlyList<BlockApproachMatrixRow>? BlockApproachMatrix,
    IReadOnlyList<BlockModelPriceRow>? BlockModelPrices,
    ConstructionSummaryData? ConstructionSummary,
    DateTime? AppraisalDate
);
