@baseUrl = https://localhost:7111
@requestId = 9d14684e-608d-4f13-6b2b-08de2a635ee2
PATCH {{baseUrl}}/requests/{{requestId}}/titles
Host: localhost:7111
Content-Type: application/json

{
    "requestTitleDtos":
    [
        {
            "id": "748db05a-35ad-42f2-bdf7-9e9f18bb8ca2",
            "collateralType": "Land",
            "collateralStatus": false,
            "titleNo": "1212312121",
            "deedType": "NorSor3",
            "titleDetail": "",
            "rawang": "xxxx",
            "landNo": "xxxx",
            "surveyNo": "xxxx",
            "areaRai": 0,
            "areaNgan": 0,
            "areaSquareWa": 0,
            "titleAddress":
            {
                "houseNo": "",
                "projectName": "",
                "moo": "",
                "soi": "",
                "road": "123456789",
                "subDistrict": "Muang",
                "district": "Watket",
                "province": "Chiang Mai",
                "postcode": "50000"
            },
            "dopaAddress":
            {
                "houseNo": "",
                "projectName": "",
                "moo": "",
                "soi": "",
                "road": "",
                "subDistrict": "Muang",
                "district": "Watket",
                "province": "Chiang Mai",
                "postcode": "50000"
            },
            "notes": "",
            "requestTitleDocumentDtos": 
            [
                {
                    "id": "b1406829-caae-4248-adf9-147a374b6095",
                    "documentId": "c5f2d07a-9a9e-4b13-b9e2-0b8d0f5f1104",
                    "documentType": "Test Update 4",
                    "isRequired": false,
                    "documentDescription": "new document D1",
                    "uploadedBy": "xxxxx",
                    "uploadedByName": "Joe"
                },
                {
                    "documentId": "c5f2d07a-9a9e-4b13-b9e2-0b8d0f5f1105",
                    "documentType": "Test Update 4",
                    "isRequired": false,
                    "documentDescription": "new document D2",
                    "uploadedBy": "xxxxx",
                    "uploadedByName": "Joe"
                }
            ]
        }
    ]
}