namespace Appraisal.Application.Features.Project.CreateProjectTower;

/// <summary>Request to create a tower within a Condo project.</summary>
public record CreateProjectTowerRequest(
    string? TowerName = null,
    int? NumberOfUnits = null,
    int? NumberOfFloors = null,
    string? CondoRegistrationNumber = null,
    List<Guid>? ModelTypeIds = null,
    string? ConditionType = null,
    bool? HasObligation = null,
    string? ObligationDetails = null,
    string? DocumentValidationType = null,
    bool? IsLocationCorrect = null,
    decimal? Distance = null,
    decimal? RoadWidth = null,
    decimal? RightOfWay = null,
    string? RoadSurfaceType = null,
    string? RoadSurfaceTypeOther = null,
    string? DecorationType = null,
    string? DecorationTypeOther = null,
    int? ConstructionYear = null,
    int? TotalNumberOfFloors = null,
    string? BuildingFormType = null,
    string? ConstructionMaterialType = null,
    string? GroundFloorMaterialType = null,
    string? GroundFloorMaterialTypeOther = null,
    string? UpperFloorMaterialType = null,
    string? UpperFloorMaterialTypeOther = null,
    string? BathroomFloorMaterialType = null,
    string? BathroomFloorMaterialTypeOther = null,
    List<string>? RoofType = null,
    string? RoofTypeOther = null,
    bool? IsExpropriated = null,
    string? ExpropriationRemark = null,
    bool? IsInExpropriationLine = null,
    string? RoyalDecree = null,
    bool? IsForestBoundary = null,
    string? ForestBoundaryRemark = null,
    string? Remark = null,
    List<Guid>? ImageDocumentIds = null
);
