@baseUrl = https://localhost:7111

@requestId = EB09E7F2-FF78-497F-22A7-08DE20F81BC9

POST {{baseUrl}}/requests/{{requestId}}/titles/draft
Host: localhost:7111
Content-Type: application/json

{
	"titleAddress":
	{
		
	},
	"dopaAddress":
	{
		
	},
	"notes": ""
}