@baseUrl = https://localhost:7111
@requestId = AEB2C52F-CB03-4AA7-868A-08DE1DD6E8B1
@titleId = CAE86C0E-1AD4-4542-9E20-82CE68BDFA95

GET {{baseUrl}}/requests/{{requestId}}/titles/{{titleId}}
Host: localhost:7111
Content-Type: application/json

{
	
}