@baseUrl = https://Localhost:7111
@requestId = 6D884C99-1F73-4F6C-86A4-08DE227BF8AC
@titleId = F9C50A37-345A-4981-96DC-0513A83AB837

DELETE {{baseUrl}}/requests/{{requestId}}/titles/{{titleId}}
Host: localhost:7111
Content-Type: application/json

{

}