@baseUrl = https://localhost:7111

@requestId = 6D884C99-1F73-4F6C-86A4-08DE227BF8AC

@titleId = 98CCC8AB-CCE2-45B6-B0E6-5FCA52B8B75D

PATCH {{baseUrl}}/requests/{{requestId}}/titles/{{titleId}}
Host: localhost:7111
Content-Type: application/json

{
    "collateralType": "L",
    "collateralStatus": false,
    "titleNo": "1234",
    "deedType": "NorSor3",
    "rawang": "01",
    "landNo": "01",
    "surveyNo": "01",
    "areaRai": 0,
    "areaNgan": 0,
    "areaSquareWa": 0,
    "titleAddress":
    {
        "subDistrict": "00",
        "district": "00",
        "province": "00",
        "postcode": "00"
    },
    "dopaAddress": 
    {
        "subDistrict": "00",
        "district": "00",
        "province": "00",
        "postcode": "00"
    }
}