using Shared.DDD;
using Workflow.Domain.Committees;
using Workflow.Meetings.Domain.Events;
using Workflow.Meetings.ReadModels;

namespace Workflow.Meetings.Domain;

public class Meeting : Aggregate<Guid>
{
    public string Title { get; private set; } = default!;
    public string? Location { get; private set; }
    public string? Notes { get; private set; }
    public MeetingStatus Status { get; private set; }
    public string? CancelReason { get; private set; }
    public DateTime? EndedAt { get; private set; }
    public DateTime? CancelledAt { get; private set; }

    // ----- Meeting number -----

    public string? MeetingNo { get; private set; }
    public int? MeetingNoYear { get; private set; }
    public int? MeetingNoSeq { get; private set; }

    /// <summary>Scheduled start time.</summary>
    public DateTime? StartAt { get; private set; }

    /// <summary>Scheduled end time.</summary>
    public DateTime? EndAt { get; private set; }

    /// <summary>Free-text "from" field for the meeting agenda header.</summary>
    public string? FromText { get; private set; }

    /// <summary>Free-text "to" field for the meeting agenda header.</summary>
    public string? ToText { get; private set; }

    public string? AgendaCertifyMinutes { get; private set; }
    public string? AgendaChairmanInformed { get; private set; }
    public string? AgendaOthers { get; private set; }

    public DateTime? CutOffAt { get; private set; }
    public DateTime? InvitationSentAt { get; private set; }

    /// <summary>Optimistic concurrency token managed by EF Core.</summary>
    public byte[] RowVersion { get; private set; } = default!;

    // ----- Collections -----

    private readonly List<MeetingItem> _items = new();
    public IReadOnlyList<MeetingItem> Items => _items.AsReadOnly();

    private readonly List<MeetingMember> _members = new();
    public IReadOnlyList<MeetingMember> Members => _members.AsReadOnly();

    private Meeting() { }

    // -------------------------------------------------------------------------
    // Factory
    // -------------------------------------------------------------------------

    /// <summary>
    /// Creates a New meeting with the pre-generated meeting number.
    /// The meeting number is generated by the application handler (via <see cref="IMeetingNoGenerator"/>)
    /// before calling this factory, so every meeting has a number from birth.
    /// </summary>
    public static Meeting Create(string title, string? notes, string meetingNo, int meetingNoSeq, int meetingNoYear)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(title);
        ArgumentException.ThrowIfNullOrWhiteSpace(meetingNo);

        return new Meeting
        {
            Id = Guid.CreateVersion7(),
            Title = title.Trim(),
            Notes = notes,
            Status = MeetingStatus.New,
            MeetingNo = meetingNo,
            MeetingNoSeq = meetingNoSeq,
            MeetingNoYear = meetingNoYear
        };
    }

    // -------------------------------------------------------------------------
    // Member management
    // -------------------------------------------------------------------------

    /// <summary>
    /// Copies active members of <paramref name="committee"/> into this meeting,
    /// applying parity filtering based on <paramref name="meetingSeq"/>.
    /// May only be called once (throws if members already exist).
    /// </summary>
    public void SnapshotCommittee(Committee committee, int meetingSeq)
    {
        ArgumentNullException.ThrowIfNull(committee);

        if (_members.Count > 0)
            throw new InvalidOperationException(
                "Committee snapshot has already been taken for this meeting");

        foreach (var cm in committee.GetActiveMembers(meetingSeq))
            _members.Add(MeetingMember.CreateSnapshot(Id, cm));
    }

    public void AddMember(MeetingMember member, DateTime now)
    {
        EnsureMutableStatus();
        EnsureNotInProgress(now);
        ArgumentNullException.ThrowIfNull(member);

        if (_members.Any(m => m.UserId == member.UserId))
            throw new InvalidOperationException(
                $"User {member.UserId} is already a member of this meeting");

        _members.Add(member);
    }

    public void RemoveMember(Guid memberId, DateTime now)
    {
        EnsureMutableStatus();
        EnsureNotInProgress(now);

        var member = _members.FirstOrDefault(m => m.Id == memberId)
            ?? throw new InvalidOperationException(
                $"Meeting member {memberId} not found");

        _members.Remove(member);
    }

    public void ChangeMemberPosition(Guid memberId, CommitteeMemberPosition position, DateTime now)
    {
        EnsureMutableStatus();
        EnsureNotInProgress(now);

        var member = _members.FirstOrDefault(m => m.Id == memberId)
            ?? throw new InvalidOperationException(
                $"Meeting member {memberId} not found");

        member.UpdatePosition(position);
    }

    // -------------------------------------------------------------------------
    // Item management
    // -------------------------------------------------------------------------

    public MeetingItem AddItem(
        Guid appraisalId,
        string? appraisalNo,
        decimal facilityLimit,
        Guid workflowInstanceId,
        string activityId,
        DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cannot add items to a meeting in status {Status}");

        EnsureNotInProgress(now);

        if (_items.Any(i => i.AppraisalId == appraisalId))
            throw new InvalidOperationException(
                $"Appraisal {appraisalId} is already on this meeting");

        var item = MeetingItem.CreateDecision(
            Id, appraisalId, appraisalNo, facilityLimit,
            appraisalType: null, workflowInstanceId, activityId);
        _items.Add(item);
        return item;
    }

    public MeetingItem RemoveItem(Guid appraisalId, DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cannot remove items from a meeting in status {Status}");

        EnsureNotInProgress(now);

        var item = _items.FirstOrDefault(i => i.AppraisalId == appraisalId)
            ?? throw new InvalidOperationException(
                $"Appraisal {appraisalId} is not on this meeting");

        _items.Remove(item);
        return item;
    }

    // -------------------------------------------------------------------------
    // Cut-off
    // -------------------------------------------------------------------------

    /// <summary>
    /// Freezes the meeting agenda by converting queued decision items and pending
    /// acknowledgement items into <see cref="MeetingItem"/> rows.
    /// Allowed in <see cref="MeetingStatus.New"/> and <see cref="MeetingStatus.InvitationSent"/>.
    /// Additive and idempotent: items already on the meeting are skipped; CutOffAt is updated to now.
    /// May be called multiple times to pull in newly queued items.
    /// </summary>
    public void CutOff(
        IEnumerable<MeetingQueueItem> queuedItems,
        IEnumerable<AppraisalAcknowledgementQueueItem> ackPendingItems,
        DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cut-off is only allowed in New or InvitationSent status; current status is {Status}");

        EnsureNotInProgress(now);

        var includedAppraisalIds = new List<Guid>();

        foreach (var qi in queuedItems)
        {
            if (_items.Any(i => i.AppraisalId == qi.AppraisalId))
                continue;

            var item = MeetingItem.CreateDecision(
                Id, qi.AppraisalId, qi.AppraisalNo, qi.FacilityLimit,
                appraisalType: null, qi.WorkflowInstanceId, qi.ActivityId);
            _items.Add(item);
            qi.AssignTo(Id);
            includedAppraisalIds.Add(qi.AppraisalId);
        }

        foreach (var ai in ackPendingItems)
        {
            if (_items.Any(i => i.AppraisalId == ai.AppraisalId))
                continue;

            var item = MeetingItem.CreateAcknowledgement(
                Id, ai.AppraisalId, ai.AppraisalNo, facilityLimit: 0,
                appraisalType: null, ai.AcknowledgementGroup, ai.AppraisalDecisionId);
            _items.Add(item);
            ai.Include(Id);
            includedAppraisalIds.Add(ai.AppraisalId);
        }

        CutOffAt = now;

        AddDomainEvent(new MeetingCutOffDomainEvent(Id, includedAppraisalIds.AsReadOnly()));
    }

    // -------------------------------------------------------------------------
    // Invitation
    // -------------------------------------------------------------------------

    /// <summary>
    /// Transitions <see cref="MeetingStatus.New"/> → <see cref="MeetingStatus.InvitationSent"/>
    /// and raises <see cref="MeetingInvitationSentDomainEvent"/>.
    /// Idempotent re-send (already InvitationSent): updates <see cref="InvitationSentAt"/> only, no new event.
    /// </summary>
    public void SendInvitation(DateTime now)
    {
        if (Status == MeetingStatus.Ended || Status == MeetingStatus.Cancelled)
            throw new InvalidOperationException(
                $"Cannot send invitation for a meeting in terminal status {Status}");

        if (Status == MeetingStatus.RoutedBack)
            throw new InvalidOperationException(
                $"Cannot send invitation for a meeting in status {Status}");

        if (Status == MeetingStatus.InvitationSent)
        {
            // Idempotent re-send: just update the timestamp
            InvitationSentAt = now;
            return;
        }

        // New → InvitationSent
        InvitationSentAt = now;
        Status = MeetingStatus.InvitationSent;

        AddDomainEvent(new MeetingInvitationSentDomainEvent(Id, MeetingNo!));
    }

    // -------------------------------------------------------------------------
    // Schedule
    // -------------------------------------------------------------------------

    public void SetSchedule(DateTime startAt, DateTime endAt, string? location, DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cannot set schedule in status {Status}");

        EnsureNotInProgress(now);

        if (endAt <= startAt)
            throw new ArgumentException("EndAt must be after StartAt");

        StartAt = startAt;
        EndAt = endAt;

        if (!string.IsNullOrWhiteSpace(location))
            Location = location;
    }

    public void SetAgenda(
        string? from,
        string? to,
        string? certifyMinutes,
        string? chairmanInformed,
        string? others,
        DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cannot set agenda in status {Status}");

        EnsureNotInProgress(now);

        if (from is not null && from.Length > 200)
            throw new ArgumentException("FromText must not exceed 200 characters");
        if (to is not null && to.Length > 200)
            throw new ArgumentException("ToText must not exceed 200 characters");
        if (certifyMinutes is not null && certifyMinutes.Length > 2000)
            throw new ArgumentException("AgendaCertifyMinutes must not exceed 2000 characters");
        if (chairmanInformed is not null && chairmanInformed.Length > 2000)
            throw new ArgumentException("AgendaChairmanInformed must not exceed 2000 characters");
        if (others is not null && others.Length > 2000)
            throw new ArgumentException("AgendaOthers must not exceed 2000 characters");

        FromText = from;
        ToText = to;
        AgendaCertifyMinutes = certifyMinutes;
        AgendaChairmanInformed = chairmanInformed;
        AgendaOthers = others;
    }

    // -------------------------------------------------------------------------
    // Details
    // -------------------------------------------------------------------------

    public void UpdateDetails(string title, string? location, string? notes, DateTime now)
    {
        EnsureNotTerminal();
        EnsureNotInProgress(now);
        ArgumentException.ThrowIfNullOrWhiteSpace(title);

        Title = title.Trim();
        Location = location;
        Notes = notes;
    }

    // -------------------------------------------------------------------------
    // Cancel
    // -------------------------------------------------------------------------

    /// <summary>
    /// Cancels a New or InvitationSent meeting. <paramref name="reason"/> is required.
    /// Raises exactly one <see cref="MeetingCancelledDomainEvent"/> regardless of the number of
    /// decision items (including zero), so the handler always runs to detach ack items.
    /// </summary>
    public void Cancel(string reason, DateTime now)
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"Cannot cancel a meeting in status {Status}");

        EnsureNotInProgress(now);

        ArgumentException.ThrowIfNullOrWhiteSpace(reason);

        Status = MeetingStatus.Cancelled;
        CancelReason = reason;
        CancelledAt = now;

        var cancelledDecisionItems = _items
            .Where(i => i.Kind == MeetingItemKind.Decision)
            .Select(i => new CancelledDecisionItem(
                i.AppraisalId, i.WorkflowInstanceId!.Value, i.ActivityId!))
            .ToList()
            .AsReadOnly();

        AddDomainEvent(new MeetingCancelledDomainEvent(
            Id, reason, CancelledAt.Value, cancelledDecisionItems));
    }

    // -------------------------------------------------------------------------
    // Secretary decisions
    // -------------------------------------------------------------------------

    /// <summary>
    /// Secretary releases a Decision item.
    /// Allowed in <see cref="MeetingStatus.InvitationSent"/> and <see cref="MeetingStatus.RoutedBack"/>.
    /// If this is the last Decision item with a pending outcome, the meeting auto-transitions to
    /// <see cref="MeetingStatus.Ended"/> and raises <see cref="MeetingEndedDomainEvent"/>.
    /// </summary>
    public void ReleaseItem(Guid appraisalId, string actor, DateTime now)
    {
        EnsureDecisionAllowed();
        ArgumentException.ThrowIfNullOrWhiteSpace(actor);

        var item = GetDecisionItemOrThrow(appraisalId);

        if (item.ItemDecision != ItemDecision.Pending)
            throw new InvalidOperationException(
                $"Cannot release item for appraisal {appraisalId}: decision is already {item.ItemDecision}");

        item.ApplyDecision(ItemDecision.Released, actor, reason: null, now);

        // Decision items always have WorkflowInstanceId/ActivityId set — guard defensively.
        if (!item.WorkflowInstanceId.HasValue || item.ActivityId is null)
            throw new InvalidOperationException(
                $"Decision item for appraisal {appraisalId} is missing WorkflowInstanceId or ActivityId");

        var memberUserIds = _members.Select(m => m.UserId).ToList().AsReadOnly();

        AddDomainEvent(new MeetingItemReleasedDomainEvent(
            Id, appraisalId, item.WorkflowInstanceId.Value, item.ActivityId, actor, memberUserIds));

        // Auto-transition: if every Decision item has been Released, end the meeting.
        var allDecisionItems = _items.Where(i => i.Kind == MeetingItemKind.Decision).ToList();
        if (allDecisionItems.Count > 0 && allDecisionItems.All(i => i.ItemDecision == ItemDecision.Released))
        {
            Status = MeetingStatus.Ended;
            EndedAt = now;
            AddDomainEvent(new MeetingEndedDomainEvent(Id, now));
        }
    }

    /// <summary>
    /// Secretary routes a Decision item back to the appraisal team.
    /// Allowed in <see cref="MeetingStatus.InvitationSent"/> and <see cref="MeetingStatus.RoutedBack"/>.
    /// Always sets the meeting status to <see cref="MeetingStatus.RoutedBack"/>.
    /// </summary>
    public void RouteBackItem(Guid appraisalId, string actor, string reason, DateTime now)
    {
        EnsureDecisionAllowed();
        ArgumentException.ThrowIfNullOrWhiteSpace(actor);
        ArgumentException.ThrowIfNullOrWhiteSpace(reason);

        var item = GetDecisionItemOrThrow(appraisalId);

        if (item.ItemDecision != ItemDecision.Pending)
            throw new InvalidOperationException(
                $"Cannot route back item for appraisal {appraisalId}: decision is already {item.ItemDecision}");

        item.ApplyDecision(ItemDecision.RoutedBack, actor, reason, now);

        // Decision items always have WorkflowInstanceId/ActivityId set — guard defensively.
        if (!item.WorkflowInstanceId.HasValue || item.ActivityId is null)
            throw new InvalidOperationException(
                $"Decision item for appraisalId {appraisalId} is missing WorkflowInstanceId or ActivityId");

        // Sticky: once any item is routed back, the meeting stays in RoutedBack.
        Status = MeetingStatus.RoutedBack;

        AddDomainEvent(new MeetingItemRoutedBackDomainEvent(
            Id, appraisalId, item.WorkflowInstanceId.Value, item.ActivityId, reason, actor));
    }

    // -------------------------------------------------------------------------
    // Reinstate
    // -------------------------------------------------------------------------

    /// <summary>
    /// Re-enters a routed-back appraisal onto this same meeting by resetting its item's
    /// decision back to <see cref="ItemDecision.Pending"/>. The meeting remains in
    /// <see cref="MeetingStatus.RoutedBack"/> — it can only leave that status once every
    /// Decision item is Released (the existing <see cref="ReleaseItem"/> auto-end rule).
    /// </summary>
    /// <remarks>
    /// This is the only valid re-entry path. The <see cref="Meetings.Activities.MeetingActivity"/>
    /// calls this instead of enqueuing a new <see cref="ReadModels.MeetingQueueItem"/> when it
    /// detects an existing routed-back item for the same workflow instance.
    /// </remarks>
    public void ReinstateRoutedBackItem(Guid appraisalId, DateTime now)
    {
        if (Status != MeetingStatus.RoutedBack)
            throw new InvalidOperationException(
                $"Cannot reinstate items on a meeting in status {Status}; expected RoutedBack");

        var item = GetDecisionItemOrThrow(appraisalId);
        item.Reinstate(now);
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private void EnsureNotTerminal()
    {
        if (Status == MeetingStatus.Ended || Status == MeetingStatus.Cancelled)
            throw new InvalidOperationException(
                $"Meeting is in terminal status {Status}");
    }

    /// <summary>Guards mutating operations that are allowed in <see cref="MeetingStatus.New"/> and
    /// <see cref="MeetingStatus.InvitationSent"/> only.</summary>
    private void EnsureMutableStatus()
    {
        if (Status != MeetingStatus.New && Status != MeetingStatus.InvitationSent)
            throw new InvalidOperationException(
                $"This operation is only allowed in New or InvitationSent status; current status is {Status}");
    }

    /// <summary>
    /// Blocks mutation operations once the meeting has effectively started.
    /// Effective InProgress = persisted <see cref="MeetingStatus.InvitationSent"/> + StartAt &lt;= now.
    /// </summary>
    private void EnsureNotInProgress(DateTime now)
    {
        if (Status == MeetingStatus.InvitationSent
            && StartAt.HasValue && StartAt.Value <= now)
        {
            throw new InvalidOperationException(
                "Cannot perform this operation once the meeting has started (StartAt has passed)");
        }
    }

    /// <summary>Guards secretary decision operations (Release / RouteBack).</summary>
    private void EnsureDecisionAllowed()
    {
        if (Status != MeetingStatus.InvitationSent && Status != MeetingStatus.RoutedBack)
            throw new InvalidOperationException(
                $"Secretary decisions are only allowed in InvitationSent or RoutedBack status; current status is {Status}");
    }

    private MeetingItem GetDecisionItemOrThrow(Guid appraisalId)
    {
        var item = _items.FirstOrDefault(i => i.AppraisalId == appraisalId)
            ?? throw new InvalidOperationException(
                $"Appraisal {appraisalId} is not on this meeting");

        if (item.Kind != MeetingItemKind.Decision)
            throw new InvalidOperationException(
                $"Appraisal {appraisalId} is an acknowledgement item and cannot be released or routed back");

        return item;
    }
}
