namespace Appraisal.Application.Features.Appraisals.GetLandAndBuildingProperty;

/// <summary>
/// Result of getting a land and building property
/// </summary>
public record GetLandAndBuildingPropertyResult(
    // Property
    Guid PropertyId,
    Guid AppraisalId,
    int SequenceNumber,
    string PropertyType,
    string? Description,
    Guid DetailId,
    // Property Identification
    string? PropertyName,
    string? LandDescription,
    decimal? Latitude,
    decimal? Longitude,
    string? SubDistrict,
    string? District,
    string? Province,
    string? LandOffice,
    // Owner Fields
    string? OwnerName,
    bool? IsOwnerVerified,
    bool? HasObligation,
    string? ObligationDetails,
    // Land - Document Verification
    bool? IsLandLocationVerified,
    string? LandCheckMethod,
    string? LandCheckMethodOther,
    // Land - Location Details
    string? Street,
    string? Soi,
    decimal? DistanceFromMainRoad,
    string? Village,
    string? AddressLocation,
    // Land - Characteristics
    string? LandShape,
    string? UrbanPlanningType,
    List<string>? LandZoneType,
    List<string>? PlotLocationType,
    string? PlotLocationOther,
    string? LandFillStatus,
    string? LandFillStatusOther,
    decimal? LandFillPercent,
    decimal? SoilLevel,
    // Land - Road Access
    decimal? AccessRoadWidth,
    short? RightOfWay,
    decimal? RoadFrontage,
    int? NumberOfSidesFacingRoad,
    string? RoadPassInFrontOfLand,
    string? LandAccessibility,
    string? LandAccessibilityDescription,
    string? RoadSurfaceType,
    string? RoadSurfaceTypeOther,
    // Land - Utilities
    bool? ElectricityAvailable,
    decimal? ElectricityDistance,
    List<string>? PublicUtilities,
    string? PublicUtilitiesOther,
    List<string>? LandUseType,
    string? LandUseTypeOther,
    List<string>? LandEntranceExit,
    string? LandEntranceExitOther,
    List<string>? TransportationAccess,
    string? TransportationAccessOther,
    string? PropertyAnticipation,
    // Land - Legal
    bool? IsExpropriated,
    string? ExpropriationRemark,
    bool? IsInExpropriationLine,
    string? ExpropriationLineRemark,
    string? RoyalDecree,
    bool? IsEncroached,
    string? EncroachmentRemark,
    decimal? EncroachmentArea,
    bool? IsLandlocked,
    string? LandlockedRemark,
    bool? IsForestBoundary,
    string? ForestBoundaryRemark,
    string? OtherLegalLimitations,
    List<string>? EvictionStatus,
    string? EvictionStatusOther,
    string? AllocationStatus,
    // Land - Boundaries
    string? NorthAdjacentArea,
    decimal? NorthBoundaryLength,
    string? SouthAdjacentArea,
    decimal? SouthBoundaryLength,
    string? EastAdjacentArea,
    decimal? EastBoundaryLength,
    string? WestAdjacentArea,
    decimal? WestBoundaryLength,
    // Land - Other
    decimal? PondArea,
    decimal? PondDepth,
    bool? HasBuilding,
    string? HasBuildingOther,
    // Building - Identification
    string? BuildingNumber,
    string? ModelName,
    string? BuiltOnTitleNumber,
    string? HouseNumber,
    // Building - Info
    string? BuildingType,
    string? BuildingTypeOther,
    decimal? NumberOfFloors,
    string? DecorationType,
    string? DecorationTypeOther,
    bool? IsEncroachingOthers,
    string? EncroachingOthersRemark,
    decimal? EncroachingOthersArea,
    // Building - Status
    string? BuildingCondition,
    bool? IsUnderConstruction,
    decimal? ConstructionCompletionPercent,
    DateTime? ConstructionLicenseExpirationDate,
    bool? IsAppraisable,
    // Building - Age
    int? BuildingAge,
    int? ConstructionYear,
    string? ResidentialRemark,
    // Building - Style
    string? BuildingMaterial,
    string? BuildingStyle,
    bool? IsResidential,
    string? ConstructionStyleType,
    string? ConstructionStyleRemark,
    string? ConstructionType,
    string? ConstructionTypeOther,
    // Building - Components
    List<string>? StructureType,
    string? StructureTypeOther,
    List<string>? RoofFrameType,
    string? RoofFrameTypeOther,
    List<string>? RoofType,
    string? RoofTypeOther,
    List<string>? CeilingType,
    string? CeilingTypeOther,
    List<string>? InteriorWallType,
    string? InteriorWallTypeOther,
    List<string>? ExteriorWallType,
    string? ExteriorWallTypeOther,
    List<string>? FenceType,
    string? FenceTypeOther,
    // Building - Utilization
    string? UtilizationType,
    string? OtherPurposeUsage,
    // Building - Area
    decimal? TotalBuildingArea,
    // Building - Pricing
    decimal? BuildingInsurancePrice,
    decimal? SellingPrice,
    decimal? ForcedSalePrice,
    // Remarks
    string? LandRemark,
    string? BuildingRemark
);