namespace Appraisal.Application.Features.Appraisals.GetLandAndBuildingProperty;

/// <summary>
/// Response for getting a land and building property
/// </summary>
public record GetLandAndBuildingPropertyResponse(
    // Property
    Guid PropertyId,
    Guid AppraisalId,
    int SequenceNumber,
    string PropertyType,
    string? Description,
    Guid DetailId,
    // Property Identification
    string? PropertyName,
    string? LandDescription,
    decimal? Latitude,
    decimal? Longitude,
    string? SubDistrict,
    string? District,
    string? Province,
    string? LandOffice,
    // Owner Fields
    string OwnerName,
    string OwnershipType,
    string? OwnershipDocument,
    decimal? OwnershipPercentage,
    bool IsOwnerVerified,
    bool HasObligation,
    string? ObligationDetails,
    string? PropertyUsage,
    string? OccupancyStatus,
    // Land - Title Deed
    string? TitleDeedType,
    string? TitleDeedNumber,
    string? LandNumber,
    string? SurveyPageNumber,
    decimal? Rai,
    decimal? Ngan,
    decimal? SquareWa,
    // Land - Document Verification
    string? LandLocationVerification,
    string? LandCheckMethod,
    string? LandCheckMethodOther,
    // Land - Location Details
    string? Street,
    string? Soi,
    decimal? DistanceFromMainRoad,
    string? Village,
    string? AddressLocation,
    // Land - Characteristics
    string? LandShape,
    string? UrbanPlanningType,
    string? PlotLocation,
    string? PlotLocationOther,
    string? LandFillStatus,
    string? LandFillStatusOther,
    decimal? LandFillPercent,
    string? TerrainType,
    string? SoilCondition,
    string? SoilLevel,
    string? FloodRisk,
    string? LandUseZoning,
    string? LandUseZoningOther,
    // Land - Road Access
    string? AccessRoadType,
    decimal? AccessRoadWidth,
    string? RightOfWay,
    decimal? RoadFrontage,
    int? NumberOfSidesFacingRoad,
    string? RoadPassInFrontOfLand,
    string? LandAccessibility,
    string? LandAccessibilityDescription,
    string? RoadSurfaceType,
    string? RoadSurfaceTypeOther,
    // Land - Utilities
    bool? ElectricityAvailable,
    decimal? ElectricityDistance,
    bool? WaterSupplyAvailable,
    bool? SewerageAvailable,
    string? PublicUtilities,
    string? PublicUtilitiesOther,
    string? LandEntranceExit,
    string? LandEntranceExitOther,
    string? TransportationAccess,
    string? TransportationAccessOther,
    string? PropertyAnticipation,
    // Land - Legal
    bool IsExpropriated,
    string? ExpropriationRemark,
    bool IsInExpropriationLine,
    string? ExpropriationLineRemark,
    string? RoyalDecree,
    bool IsEncroached,
    string? EncroachmentRemark,
    decimal? EncroachmentArea,
    bool IsLandlocked,
    string? LandlockedRemark,
    bool IsForestBoundary,
    string? ForestBoundaryRemark,
    string? OtherLegalLimitations,
    string? EvictionStatus,
    string? EvictionStatusOther,
    string? AllocationStatus,
    // Land - Boundaries
    string? NorthAdjacentArea,
    decimal? NorthBoundaryLength,
    string? SouthAdjacentArea,
    decimal? SouthBoundaryLength,
    string? EastAdjacentArea,
    decimal? EastBoundaryLength,
    string? WestAdjacentArea,
    decimal? WestBoundaryLength,
    // Land - Other
    decimal? PondArea,
    decimal? PondDepth,
    // Building - Identification
    string? BuildingNumber,
    string? ModelName,
    string? BuiltOnTitleNumber,
    string? HouseNumber,
    // Building - Info
    string? BuildingType,
    string? BuildingTypeOther,
    int? NumberOfBuildings,
    int? BuildingAge,
    int? ConstructionYear,
    string? IsResidentialRemark,
    // Building - Status
    string? BuildingCondition,
    bool IsUnderConstruction,
    decimal? ConstructionCompletionPercent,
    DateTime? ConstructionLicenseExpirationDate,
    bool IsAppraisable,
    string? MaintenanceStatus,
    string? RenovationHistory,
    // Building - Area
    decimal? TotalBuildingArea,
    string? BuildingAreaUnit,
    decimal? UsableArea,
    // Building - Structure
    int? NumberOfFloors,
    int? NumberOfUnits,
    int? NumberOfBedrooms,
    int? NumberOfBathrooms,
    // Building - Style
    string? BuildingMaterial,
    string? BuildingStyle,
    bool? IsResidential,
    string? ConstructionStyleType,
    string? ConstructionStyleRemark,
    string? ConstructionType,
    string? ConstructionTypeOther,
    // Building - Components
    string? StructureType,
    string? StructureTypeOther,
    string? FoundationType,
    string? RoofFrameType,
    string? RoofFrameTypeOther,
    string? RoofType,
    string? RoofTypeOther,
    string? RoofMaterial,
    string? CeilingType,
    string? CeilingTypeOther,
    string? InteriorWallType,
    string? InteriorWallTypeOther,
    string? ExteriorWallType,
    string? ExteriorWallTypeOther,
    string? WallMaterial,
    string? FloorMaterial,
    string? FenceType,
    string? FenceTypeOther,
    // Building - Decoration
    string? DecorationType,
    string? DecorationTypeOther,
    // Building - Utilization
    string? UtilizationType,
    string? OtherPurposeUsage,
    // Building - Permits
    string? BuildingPermitNumber,
    DateTime? BuildingPermitDate,
    bool? HasOccupancyPermit,
    // Building - Pricing
    decimal? BuildingInsurancePrice,
    decimal? SellingPrice,
    decimal? ForcedSalePrice,
    // Remarks
    string? LandRemark,
    string? BuildingRemark
);
