namespace Appraisal.Application.Features.Appraisals.GetLandAndBuildingProperty;

/// <summary>
/// Response for getting a land and building property
/// </summary>
public record GetLandAndBuildingPropertyResponse(
    // Property
    Guid PropertyId,
    Guid AppraisalId,
    int SequenceNumber,
    string PropertyType,
    string? Description,
    Guid DetailId,
    // Property Identification
    string? PropertyName,
    string? LandDescription,
    decimal? Latitude,
    decimal? Longitude,
    string? SubDistrict,
    string? District,
    string? Province,
    string? LandOffice,
    // Owner Fields
    string? OwnerName,
    bool? IsOwnerVerified,
    bool? HasObligation,
    string? ObligationDetails,
    // Land - Document Verification
    bool? IsLandLocationVerified,
    string? LandCheckMethodType,
    string? LandCheckMethodTypeOther,
    // Land - Location Details
    string? Street,
    string? Soi,
    decimal? DistanceFromMainRoad,
    string? Village,
    string? AddressLocation,
    // Land - Characteristics
    string? LandShapeType,
    string? UrbanPlanningType,
    List<string>? LandZoneType,
    List<string>? PlotLocationType,
    string? PlotLocationOther,
    string? LandFillType,
    string? LandFillTypeOther,
    decimal? LandFillPercent,
    decimal? SoilLevel,
    // Land - Road Access
    decimal? AccessRoadWidth,
    short? RightOfWay,
    decimal? RoadFrontage,
    int? NumberOfSidesFacingRoad,
    string? RoadPassInFrontOfLand,
    string? LandAccessibilityType,
    string? LandAccessibilityRemark,
    string? RoadSurfaceType,
    string? RoadSurfaceTypeOther,
    // Land - Utilities
    bool? HasElectricity,
    decimal? ElectricityDistance,
    List<string>? PublicUtilityType,
    string? PublicUtilityTypeOther,
    List<string>? LandUseType,
    string? LandUseTypeOther,
    List<string>? LandEntranceExitType,
    string? LandEntranceExitTypeOther,
    List<string>? TransportationAccessType,
    string? TransportationAccessTypeOther,
    string? PropertyAnticipationType,
    // Land - Legal
    bool? IsExpropriated,
    string? ExpropriationRemark,
    bool? IsInExpropriationLine,
    string? ExpropriationLineRemark,
    string? RoyalDecree,
    bool? IsEncroached,
    string? EncroachmentRemark,
    decimal? EncroachmentArea,
    bool? IsLandlocked,
    string? LandlockedRemark,
    bool? IsForestBoundary,
    string? ForestBoundaryRemark,
    string? OtherLegalLimitations,
    List<string>? EvictionType,
    string? EvictionTypeOther,
    string? AllocationType,
    // Land - Boundaries
    string? NorthAdjacentArea,
    decimal? NorthBoundaryLength,
    string? SouthAdjacentArea,
    decimal? SouthBoundaryLength,
    string? EastAdjacentArea,
    decimal? EastBoundaryLength,
    string? WestAdjacentArea,
    decimal? WestBoundaryLength,
    // Land - Other
    decimal? PondArea,
    decimal? PondDepth,
    bool? HasBuilding,
    string? HasBuildingOther,
    // Building - Identification
    string? BuildingNumber,
    string? ModelName,
    string? BuiltOnTitleNumber,
    string? HouseNumber,
    // Building Status
    string? BuildingConditionType,
    bool? IsUnderConstruction,
    decimal? ConstructionCompletionPercent,
    DateTime? ConstructionLicenseExpirationDate,
    bool? IsAppraisable,
    // Building Info
    string? BuildingType,
    string? BuildingTypeOther,
    decimal? NumberOfFloors,
    string? DecorationType,
    string? DecorationTypeOther,
    bool? IsEncroachingOthers,
    string? EncroachingOthersRemark,
    decimal? EncroachingOthersArea,
    // Construction Details
    string? BuildingMaterialType,
    string? BuildingStyleType,
    bool? IsResidential,
    int? BuildingAge,
    int? ConstructionYear,
    string? ResidentialRemark,
    string? ConstructionStyleType,
    string? ConstructionStyleRemark,
    // Structure Components
    List<string>? StructureType,
    string? StructureTypeOther,
    List<string>? RoofFrameType,
    string? RoofFrameTypeOther,
    List<string>? RoofType,
    string? RoofTypeOther,
    List<string>? CeilingType,
    string? CeilingTypeOther,
    List<string>? InteriorWallType,
    string? InteriorWallTypeOther,
    List<string>? ExteriorWallType,
    string? ExteriorWallTypeOther,
    List<string>? FenceType,
    string? FenceTypeOther,
    string? ConstructionType,
    string? ConstructionTypeOther,
    // Utilization
    string? UtilizationType,
    string? UtilizationTypeOther,
    // Area & Pricing
    decimal? TotalBuildingArea,
    decimal? BuildingInsurancePrice,
    decimal? SellingPrice,
    decimal? ForcedSalePrice,
    // Remarks
    string? LandRemark,
    string? BuildingRemark
);
