-- =============================================================================
--  MASTER RBAC DEPLOYMENT SCRIPT
--  Brings an EXISTING database's access control to the intended state without a
--  code deploy. Covers the three areas the C# seed would otherwise own:
--    PART A  auth.RolePermissions      role -> permission grants (full sync)
--    PART B  auth.MenuItems            appraisal action-tab edit gates
--    PART C  auth.ActivityMenuOverrides per-activity menu visibility/edit overrides
--
--  Idempotent + transactional: safe to re-run; either all parts apply or none.
--  Matches ActivityMenuOverrideSeedData / AuthDataSeed / MenuSeedData as of
--  2026-08-02 (dev DB: Admin = ALL 134 perms / IntAdmin 40 / ... / 115 override rows).
--  (134 = 133 + JOB_SCHEDULE_MANAGE, added 2026-08-02.)
--
--  IMPORTANT
--   * SET QUOTED_IDENTIFIER ON is required (auth.MenuItems has a filtered index).
--   * PART A is a FULL SYNC for the 12 managed non-admin roles: it REMOVES any
--     grant not in the intended list and adds any missing one. Admin receives
--     EVERY permission and is never trimmed. If operators have hand-granted extra
--     permissions to a managed role via /admin/roles, those extras will be removed.
--   * Run once against each target DB (UAT, then PROD). Review the row-count
--     summary printed at the end against the expected numbers in the comments.
-- =============================================================================

SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

-- =============================================================================
-- PART A -- Role -> Permission grants (full sync)
--   Expected final counts: Admin = ALL permissions (134 today; A1 keeps it complete
--   even if new permission rows exist), MeetingSecretary 2, IntAdmin 40, ExtAdmin 18,
--   RequestMaker 17, RequestChecker 7, IntAppraisalStaff 30, IntAppraisalChecker 21,
--   IntAppraisalVerifier 20, ExtAppraisalStaff 22, ExtAppraisalChecker 19,
--   ExtAppraisalVerifier 16, AppraisalCommittee 21.
-- =============================================================================
DECLARE @Grant TABLE (RoleName NVARCHAR(256), PermissionCode NVARCHAR(450));
INSERT INTO @Grant (RoleName, PermissionCode) VALUES
    (N'Admin', N'APPOINTMENT_APPROVAL_CONFIG'),
    (N'Admin', N'APPRAISAL_360_VIEW'),
    (N'Admin', N'APPRAISAL_ADMINISTRATION_EDIT'),
    (N'Admin', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'Admin', N'APPRAISAL_APPOINTMENT_EDIT'),
    (N'Admin', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'Admin', N'APPRAISAL_BLOCK_CONDO_EDIT'),
    (N'Admin', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'Admin', N'APPRAISAL_BLOCK_VILLAGE_EDIT'),
    (N'Admin', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'Admin', N'APPRAISAL_CREATE'),
    (N'Admin', N'APPRAISAL_DELETE'),
    (N'Admin', N'APPRAISAL_DOCUMENTS_EDIT'),
    (N'Admin', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'Admin', N'APPRAISAL_EDIT'),
    (N'Admin', N'APPRAISAL_PROPERTY_EDIT'),
    (N'Admin', N'APPRAISAL_PROPERTY_PMA_EDIT'),
    (N'Admin', N'APPRAISAL_PROPERTY_PMA_VIEW'),
    (N'Admin', N'APPRAISAL_PROPERTY_VIEW'),
    (N'Admin', N'APPRAISAL_REQUEST_EDIT'),
    (N'Admin', N'APPRAISAL_REQUEST_VIEW'),
    (N'Admin', N'APPRAISAL_REVIEW'),
    (N'Admin', N'APPRAISAL_SUMMARY_EDIT'),
    (N'Admin', N'APPRAISAL_SUMMARY_VIEW'),
    (N'Admin', N'APPRAISAL_VIEW'),
    (N'Admin', N'AUTH_AUDIT_VIEW'),
    (N'Admin', N'BLOCK_REAPPRAISAL_CREATE'),
    (N'Admin', N'BLOCK_REAPPRAISAL_VIEW'),
    (N'Admin', N'BLOCK_UNIT_MAINT_EDIT'),
    (N'Admin', N'BLOCK_UNIT_MAINT_VIEW'),
    (N'Admin', N'COLLATERAL_ADMIN'),
    (N'Admin', N'COMMITTEE_MEMBER'),
    (N'Admin', N'COMPANY_MANAGE'),
    (N'Admin', N'DASHBOARD_VIEW'),
    (N'Admin', N'EVALUATION_CONFIG_MANAGE'),
    (N'Admin', N'FEE_APPROVAL_CONFIG'),
    (N'Admin', N'GROUP_MANAGE'),
    (N'Admin', N'HISTORY_SEARCH_VIEW'),
    (N'Admin', N'INVOICE_APPROVE'),
    (N'Admin', N'INVOICE_CREATE'),
    (N'Admin', N'INVOICE_EXT_VIEW'),
    (N'Admin', N'INVOICE_VIEW'),
    (N'Admin', N'LOGS_VIEW'),
    (N'Admin', N'MEETING_ADMIN'),
    (N'Admin', N'MEETING_MANAGE'),
    (N'Admin', N'MEETING_SECRETARY'),
    (N'Admin', N'MENU_MANAGE'),
    (N'Admin', N'MONITORING:MEETING_FOLLOWUP'),
    (N'Admin', N'MONITORING:PENDING_EVALUATION'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:ADMIN'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:ADMIN:TEAM'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:CHECKER'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:CHECKER:TEAM'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:STAFF'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:STAFF:TEAM'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:VERIFIER'),
    (N'Admin', N'MONITORING:PENDING_EXTERNAL:VERIFIER:TEAM'),
    (N'Admin', N'MONITORING:PENDING_FOLLOWUP'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:ADMIN'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:ADMIN:TEAM'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:APPROVER'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:APPROVER:TEAM'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:CHECKER'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:CHECKER:TEAM'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:STAFF'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:STAFF:TEAM'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:VERIFIER'),
    (N'Admin', N'MONITORING:PENDING_INTERNAL:VERIFIER:TEAM'),
    (N'Admin', N'MONITORING:PENDING_QUOTATION'),
    (N'Admin', N'OAUTH_CLIENTS_MANAGE'),
    (N'Admin', N'OAUTH_SCOPES_MANAGE'),
    (N'Admin', N'OAUTH_TOKENS_REVOKE'),
    (N'Admin', N'PARAMETER_MANAGE'),
    (N'Admin', N'PASSWORD_POLICY_MANAGE'),
    (N'Admin', N'PERMISSION_MANAGE'),
    (N'Admin', N'QUOTATION_DRAFT_EDIT'),
    (N'Admin', N'QUOTATION_DRAFT_VIEW'),
    (N'Admin', N'QUOTATION_EXT_VIEW'),
    (N'Admin', N'QUOTATION_VIEW'),
    (N'Admin', N'REAPPRAISAL_GENERATE_TEST_FILE'),
    (N'Admin', N'REAPPRAISAL_VIEW'),
    (N'Admin', N'REPORT_EVALUATION_VIEW'),
    (N'Admin', N'REPORT_OP_VIEW'),
    (N'Admin', N'REPORT_STATISTICS_VIEW'),
    (N'Admin', N'REPORT_VIEW'),
    (N'Admin', N'REQUEST_CREATE'),
    (N'Admin', N'REQUEST_VIEW'),
    (N'Admin', N'ROLE_MANAGE'),
    (N'Admin', N'SLA_CONFIG_MANAGE'),
    (N'Admin', N'STANDALONE_USE'),
    (N'Admin', N'SUPPORTING_DATA_MAINT_DECISION'),
    (N'Admin', N'SUPPORTING_DATA_MAINT_EDIT'),
    (N'Admin', N'SUPPORTING_DATA_MAINT_REMOVE'),
    (N'Admin', N'SUPPORTING_DATA_MAINT_VIEW'),
    (N'Admin', N'TASK_APPR_ASSIGNMENT'),
    (N'Admin', N'TASK_APPR_BOOK_VERIFICATION'),
    (N'Admin', N'TASK_APPR_INITIATION'),
    (N'Admin', N'TASK_APPR_INITIATION_CHECK'),
    (N'Admin', N'TASK_EXT_APPR_ASSIGNMENT'),
    (N'Admin', N'TASK_EXT_APPR_CHECK'),
    (N'Admin', N'TASK_EXT_APPR_EXECUTION'),
    (N'Admin', N'TASK_EXT_APPR_VERIFICATION'),
    (N'Admin', N'TASK_FEE_APPOINTMENT_APPROVAL'),
    (N'Admin', N'TASK_INT_APPR_CHECK'),
    (N'Admin', N'TASK_INT_APPR_EXECUTION'),
    (N'Admin', N'TASK_INT_APPR_VERIFICATION'),
    (N'Admin', N'TASK_INT_OFFLINE_BOOK_KEYIN'),
    (N'Admin', N'TASK_INT_PMA_INPUT'),
    (N'Admin', N'TASK_LIST_VIEW'),
    (N'Admin', N'TASK_MONITOR_REASSIGN'),
    (N'Admin', N'TASK_MONITOR_REASSIGN:TEAM'),
    (N'Admin', N'TASK_MONITOR_VIEW'),
    (N'Admin', N'TASK_MONITOR_VIEW:TEAM'),
    (N'Admin', N'TASK_PENDING_APPROVAL'),
    (N'Admin', N'TASK_PROVIDE_ADDITIONAL_DOCS'),
    (N'Admin', N'TASK_QUOTATION_FINALIZE'),
    (N'Admin', N'TASK_QUOTATION_NEGOTIATE'),
    (N'Admin', N'TASK_QUOTATION_PICK_WINNER'),
    (N'Admin', N'TASK_QUOTATION_REVIEW'),
    (N'Admin', N'TASK_QUOTATION_SUBMIT'),
    (N'Admin', N'TEAM_MANAGE'),
    (N'Admin', N'TEMPLATE_MANAGE'),
    (N'Admin', N'USER_CHANGE_PASSWORD'),
    (N'Admin', N'USER_MANAGE'),
    (N'Admin', N'USER_RESET_PASSWORD'),
    (N'Admin', N'WEBHOOK_DELIVERIES_RETRY'),
    (N'Admin', N'WEBHOOK_DELIVERIES_VIEW'),
    (N'Admin', N'WEBHOOK_SUBSCRIPTIONS_MANAGE'),
    (N'Admin', N'WORKFLOW_ADMIN'),
    (N'Admin', N'WORKFLOW_MANAGE'),
    (N'AppraisalCommittee', N'APPRAISAL_360_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_PROPERTY_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_REQUEST_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_REVIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_SUMMARY_EDIT'),
    (N'AppraisalCommittee', N'APPRAISAL_SUMMARY_VIEW'),
    (N'AppraisalCommittee', N'APPRAISAL_VIEW'),
    (N'AppraisalCommittee', N'COMMITTEE_MEMBER'),
    (N'AppraisalCommittee', N'DASHBOARD_VIEW'),
    (N'AppraisalCommittee', N'MEETING_MANAGE'),
    (N'AppraisalCommittee', N'REPORT_EVALUATION_VIEW'),
    (N'AppraisalCommittee', N'REPORT_STATISTICS_VIEW'),
    (N'AppraisalCommittee', N'REPORT_VIEW'),
    (N'AppraisalCommittee', N'STANDALONE_USE'),
    (N'AppraisalCommittee', N'TASK_LIST_VIEW'),
    (N'AppraisalCommittee', N'TASK_PENDING_APPROVAL'),
    (N'ExtAdmin', N'APPRAISAL_APPOINTMENT_EDIT'),
    (N'ExtAdmin', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'ExtAdmin', N'APPRAISAL_REQUEST_VIEW'),
    (N'ExtAdmin', N'APPRAISAL_SUMMARY_EDIT'),
    (N'ExtAdmin', N'APPRAISAL_SUMMARY_VIEW'),
    (N'ExtAdmin', N'APPRAISAL_VIEW'),
    (N'ExtAdmin', N'DASHBOARD_VIEW'),
    (N'ExtAdmin', N'INVOICE_CREATE'),
    (N'ExtAdmin', N'INVOICE_EXT_VIEW'),
    (N'ExtAdmin', N'QUOTATION_EXT_VIEW'),
    (N'ExtAdmin', N'REQUEST_VIEW'),
    (N'ExtAdmin', N'TASK_EXT_APPR_ASSIGNMENT'),
    (N'ExtAdmin', N'TASK_LIST_VIEW'),
    (N'ExtAdmin', N'TASK_MONITOR_REASSIGN:TEAM'),
    (N'ExtAdmin', N'TASK_MONITOR_VIEW:TEAM'),
    (N'ExtAdmin', N'TASK_QUOTATION_NEGOTIATE'),
    (N'ExtAdmin', N'TASK_QUOTATION_SUBMIT'),
    (N'ExtAdmin', N'USER_MANAGE'),
    (N'ExtAppraisalChecker', N'APPRAISAL_360_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_PROPERTY_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_REQUEST_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_REVIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_SUMMARY_EDIT'),
    (N'ExtAppraisalChecker', N'APPRAISAL_SUMMARY_VIEW'),
    (N'ExtAppraisalChecker', N'APPRAISAL_VIEW'),
    (N'ExtAppraisalChecker', N'DASHBOARD_VIEW'),
    (N'ExtAppraisalChecker', N'HISTORY_SEARCH_VIEW'),
    (N'ExtAppraisalChecker', N'QUOTATION_EXT_VIEW'),
    (N'ExtAppraisalChecker', N'STANDALONE_USE'),
    (N'ExtAppraisalChecker', N'TASK_EXT_APPR_CHECK'),
    (N'ExtAppraisalChecker', N'TASK_LIST_VIEW'),
    (N'ExtAppraisalChecker', N'TASK_QUOTATION_NEGOTIATE'),
    (N'ExtAppraisalChecker', N'TASK_QUOTATION_SUBMIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_360_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_APPOINTMENT_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_BLOCK_CONDO_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_BLOCK_VILLAGE_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_DOCUMENTS_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_PROPERTY_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_PROPERTY_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_REQUEST_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_SUMMARY_EDIT'),
    (N'ExtAppraisalStaff', N'APPRAISAL_SUMMARY_VIEW'),
    (N'ExtAppraisalStaff', N'APPRAISAL_VIEW'),
    (N'ExtAppraisalStaff', N'DASHBOARD_VIEW'),
    (N'ExtAppraisalStaff', N'HISTORY_SEARCH_VIEW'),
    (N'ExtAppraisalStaff', N'STANDALONE_USE'),
    (N'ExtAppraisalStaff', N'TASK_EXT_APPR_ASSIGNMENT'),
    (N'ExtAppraisalStaff', N'TASK_EXT_APPR_EXECUTION'),
    (N'ExtAppraisalStaff', N'TASK_LIST_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_360_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_PROPERTY_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_REQUEST_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_REVIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_SUMMARY_EDIT'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_SUMMARY_VIEW'),
    (N'ExtAppraisalVerifier', N'APPRAISAL_VIEW'),
    (N'ExtAppraisalVerifier', N'DASHBOARD_VIEW'),
    (N'ExtAppraisalVerifier', N'HISTORY_SEARCH_VIEW'),
    (N'ExtAppraisalVerifier', N'STANDALONE_USE'),
    (N'ExtAppraisalVerifier', N'TASK_EXT_APPR_VERIFICATION'),
    (N'ExtAppraisalVerifier', N'TASK_LIST_VIEW'),
    (N'IntAdmin', N'APPOINTMENT_APPROVAL_CONFIG'),
    (N'IntAdmin', N'APPRAISAL_ADMINISTRATION_EDIT'),
    (N'IntAdmin', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'IntAdmin', N'APPRAISAL_REQUEST_VIEW'),
    (N'IntAdmin', N'APPRAISAL_REVIEW'),
    (N'IntAdmin', N'APPRAISAL_SUMMARY_EDIT'),
    (N'IntAdmin', N'APPRAISAL_SUMMARY_VIEW'),
    (N'IntAdmin', N'APPRAISAL_VIEW'),
    (N'IntAdmin', N'BLOCK_REAPPRAISAL_CREATE'),
    (N'IntAdmin', N'BLOCK_REAPPRAISAL_VIEW'),
    (N'IntAdmin', N'BLOCK_UNIT_MAINT_EDIT'),
    (N'IntAdmin', N'BLOCK_UNIT_MAINT_VIEW'),
    (N'IntAdmin', N'COLLATERAL_ADMIN'),
    (N'IntAdmin', N'DASHBOARD_VIEW'),
    (N'IntAdmin', N'EVALUATION_CONFIG_MANAGE'),
    (N'IntAdmin', N'FEE_APPROVAL_CONFIG'),
    (N'IntAdmin', N'INVOICE_APPROVE'),
    (N'IntAdmin', N'INVOICE_VIEW'),
    (N'IntAdmin', N'MEETING_ADMIN'),
    (N'IntAdmin', N'MEETING_MANAGE'),
    (N'IntAdmin', N'QUOTATION_DRAFT_EDIT'),
    (N'IntAdmin', N'QUOTATION_DRAFT_VIEW'),
    (N'IntAdmin', N'QUOTATION_VIEW'),
    (N'IntAdmin', N'REAPPRAISAL_VIEW'),
    (N'IntAdmin', N'REPORT_EVALUATION_VIEW'),
    (N'IntAdmin', N'REPORT_OP_VIEW'),
    (N'IntAdmin', N'REPORT_STATISTICS_VIEW'),
    (N'IntAdmin', N'REPORT_VIEW'),
    (N'IntAdmin', N'REQUEST_VIEW'),
    (N'IntAdmin', N'REQUEST_CREATE'),
    (N'IntAdmin', N'SLA_CONFIG_MANAGE'),
    (N'IntAdmin', N'STANDALONE_USE'),
    (N'IntAdmin', N'TASK_APPR_ASSIGNMENT'),
    (N'IntAdmin', N'TASK_FEE_APPOINTMENT_APPROVAL'),
    (N'IntAdmin', N'TASK_LIST_VIEW'),
    (N'IntAdmin', N'TASK_MONITOR_REASSIGN'),
    (N'IntAdmin', N'TASK_MONITOR_VIEW'),
    (N'IntAdmin', N'USER_MANAGE'),
    (N'IntAdmin', N'WORKFLOW_ADMIN'),
    (N'IntAdmin', N'WORKFLOW_MANAGE'),
    (N'IntAppraisalChecker', N'APPRAISAL_360_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_DOCUMENTS_EDIT'),
    (N'IntAppraisalChecker', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_PROPERTY_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_REQUEST_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_REVIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_SUMMARY_EDIT'),
    (N'IntAppraisalChecker', N'APPRAISAL_SUMMARY_VIEW'),
    (N'IntAppraisalChecker', N'APPRAISAL_VIEW'),
    (N'IntAppraisalChecker', N'DASHBOARD_VIEW'),
    (N'IntAppraisalChecker', N'HISTORY_SEARCH_VIEW'),
    (N'IntAppraisalChecker', N'STANDALONE_USE'),
    (N'IntAppraisalChecker', N'SUPPORTING_DATA_MAINT_DECISION'),
    (N'IntAppraisalChecker', N'SUPPORTING_DATA_MAINT_VIEW'),
    (N'IntAppraisalChecker', N'TASK_FEE_APPOINTMENT_APPROVAL'),
    (N'IntAppraisalChecker', N'TASK_INT_APPR_CHECK'),
    (N'IntAppraisalChecker', N'TASK_LIST_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_360_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_APPOINTMENT_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_BLOCK_CONDO_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_BLOCK_VILLAGE_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_DOCUMENTS_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_PROPERTY_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_PROPERTY_PMA_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_PROPERTY_PMA_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_PROPERTY_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_REQUEST_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_SUMMARY_EDIT'),
    (N'IntAppraisalStaff', N'APPRAISAL_SUMMARY_VIEW'),
    (N'IntAppraisalStaff', N'APPRAISAL_VIEW'),
    (N'IntAppraisalStaff', N'DASHBOARD_VIEW'),
    (N'IntAppraisalStaff', N'HISTORY_SEARCH_VIEW'),
    (N'IntAppraisalStaff', N'STANDALONE_USE'),
    (N'IntAppraisalStaff', N'SUPPORTING_DATA_MAINT_EDIT'),
    (N'IntAppraisalStaff', N'SUPPORTING_DATA_MAINT_REMOVE'),
    (N'IntAppraisalStaff', N'SUPPORTING_DATA_MAINT_VIEW'),
    (N'IntAppraisalStaff', N'TASK_APPR_BOOK_VERIFICATION'),
    (N'IntAppraisalStaff', N'TASK_INT_APPR_EXECUTION'),
    (N'IntAppraisalStaff', N'TASK_INT_OFFLINE_BOOK_KEYIN'),
    (N'IntAppraisalStaff', N'TASK_INT_PMA_INPUT'),
    (N'IntAppraisalStaff', N'TASK_LIST_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_360_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_ADMINISTRATION_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_APPOINTMENT_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_BLOCK_CONDO_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_BLOCK_VILLAGE_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_DOCUMENTS_EDIT'),
    (N'IntAppraisalVerifier', N'APPRAISAL_DOCUMENTS_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_PROPERTY_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_REQUEST_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_REVIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_SUMMARY_EDIT'),
    (N'IntAppraisalVerifier', N'APPRAISAL_SUMMARY_VIEW'),
    (N'IntAppraisalVerifier', N'APPRAISAL_VIEW'),
    (N'IntAppraisalVerifier', N'DASHBOARD_VIEW'),
    (N'IntAppraisalVerifier', N'HISTORY_SEARCH_VIEW'),
    (N'IntAppraisalVerifier', N'REPORT_EVALUATION_VIEW'),
    (N'IntAppraisalVerifier', N'REPORT_VIEW'),
    (N'IntAppraisalVerifier', N'STANDALONE_USE'),
    (N'IntAppraisalVerifier', N'TASK_INT_APPR_VERIFICATION'),
    (N'IntAppraisalVerifier', N'TASK_LIST_VIEW'),
    (N'MeetingSecretary', N'MEETING_MANAGE'),
    (N'MeetingSecretary', N'MEETING_SECRETARY'),
    (N'RequestChecker', N'APPRAISAL_REQUEST_VIEW'),
    (N'RequestChecker', N'APPRAISAL_SUMMARY_EDIT'),
    (N'RequestChecker', N'APPRAISAL_SUMMARY_VIEW'),
    (N'RequestChecker', N'DASHBOARD_VIEW'),
    (N'RequestChecker', N'REQUEST_VIEW'),
    (N'RequestChecker', N'TASK_APPR_INITIATION_CHECK'),
    (N'RequestChecker', N'TASK_LIST_VIEW'),
    (N'RequestMaker', N'APPRAISAL_REQUEST_EDIT'),
    (N'RequestMaker', N'APPRAISAL_REQUEST_VIEW'),
    (N'RequestMaker', N'APPRAISAL_SUMMARY_EDIT'),
    (N'RequestMaker', N'APPRAISAL_SUMMARY_VIEW'),
    (N'RequestMaker', N'BLOCK_REAPPRAISAL_CREATE'),
    (N'RequestMaker', N'BLOCK_REAPPRAISAL_VIEW'),
    (N'RequestMaker', N'DASHBOARD_VIEW'),
    (N'RequestMaker', N'QUOTATION_VIEW'),
    (N'RequestMaker', N'REAPPRAISAL_VIEW'),
    (N'RequestMaker', N'REQUEST_CREATE'),
    (N'RequestMaker', N'REQUEST_VIEW'),
    (N'RequestMaker', N'STANDALONE_USE'),
    (N'RequestMaker', N'TASK_APPR_INITIATION'),
    (N'RequestMaker', N'TASK_APPR_INITIATION_CHECK'),
    (N'RequestMaker', N'TASK_LIST_VIEW'),
    (N'RequestMaker', N'TASK_PROVIDE_ADDITIONAL_DOCS'),
    (N'RequestMaker', N'TASK_QUOTATION_PICK_WINNER');

-- A1. Admin = every permission that exists (never removed).
INSERT INTO auth.RolePermissions (RoleId, PermissionId)
SELECT r.Id, p.PermissionId
FROM auth.AspNetRoles r
CROSS JOIN auth.Permissions p
WHERE r.Name = N'Admin'
  AND NOT EXISTS (SELECT 1 FROM auth.RolePermissions rp
                  WHERE rp.RoleId = r.Id AND rp.PermissionId = p.PermissionId);

-- A2. Remove grants no longer intended (managed non-admin roles only).
DELETE rp
FROM auth.RolePermissions rp
JOIN auth.AspNetRoles r ON r.Id = rp.RoleId
JOIN auth.Permissions  p ON p.PermissionId = rp.PermissionId
WHERE r.Name IN ('MeetingSecretary','IntAdmin','ExtAdmin','RequestMaker','RequestChecker',
                     'IntAppraisalStaff','IntAppraisalChecker','IntAppraisalVerifier',
                     'ExtAppraisalStaff','ExtAppraisalChecker','ExtAppraisalVerifier','AppraisalCommittee')
  AND NOT EXISTS (SELECT 1 FROM @Grant g
                  WHERE g.RoleName = r.Name AND g.PermissionCode = p.PermissionCode);

-- A3. Add any missing intended grants (all listed roles).
INSERT INTO auth.RolePermissions (RoleId, PermissionId)
SELECT r.Id, p.PermissionId
FROM @Grant g
JOIN auth.AspNetRoles r ON r.Name = g.RoleName
JOIN auth.Permissions  p ON p.PermissionCode = g.PermissionCode
WHERE NOT EXISTS (SELECT 1 FROM auth.RolePermissions rp
                  WHERE rp.RoleId = r.Id AND rp.PermissionId = p.PermissionId);

-- =============================================================================
-- PART B -- Appraisal action-tab edit gates (auth.MenuItems.EditPermissionCode)
--   These tabs become editable only for the role holding the matching task perm.
-- =============================================================================
UPDATE auth.MenuItems SET EditPermissionCode = N'TASK_FEE_APPOINTMENT_APPROVAL' WHERE ItemKey = N'appraisal.fee-appointment-approval';
UPDATE auth.MenuItems SET EditPermissionCode = N'TASK_QUOTATION_SUBMIT'         WHERE ItemKey = N'appraisal.quotation-submit';
UPDATE auth.MenuItems SET EditPermissionCode = N'TASK_QUOTATION_NEGOTIATE'      WHERE ItemKey = N'appraisal.quotation-respond-negotiation';
UPDATE auth.MenuItems SET EditPermissionCode = N'TASK_QUOTATION_PICK_WINNER'    WHERE ItemKey = N'appraisal.quotation-pick-winner';
UPDATE auth.MenuItems SET EditPermissionCode = N'TASK_PROVIDE_ADDITIONAL_DOCS'  WHERE ItemKey = N'appraisal.document-followup';

-- =============================================================================
-- PART C -- Activity menu overrides (full authoritative reset: 115 rows)
--   Overrides only RESTRICT (hide / force read-only) while on a given activity.
--   Cleared and reinserted so the table exactly matches the intended seed.
-- =============================================================================
DECLARE @Ov TABLE (ActivityId NVARCHAR(100), ItemKey NVARCHAR(200), IsVisible BIT, CanEdit BIT);
INSERT INTO @Ov (ActivityId, ItemKey, IsVisible, CanEdit) VALUES
    (N'appraisal-assignment', N'appraisal.fee-appointment-approval', 0, 0),
    (N'appraisal-book-verification', N'appraisal.appointment', 1, 0),
    (N'appraisal-book-verification', N'appraisal.block-condo', 1, 0),
    (N'appraisal-book-verification', N'appraisal.block-village', 1, 0),
    (N'appraisal-book-verification', N'appraisal.property', 1, 0),
    (N'appraisal-book-verification', N'appraisal.property-pma', 0, 0),
    (N'appraisal-initiation', N'appraisal.360', 1, 0),
    (N'appraisal-initiation', N'appraisal.administration', 0, 0),
    (N'appraisal-initiation', N'appraisal.document-followup', 0, 0),
    (N'appraisal-initiation', N'appraisal.quotation-pick-winner', 0, 0),
    (N'appraisal-initiation-check', N'appraisal.document-followup', 0, 0),
    (N'appraisal-initiation-check', N'appraisal.quotation-pick-winner', 0, 0),
    (N'appraisal-initiation-check', N'appraisal.request', 1, 0),
    (N'ext-appraisal-assignment', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'ext-appraisal-assignment', N'appraisal.quotation-submit', 0, 0),
    (N'ext-appraisal-check', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'ext-appraisal-check', N'appraisal.quotation-submit', 0, 0),
    (N'ext-collect-submissions', N'appraisal.360', 0, 0),
    (N'ext-collect-submissions', N'appraisal.administration', 0, 0),
    (N'ext-collect-submissions', N'appraisal.appointment', 0, 0),
    (N'ext-collect-submissions', N'appraisal.block-condo', 0, 0),
    (N'ext-collect-submissions', N'appraisal.block-village', 0, 0),
    (N'ext-collect-submissions', N'appraisal.document-followup', 0, 0),
    (N'ext-collect-submissions', N'appraisal.documents', 0, 0),
    (N'ext-collect-submissions', N'appraisal.fee-appointment-approval', 0, 0),
    (N'ext-collect-submissions', N'appraisal.property', 0, 0),
    (N'ext-collect-submissions', N'appraisal.property-pma', 0, 0),
    (N'ext-collect-submissions', N'appraisal.quotation-finalize', 0, 0),
    (N'ext-collect-submissions', N'appraisal.quotation-pick-winner', 0, 0),
    (N'ext-collect-submissions', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'ext-collect-submissions', N'appraisal.quotation-review', 0, 0),
    (N'ext-collect-submissions', N'appraisal.request', 1, 0),
    (N'ext-collect-submissions', N'appraisal.summary', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.360', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.administration', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.appointment', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.block-condo', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.block-village', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.document-followup', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.documents', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.fee-appointment-approval', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.property', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.property-pma', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.quotation-finalize', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.quotation-pick-winner', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.quotation-review', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.quotation-submit', 0, 0),
    (N'ext-respond-negotiation', N'appraisal.request', 1, 0),
    (N'ext-respond-negotiation', N'appraisal.summary', 0, 0),
    (N'fee-appointment-approval', N'appraisal.360', 0, 0),
    (N'fee-appointment-approval', N'appraisal.administration', 0, 0),
    (N'fee-appointment-approval', N'appraisal.appointment', 0, 0),
    (N'fee-appointment-approval', N'appraisal.block-condo', 0, 0),
    (N'fee-appointment-approval', N'appraisal.block-village', 0, 0),
    (N'fee-appointment-approval', N'appraisal.document-followup', 0, 0),
    (N'fee-appointment-approval', N'appraisal.documents', 0, 0),
    (N'fee-appointment-approval', N'appraisal.property', 0, 0),
    (N'fee-appointment-approval', N'appraisal.property-pma', 0, 0),
    (N'fee-appointment-approval', N'appraisal.quotation-finalize', 0, 0),
    (N'fee-appointment-approval', N'appraisal.quotation-pick-winner', 0, 0),
    (N'fee-appointment-approval', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'fee-appointment-approval', N'appraisal.quotation-review', 0, 0),
    (N'fee-appointment-approval', N'appraisal.quotation-submit', 0, 0),
    (N'fee-appointment-approval', N'appraisal.request', 1, 0),
    (N'fee-appointment-approval', N'appraisal.summary', 0, 0),
    (N'int-appraisal-check', N'appraisal.fee-appointment-approval', 0, 0),
    (N'int-appraisal-execution', N'appraisal.property-pma', 0, 0),
    (N'int-offline-book-keyin', N'appraisal.property-pma', 0, 0),
    (N'int-pma-input', N'appraisal.360', 0, 0),
    (N'int-pma-input', N'appraisal.administration', 0, 0),
    (N'int-pma-input', N'appraisal.appointment', 0, 0),
    (N'int-pma-input', N'appraisal.block-condo', 0, 0),
    (N'int-pma-input', N'appraisal.block-village', 0, 0),
    (N'int-pma-input', N'appraisal.document-followup', 0, 0),
    (N'int-pma-input', N'appraisal.documents', 0, 0),
    (N'int-pma-input', N'appraisal.fee-appointment-approval', 0, 0),
    (N'int-pma-input', N'appraisal.property', 0, 0),
    (N'int-pma-input', N'appraisal.quotation-finalize', 0, 0),
    (N'int-pma-input', N'appraisal.quotation-pick-winner', 0, 0),
    (N'int-pma-input', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'int-pma-input', N'appraisal.quotation-review', 0, 0),
    (N'int-pma-input', N'appraisal.quotation-submit', 0, 0),
    (N'int-pma-input', N'appraisal.request', 1, 0),
    (N'provide-additional-documents', N'appraisal.360', 0, 0),
    (N'provide-additional-documents', N'appraisal.administration', 0, 0),
    (N'provide-additional-documents', N'appraisal.appointment', 0, 0),
    (N'provide-additional-documents', N'appraisal.block-condo', 0, 0),
    (N'provide-additional-documents', N'appraisal.block-village', 0, 0),
    (N'provide-additional-documents', N'appraisal.documents', 0, 0),
    (N'provide-additional-documents', N'appraisal.fee-appointment-approval', 0, 0),
    (N'provide-additional-documents', N'appraisal.property', 0, 0),
    (N'provide-additional-documents', N'appraisal.property-pma', 0, 0),
    (N'provide-additional-documents', N'appraisal.quotation-finalize', 0, 0),
    (N'provide-additional-documents', N'appraisal.quotation-pick-winner', 0, 0),
    (N'provide-additional-documents', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'provide-additional-documents', N'appraisal.quotation-review', 0, 0),
    (N'provide-additional-documents', N'appraisal.quotation-submit', 0, 0),
    (N'provide-additional-documents', N'appraisal.request', 1, 0),
    (N'provide-additional-documents', N'appraisal.summary', 0, 0),
    (N'rm-pick-winner', N'appraisal.360', 0, 0),
    (N'rm-pick-winner', N'appraisal.administration', 0, 0),
    (N'rm-pick-winner', N'appraisal.appointment', 0, 0),
    (N'rm-pick-winner', N'appraisal.block-condo', 0, 0),
    (N'rm-pick-winner', N'appraisal.block-village', 0, 0),
    (N'rm-pick-winner', N'appraisal.document-followup', 0, 0),
    (N'rm-pick-winner', N'appraisal.documents', 0, 0),
    (N'rm-pick-winner', N'appraisal.fee-appointment-approval', 0, 0),
    (N'rm-pick-winner', N'appraisal.property', 0, 0),
    (N'rm-pick-winner', N'appraisal.property-pma', 0, 0),
    (N'rm-pick-winner', N'appraisal.quotation-finalize', 0, 0),
    (N'rm-pick-winner', N'appraisal.quotation-respond-negotiation', 0, 0),
    (N'rm-pick-winner', N'appraisal.quotation-review', 0, 0),
    (N'rm-pick-winner', N'appraisal.quotation-submit', 0, 0),
    (N'rm-pick-winner', N'appraisal.request', 1, 0),
    (N'rm-pick-winner', N'appraisal.summary', 0, 0);

DELETE FROM auth.ActivityMenuOverrides;

INSERT INTO auth.ActivityMenuOverrides (ActivityMenuOverrideId, ActivityId, MenuItemId, IsVisible, CanEdit)
SELECT NEWID(), o.ActivityId, m.MenuItemId, o.IsVisible, o.CanEdit
FROM @Ov o
JOIN auth.MenuItems m ON m.ItemKey = o.ItemKey;

-- Guard: every override ItemKey must resolve to a MenuItem, or we lost rows.
IF (SELECT COUNT(*) FROM @Ov) <> (SELECT COUNT(*) FROM auth.ActivityMenuOverrides)
BEGIN
    RAISERROR('Activity override count mismatch - an ItemKey did not resolve to a MenuItem. Rolling back.', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END

COMMIT TRANSACTION;

-- =============================================================================
-- VERIFICATION (read-only) -- compare against the expected numbers above.
-- =============================================================================
SELECT r.Name AS Role, COUNT(*) AS Permissions
FROM auth.RolePermissions rp JOIN auth.AspNetRoles r ON r.Id = rp.RoleId
GROUP BY r.Name ORDER BY r.Name;

SELECT ItemKey, EditPermissionCode
FROM auth.MenuItems
WHERE ItemKey IN (N'appraisal.fee-appointment-approval', N'appraisal.quotation-submit',
                  N'appraisal.quotation-respond-negotiation', N'appraisal.quotation-pick-winner',
                  N'appraisal.document-followup')
ORDER BY ItemKey;

SELECT ActivityId, COUNT(*) AS OverrideRows
FROM auth.ActivityMenuOverrides GROUP BY ActivityId ORDER BY ActivityId;
