-- =============================================================================
--  PATCH USER DEPARTMENTS   (from '.claude/docs/fix user department.xlsx', 2026-08-01)
--  Corrects auth.AspNetUsers.Department for bank users (Thai -> English names).
--  Idempotent: only updates rows whose Department actually differs; safe to re-run.
--  Matches users by NormalizedUserName. 1085 users in the fix file
--  (1,081 differ from the originally-loaded value; 4 already match).
--  Inserts are chunked at 900 rows (SQL Server caps VALUES at 1000 per INSERT).
-- =============================================================================

SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRANSACTION;

DECLARE @Fix TABLE (UserName NVARCHAR(256), Department NVARCHAR(100));

INSERT INTO @Fix (UserName, Department) VALUES
    (N'P5461', N'IT Security and IT Risk Management'),
    (N'P2560', N'Operation'),
    (N'P0236', N'Collateral Appraisal'),
    (N'P2248', N'Collateral Appraisal'),
    (N'P1977', N'Collateral Appraisal'),
    (N'P1990', N'Collateral Appraisal'),
    (N'P0994', N'Collateral Appraisal'),
    (N'P2405', N'Collateral Appraisal'),
    (N'P1906', N'Collateral Appraisal'),
    (N'P1163', N'Collateral Appraisal'),
    (N'P3069', N'Credit Management'),
    (N'P1561', N'Conglomerate Business'),
    (N'P3328', N'Credit Management'),
    (N'P2254', N'Credit Management'),
    (N'P3430', N'Credit Management'),
    (N'P4232', N'Collateral Appraisal'),
    (N'P4252', N'Collateral Appraisal'),
    (N'P0483', N'Credit Management'),
    (N'P4464', N'Credit Management'),
    (N'P0932', N'Credit Management'),
    (N'P1480', N'Credit Management'),
    (N'P1084', N'Credit Management'),
    (N'P4418', N'Collateral Appraisal'),
    (N'TENY003', N'สายงานตรวจสอบ'),
    (N'P4859', N'Collateral Appraisal'),
    (N'P4860', N'Credit Management'),
    (N'P4861', N'Credit Management'),
    (N'P4907', N'Credit Management'),
    (N'LOS', N'Credit Management'),
    (N'P0017', N'Retail Credit Underwriting'),
    (N'P1294', N'Retail Credit Underwriting'),
    (N'P0144', N'Retail Credit Underwriting'),
    (N'P0514', N'Retail Credit Underwriting'),
    (N'P4227', N'Credit Review'),
    (N'P4345', N'Credit Review'),
    (N'P4753', N'Credit Review'),
    (N'P5285', N'Corporate Business'),
    (N'P5286', N'Corporate Business'),
    (N'P2395', N'Corporate Business'),
    (N'P5219', N'Corporate Business'),
    (N'P2891', N'Credit Management'),
    (N'P5566', N'Retail Credit Underwriting'),
    (N'P3954', N'Metropolitan Business'),
    (N'P4078', N'International Business'),
    (N'P5361', N'Metropolitan Business'),
    (N'P5070', N'Metropolitan Business'),
    (N'P0668', N'Provincial Business'),
    (N'P5737', N'Saphankhwai Branch'),
    (N'P5606', N'Retail Lending Sales Team 3'),
    (N'P5863', N'Collateral Appraisal'),
    (N'P5475', N'Provincial Business'),
    (N'P5923', N'RL Operation Management'),
    (N'P5740', N'International Business'),
    (N'P5902', N'International Business'),
    (N'P5856', N'International Business'),
    (N'P5934', N'Central Salaya Branch'),
    (N'P5864', N'Retail Credit Underwriting'),
    (N'P5913', N'Retail Credit Underwriting'),
    (N'P5930', N'International Business'),
    (N'P5957', N'RL Operation Management'),
    (N'P1960', N'The Circle Ratchapruk Branch'),
    (N'P5708', N'Retail Credit Underwriting'),
    (N'P5971', N'RL Operation Management'),
    (N'P3806', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'P3827', N'Big C Bangna Branch'),
    (N'P4868', N'Lotus Srinakarin Branch'),
    (N'P3702', N'The Mall Thapra Branch'),
    (N'P3467', N'Big C Bangna Branch'),
    (N'P4093', N'Homepro Suvarnabhumi Branch'),
    (N'P3877', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'P1890', N'Homepro Suvarnabhumi Branch'),
    (N'P3719', N'Worachak Branch'),
    (N'P4867', N'Paradise Park Branch'),
    (N'P5181', N'Paradise Park Branch'),
    (N'P2103', N'Mega Bangna Branch'),
    (N'P0823', N'The Mall Bangkapi Branch'),
    (N'P1755', N'The Mall Bangkapi Branch'),
    (N'P2621', N'The Mall Bangkapi Branch'),
    (N'P5472', N'The Mall Bangkapi Branch'),
    (N'P1422', N'Lotus Rama 4 Branch'),
    (N'P4277', N'The Mall Ngamwongwan Branch'),
    (N'P4275', N'The Crystal Ekamai-Ramindra Branch'),
    (N'P2636', N'Fashion Island Branch'),
    (N'P0834', N'Fashion Island Branch'),
    (N'P4322', N'Fashion Island Branch'),
    (N'P4881', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'P4749', N'The Crystal Ekamai-Ramindra Branch'),
    (N'P2265', N'Administration'),
    (N'P3727', N'Saphankhwai Branch'),
    (N'P4122', N'The Mall Ngamwongwan Branch'),
    (N'P3074', N'Worachak Branch'),
    (N'P4574', N'Lotus North Ratchapruek Branch'),
    (N'P4315', N'Central Westgate Branch'),
    (N'P0351', N'Future Park Rangsit Branch'),
    (N'P5194', N'Ayutthaya City Park Branch'),
    (N'P6117', N'Central World Branch'),
    (N'P6157', N'Retail Credit Underwriting'),
    (N'P6170', N'RL Operation Management'),
    (N'P6196', N'The Old Siam Branch'),
    (N'P81153', N'Business Audit'),
    (N'P3341', N'Business Audit'),
    (N'P81165', N'Business Audit'),
    (N'P4219', N'Internal Audit Professional Practice Standards and Strategy'),
    (N'P4446', N'Business Audit'),
    (N'P81102', N'Business Audit'),
    (N'P6209', N'RL Operation Management'),
    (N'P6210', N'Retail Credit Underwriting'),
    (N'P6223', N'Central Westgate Branch'),
    (N'P6225', N'Retail Credit Underwriting'),
    (N'P5742', N'Corporate Business'),
    (N'P4989', N'Khonkaen Branch'),
    (N'P3068', N'Central KhonKaen Branch'),
    (N'P3653', N'Credit Management'),
    (N'P3890', N'Credit Management'),
    (N'P4970', N'UD Town Udonthani Branch'),
    (N'P5825', N'Central KhonKaen Branch'),
    (N'P3770', N'Central KhonKaen Branch'),
    (N'P6220', N'Homepro Roiet Branch'),
    (N'P2137', N'Ubon Ratchathani Branch'),
    (N'P5437', N'Homepro Chaiyaphum Branch'),
    (N'P6017', N'Homepro Roiet Branch'),
    (N'P6180', N'Homepro Chaiyaphum Branch'),
    (N'P3395', N'Homepro Surin Branch'),
    (N'P2041', N'Terminal 21 Korat Branch'),
    (N'P4921', N'Credit Management'),
    (N'P5984', N'Pak Chong Branch'),
    (N'P5851', N'Homepro Saraburi Branch'),
    (N'P2556', N'Homepro Saraburi Branch'),
    (N'P2863', N'Ayutthaya City Park Branch'),
    (N'P5774', N'Lotus Phuket Branch'),
    (N'P3615', N'Lotus Phuket Branch'),
    (N'P5281', N'Phuket Branch'),
    (N'P5315', N'Hat Yai Branch'),
    (N'P5134', N'Credit Management'),
    (N'P5620', N'Big C Hatyai 2 Branch'),
    (N'P5891', N'Big C Hatyai 2 Branch'),
    (N'P6048', N'Hat Yai Branch'),
    (N'P6198', N'Lotus Phuket Branch'),
    (N'P4844', N'Homepro Chumphon Branch'),
    (N'P5504', N'Homepro Chumphon Branch'),
    (N'P6200', N'Homepro Chumphon Branch'),
    (N'P3373', N'Nakhon Si Thammarat Branch'),
    (N'P4041', N'Credit Management'),
    (N'P4843', N'Nakhon Si Thammarat Branch'),
    (N'P4992', N'Nakhon Si Thammarat Branch'),
    (N'P3426', N'Patong Branch'),
    (N'P4576', N'Suratthani Branch'),
    (N'B001AHC2', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B001AHC3', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B001AHCS', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B001BM', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B001CSR', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B002AHC2', N'Big C Hangdong Branch'),
    (N'B002AHCS', N'Big C Hangdong Branch'),
    (N'B002BM', N'Big C Hangdong Branch'),
    (N'B002CSR', N'Big C Hangdong Branch'),
    (N'B002CSR2', N'Big C Hangdong Branch'),
    (N'B003AHC2', N'Talat Warorot Branch'),
    (N'B003AHCS', N'Talat Warorot Branch'),
    (N'B003BM', N'Talat Warorot Branch'),
    (N'B003CSR', N'Talat Warorot Branch'),
    (N'B003CSR2', N'Talat Warorot Branch'),
    (N'B004AHC2', N'Phitsanulok Branch'),
    (N'B004AHC3', N'Phitsanulok Branch'),
    (N'B004AHCS', N'Phitsanulok Branch'),
    (N'B004BM', N'Phitsanulok Branch'),
    (N'B004CSR', N'Phitsanulok Branch'),
    (N'B005AHCS', N'Nakhonsawan Branch'),
    (N'B005BM', N'Nakhonsawan Branch'),
    (N'B005CSR', N'Nakhonsawan Branch'),
    (N'B006AHC2', N'Chiangrai Branch'),
    (N'B006AHCS', N'Chiangrai Branch'),
    (N'B006BM', N'Chiangrai Branch'),
    (N'B201AHCS', N'Homepro Chonburi Branch'),
    (N'B201BM', N'Homepro Chonburi Branch'),
    (N'B201CSR', N'Homepro Chonburi Branch'),
    (N'B201HCS2', N'Homepro Chonburi Branch'),
    (N'B201HCSU', N'Homepro Chonburi Branch'),
    (N'B202AHC2', N'Sriracha Branch'),
    (N'B202AHCS', N'Sriracha Branch'),
    (N'B202BM', N'Sriracha Branch'),
    (N'B202CSR', N'Sriracha Branch'),
    (N'B202CSR2', N'Sriracha Branch'),
    (N'B202HCSU', N'Sriracha Branch'),
    (N'B202HCS2', N'Sriracha Branch'),
    (N'B203AHC2', N'Terminal 21 Pattaya Branch'),
    (N'B203AHCS', N'Terminal 21 Pattaya Branch'),
    (N'B203BM', N'Terminal 21 Pattaya Branch'),
    (N'B203CSR', N'Terminal 21 Pattaya Branch'),
    (N'B203CSR2', N'Terminal 21 Pattaya Branch'),
    (N'B203HCS2', N'Terminal 21 Pattaya Branch'),
    (N'B203HCSU', N'Terminal 21 Pattaya Branch'),
    (N'B204AHC2', N'Rayong Branch'),
    (N'B204AHCS', N'Rayong Branch'),
    (N'B204BM', N'Rayong Branch'),
    (N'B204CSR', N'Rayong Branch'),
    (N'B301AHC2', N'Hua Hin Branch'),
    (N'B301AHCS', N'Hua Hin Branch'),
    (N'B301BM', N'Hua Hin Branch'),
    (N'B301CSR', N'Hua Hin Branch'),
    (N'B301CSR2', N'Hua Hin Branch'),
    (N'B302AHC2', N'Nakhonpathom Branch'),
    (N'B302AHCS', N'Nakhonpathom Branch'),
    (N'B302BM', N'Nakhonpathom Branch'),
    (N'B302CSR', N'Nakhonpathom Branch'),
    (N'B302CSR2', N'Nakhonpathom Branch'),
    (N'B303AHC2', N'Kanchanaburi Branch'),
    (N'B303AHCS', N'Kanchanaburi Branch'),
    (N'B303BM', N'Kanchanaburi Branch'),
    (N'B303CSR', N'Kanchanaburi Branch'),
    (N'B303HCSU', N'Kanchanaburi Branch'),
    (N'B304AHC2', N'Central Salaya Branch'),
    (N'B304AHCS', N'Central Salaya Branch'),
    (N'B304BM', N'Central Salaya Branch'),
    (N'B304CSR', N'Central Salaya Branch'),
    (N'B304CSR2', N'Central Salaya Branch'),
    (N'B304HCS2', N'Central Salaya Branch'),
    (N'B304HCSU', N'Central Salaya Branch'),
    (N'B305AHC2', N'Homepro Saraburi Branch'),
    (N'B305AHCS', N'Homepro Saraburi Branch'),
    (N'B305BM', N'Homepro Saraburi Branch'),
    (N'B305CSR', N'Homepro Saraburi Branch'),
    (N'B305CSR2', N'Homepro Saraburi Branch'),
    (N'B305HCSU', N'Homepro Saraburi Branch'),
    (N'B309AHC2', N'Homepro Chachoengsao Branch'),
    (N'B501BM', N'The Mall Bangkhae Branch'),
    (N'B501CSR', N'The Mall Bangkhae Branch'),
    (N'B501CSR2', N'The Mall Bangkhae Branch'),
    (N'B501CSR3', N'The Mall Bangkhae Branch'),
    (N'B503AHC2', N'The Mall Bangkapi Branch'),
    (N'B503AHCS', N'The Mall Bangkapi Branch'),
    (N'B503BM', N'The Mall Bangkapi Branch'),
    (N'B503CSR', N'The Mall Bangkapi Branch'),
    (N'B504AHC2', N'The Old Siam Branch'),
    (N'B504AHCS', N'The Old Siam Branch'),
    (N'B504BM', N'The Old Siam Branch'),
    (N'B504CSR', N'The Old Siam Branch'),
    (N'B504CSR2', N'The Old Siam Branch'),
    (N'B505AHC2', N'Big C Bangna Branch'),
    (N'B505AHC3', N'Big C Bangna Branch'),
    (N'B505AHCS', N'Big C Bangna Branch'),
    (N'B505BM', N'Big C Bangna Branch'),
    (N'B505CSR', N'Big C Bangna Branch'),
    (N'B505CSR2', N'Big C Bangna Branch'),
    (N'B507AHC2', N'Central World Branch'),
    (N'B507AHC3', N'Central World Branch'),
    (N'B507AHCS', N'Central World Branch'),
    (N'B507BM', N'Central World Branch'),
    (N'B507CSR', N'Central World Branch'),
    (N'B507CSR2', N'Central World Branch'),
    (N'B507CSR3', N'Central World Branch'),
    (N'B509AHC2', N'Future Park Rangsit Branch'),
    (N'B509AHC3', N'Future Park Rangsit Branch'),
    (N'B509AHCS', N'Future Park Rangsit Branch'),
    (N'B509BM', N'Future Park Rangsit Branch'),
    (N'B509CSR', N'Future Park Rangsit Branch'),
    (N'B509CSR2', N'Future Park Rangsit Branch'),
    (N'B509CSR3', N'Future Park Rangsit Branch'),
    (N'B511AHC2', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B511AHC3', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B511AHCS', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B511BM', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B511CSR', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B511CSR2', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B512AHC2', N'The Mall Thapra Branch'),
    (N'B512AHCS', N'The Mall Thapra Branch'),
    (N'B512BM', N'The Mall Thapra Branch'),
    (N'B512CSR', N'The Mall Thapra Branch'),
    (N'B512CSR2', N'The Mall Thapra Branch'),
    (N'B512CSR3', N'The Mall Thapra Branch'),
    (N'B513AHC2', N'Yaowaraj Branch'),
    (N'B530AHC2', N'Samutsakhon Branch'),
    (N'B530AHCS', N'Samutsakhon Branch'),
    (N'B530BM', N'Samutsakhon Branch'),
    (N'B530CSR', N'Samutsakhon Branch'),
    (N'B530CSR2', N'Samutsakhon Branch'),
    (N'B530HCS2', N'Samutsakhon Branch'),
    (N'B530HCSU', N'Samutsakhon Branch'),
    (N'B532AHC2', N'Central Rama 9 Branch'),
    (N'B532AHCS', N'Central Rama 9 Branch'),
    (N'B532BM', N'Central Rama 9 Branch'),
    (N'B532CSM', N'Central Rama 9 Branch'),
    (N'B532CSR', N'Central Rama 9 Branch'),
    (N'B532CSR2', N'Central Rama 9 Branch'),
    (N'B535AHC2', N'Suksawat Branch'),
    (N'B535AHCS', N'Suksawat Branch'),
    (N'B535BM', N'Suksawat Branch'),
    (N'B535CSR', N'Suksawat Branch'),
    (N'B538AHC2', N'Central Rama3 Branch'),
    (N'B538AHCS', N'Central Rama3 Branch'),
    (N'B538BM', N'Central Rama3 Branch'),
    (N'B538CSR', N'Central Rama3 Branch'),
    (N'B538CSR2', N'Central Rama3 Branch'),
    (N'B541AHC2', N'Park Lane (Ekkamai) Branch'),
    (N'B541AHCS', N'Park Lane (Ekkamai) Branch'),
    (N'B541BM', N'Park Lane (Ekkamai) Branch'),
    (N'B541CSR', N'Park Lane (Ekkamai) Branch'),
    (N'B541CSR2', N'Park Lane (Ekkamai) Branch'),
    (N'B541CSR3', N'Park Lane (Ekkamai) Branch'),
    (N'B547AHC2', N'Lotus Rama 4 Branch'),
    (N'B547AHCS', N'Lotus Rama 4 Branch'),
    (N'B547BM', N'Lotus Rama 4 Branch'),
    (N'B547CSR', N'Lotus Rama 4 Branch'),
    (N'B547CSR2', N'Lotus Rama 4 Branch'),
    (N'B549AHC2', N'Central Pinklao Branch'),
    (N'B549AHCS', N'Central Pinklao Branch'),
    (N'B549BM', N'Central Pinklao Branch'),
    (N'B549CSR', N'Central Pinklao Branch'),
    (N'B549CSR2', N'Central Pinklao Branch'),
    (N'B555AHC2', N'Lotus Srinakarin Branch'),
    (N'B555AHC3', N'Lotus Srinakarin Branch'),
    (N'B555AHCS', N'Lotus Srinakarin Branch'),
    (N'B555BM', N'Lotus Srinakarin Branch'),
    (N'B555CSR', N'Lotus Srinakarin Branch'),
    (N'B557AHC2', N'Homepro Suvarnabhumi Branch'),
    (N'B557AHC3', N'Homepro Suvarnabhumi Branch'),
    (N'B557AHCS', N'Homepro Suvarnabhumi Branch'),
    (N'B557BM', N'Homepro Suvarnabhumi Branch'),
    (N'B557CSR', N'Homepro Suvarnabhumi Branch'),
    (N'P6332', N'Terminal 21 Korat Branch'),
    (N'P6333', N'Homepro Surin Branch'),
    (N'P6311', N'Retail Credit Underwriting'),
    (N'P6330', N'The Mall Ngamwongwan Branch'),
    (N'TQA001', N'Default/Dummy'),
    (N'P6327', N'Fashion Island Branch'),
    (N'P6152', N'Secured Lending'),
    (N'P6339', N'The Circle Ratchapruk Branch'),
    (N'P6340', N'The Mall Bangkhae Branch'),
    (N'P6342', N'Retail Credit Underwriting'),
    (N'P6363', N'Lumpini Branch'),
    (N'P3137', N'Corporate Business'),
    (N'P6351', N'Retail Credit Underwriting'),
    (N'P6381', N'Future Park Rangsit Branch'),
    (N'RPAPRDI01', N'Collateral Appraisal'),
    (N'RPAPRDI02', N'Collateral Appraisal'),
    (N'P6343', N'Corporate Business'),
    (N'P6403', N'Lotus North Ratchapruek Branch'),
    (N'P6404', N'Hat Yai Branch'),
    (N'P6388', N'Ayutthaya City Park Branch'),
    (N'B521AHC2', N'Big C Onnut Branch'),
    (N'P6424', N'Credit Management'),
    (N'P6402', N'Terminal 21 Pattaya Branch'),
    (N'P6427', N'UD Town Udonthani Branch'),
    (N'P6429', N'Lumpini Branch'),
    (N'P6391', N'Corporate Business'),
    (N'P6397', N'Retail Credit Underwriting'),
    (N'P6020', N'Credit Administration'),
    (N'P4501', N'Credit Administration'),
    (N'P2596', N'Credit Administration'),
    (N'P6442', N'Terminal 21 Pattaya Branch'),
    (N'P6443', N'Sriracha Branch'),
    (N'P6439', N'Kanchanaburi Branch'),
    (N'P6462', N'Paradise Park Branch'),
    (N'P6463', N'Pak Chong Branch'),
    (N'B501ABM', N'The Mall Bangkhae Branch'),
    (N'B512ABM', N'The Mall Thapra Branch'),
    (N'B504ABM', N'The Old Siam Branch'),
    (N'B524ABM', N'Worachak Branch'),
    (N'B549ABM', N'Central Pinklao Branch'),
    (N'B304ABM', N'Central Salaya Branch'),
    (N'B513ABM', N'Yaowaraj Branch'),
    (N'B561ABM', N'Paradise Park Branch'),
    (N'B503ABM', N'The Mall Bangkapi Branch'),
    (N'B557ABM', N'Homepro Suvarnabhumi Branch'),
    (N'B560ABM', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'P6575', N'Retail Lending Sales 1'),
    (N'P6577', N'Retail Lending Sales 1'),
    (N'P6576', N'Retail Lending Sales 1'),
    (N'B119ABM', N'Terminal 21 Korat Branch'),
    (N'B201ABM', N'Homepro Chonburi Branch'),
    (N'B305ABM', N'Homepro Saraburi Branch'),
    (N'B203ABM', N'Terminal 21 Pattaya Branch'),
    (N'B107ABM', N'Homepro Chaiyaphum Branch'),
    (N'B120ABM', N'Pak Chong Branch'),
    (N'B109ABM', N'Homepro Roiet Branch'),
    (N'B106ABM', N'Ubon Ratchathani Branch'),
    (N'B116ABM', N'Homepro Surin Branch'),
    (N'B105ABM', N'Central KhonKaen Branch'),
    (N'B103ABM', N'UD Town Udonthani Branch'),
    (N'B309ABM', N'Homepro Chachoengsao Branch'),
    (N'B317ABM', N'Ayutthaya City Park Branch'),
    (N'B004ABM', N'Phitsanulok Branch'),
    (N'B006ABM', N'Chiangrai Branch'),
    (N'B202ABM', N'Sriracha Branch'),
    (N'B101ABM', N'Khonkaen Branch'),
    (N'P6590', N'Metropolitan Business'),
    (N'P6596', N'The Crystal Ekamai-Ramindra Branch'),
    (N'P6600', N'Central KhonKaen Branch'),
    (N'B204ABM', N'Rayong Branch'),
    (N'B303ABM', N'Kanchanaburi Branch'),
    (N'B301ABM', N'Hua Hin Branch'),
    (N'B530ABM', N'Samutsakhon Branch'),
    (N'B302ABM', N'Nakhonpathom Branch'),
    (N'B405ABM', N'Hat Yai Branch'),
    (N'B406ABM', N'Big C Hatyai 2 Branch'),
    (N'B402ABM', N'Lotus Phuket Branch'),
    (N'B404ABM', N'Suratthani Branch'),
    (N'B408ABM', N'Homepro Chumphon Branch'),
    (N'B401ABM', N'Phuket Branch'),
    (N'B409ABM', N'Nakhon Si Thammarat Branch'),
    (N'P6605', N'Secured Lending'),
    (N'B525HCSU', N'The Circle Ratchapruk Branch'),
    (N'B527HCS2', N'Terminal 21 Branch'),
    (N'B527HCS3', N'Terminal 21 Branch'),
    (N'B527HCSU', N'Terminal 21 Branch'),
    (N'B532HCS2', N'Central Rama 9 Branch'),
    (N'B532HCSU', N'Central Rama 9 Branch'),
    (N'B535HCSU', N'Suksawat Branch'),
    (N'B538HCSU', N'Central Rama3 Branch'),
    (N'B541HCSU', N'Park Lane (Ekkamai) Branch'),
    (N'B547HCSU', N'Lotus Rama 4 Branch'),
    (N'B549HCSU', N'Central Pinklao Branch'),
    (N'B555HCSU', N'Lotus Srinakarin Branch'),
    (N'B557HCS2', N'Homepro Suvarnabhumi Branch'),
    (N'B557HCSU', N'Homepro Suvarnabhumi Branch'),
    (N'B560HCSU', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B561SCSR', N'Paradise Park Branch'),
    (N'B890HCSU', N'Fashion Island Branch'),
    (N'P6669', N'Homepro Suvarnabhumi Branch'),
    (N'P6666', N'Phuket Branch'),
    (N'P6667', N'Homepro Chachoengsao Branch'),
    (N'P6662', N'Chiangrai Branch'),
    (N'P6671', N'Central Westgate Branch'),
    (N'P6643', N'Credit Management'),
    (N'P81331', N'Credit Review'),
    (N'P6695', N'The Old Siam Branch'),
    (N'P6703', N'Central Rama3 Branch'),
    (N'P6705', N'Terminal 21 Korat Branch'),
    (N'P6708', N'Retail Lending Sales 2'),
    (N'P6354', N'Collateral Appraisal'),
    (N'P6692', N'International Business'),
    (N'P6725', N'Big C Hangdong Branch'),
    (N'P6707', N'Retail Lending Sales 2'),
    (N'TENY001', N'สายงานตรวจสอบ'),
    (N'P6734', N'Provincial Business'),
    (N'P6733', N'Central Westgate Branch'),
    (N'P3721', N'Business Audit'),
    (N'P6754', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'P6758', N'Homepro Surin Branch'),
    (N'P6916', N'Homepro Suvarnabhumi Branch'),
    (N'B563SCSR', N'One Bangkok Branch'),
    (N'P6947', N'Retail Credit Underwriting'),
    (N'P6432', N'Central Rama3 Branch'),
    (N'P6896', N'Provincial Business'),
    (N'P6565', N'Metropolitan Business'),
    (N'P6949', N'Homepro Roiet Branch'),
    (N'P6908', N'Provincial Business'),
    (N'P6844', N'Khonkaen Branch'),
    (N'P6977', N'One Bangkok Branch'),
    (N'P6980', N'Lotus Srinakarin Branch'),
    (N'P7001', N'Suratthani Branch'),
    (N'P7002', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'P7013', N'Lotus Srinakarin Branch'),
    (N'P6976', N'Yaowaraj Branch'),
    (N'P0824', N'Institutional Credit Underwriting 1'),
    (N'P6964', N'Nakhonsawan Branch'),
    (N'P6978', N'Rayong Branch'),
    (N'P6946', N'Provincial Business'),
    (N'P7015', N'The Mall Ngamwongwan Branch'),
    (N'P7024', N'Chiangrai Branch'),
    (N'P7003', N'Rayong Branch'),
    (N'P6938', N'Metropolitan Business'),
    (N'P6881', N'Retail Collection Management'),
    (N'P6956', N'Metropolitan Business'),
    (N'P7025', N'Mega Bangna Branch'),
    (N'P7052', N'Park Lane (Ekkamai) Branch'),
    (N'P7022', N'Retail Credit Underwriting'),
    (N'P7042', N'Samutsakhon Branch'),
    (N'P6863', N'Big C Hatyai 2 Branch'),
    (N'P7050', N'Provincial Business'),
    (N'P7030', N'Central Pinklao Branch'),
    (N'P7039', N'Central Pinklao Branch'),
    (N'P7063', N'Homepro Chaiyaphum Branch'),
    (N'P7026', N'Retail Credit Underwriting'),
    (N'P7062', N'Retail Lending Sales 4'),
    (N'P7064', N'Lotus Phuket Branch'),
    (N'P7229', N'Homepro Lampang Branch'),
    (N'P7198', N'Retail Lending Sales 2'),
    (N'P7257', N'Terminal 21 Korat Branch'),
    (N'P7234', N'Central Rama 9 Branch'),
    (N'P7195', N'Business Process and PMO'),
    (N'P7239', N'Ayutthaya City Park Branch'),
    (N'P7244', N'Retail Credit Underwriting'),
    (N'P7248', N'International Business'),
    (N'P7252', N'Provincial Business'),
    (N'P7240', N'Metropolitan Business'),
    (N'P7232', N'Metropolitan Business'),
    (N'P7269', N'Phitsanulok Branch'),
    (N'P7270', N'Terminal 21 Korat Branch'),
    (N'P7266', N'Credit Management'),
    (N'P7250', N'Credit Review'),
    (N'B562BM', N'Mega Bangna Branch'),
    (N'B309BM2', N'Homepro Chachoengsao Branch'),
    (N'B309BM3', N'Homepro Chachoengsao Branch'),
    (N'B309AHC3', N'Homepro Chachoengsao Branch'),
    (N'B309AHC4', N'Homepro Chachoengsao Branch'),
    (N'B309AHC5', N'Homepro Chachoengsao Branch'),
    (N'B309AHC6', N'Homepro Chachoengsao Branch'),
    (N'B309AHC7', N'Homepro Chachoengsao Branch'),
    (N'P81351', N'Business Audit'),
    (N'P3000', N'Business Audit'),
    (N'P7271', N'UD Town Udonthani Branch'),
    (N'P81392', N'Business Audit'),
    (N'P7272', N'Metropolitan Business'),
    (N'P7253', N'Metropolitan Business'),
    (N'B208SCSR', N'Amata City Chonburi Branch'),
    (N'P7279', N'Lumpini Branch'),
    (N'B309AHC8', N'Homepro Chachoengsao Branch'),
    (N'P7311', N'Retail Lending Sales 2'),
    (N'P7307', N'Retail Lending Sales 2'),
    (N'P7308', N'Retail Lending Sales 2'),
    (N'P7312', N'Retail Lending Sales 2'),
    (N'P7392', N'Business Process and PMO'),
    (N'P7385', N'Provincial Business'),
    (N'P7400', N'Provincial Business'),
    (N'P7446', N'Lumpini Branch'),
    (N'P6954', N'International Business'),
    (N'P7409', N'IT Security and IT Risk Management'),
    (N'P6064', N'Conglomerate Business'),
    (N'P7471', N'Central Rama3 Branch'),
    (N'P7470', N'The Circle Ratchapruk Branch'),
    (N'P7457', N'Retail Credit Underwriting'),
    (N'P7423', N'The Mall Bangkhae Branch'),
    (N'P7472', N'Worachak Branch'),
    (N'P6939', N'Talat Warorot Branch'),
    (N'P7237', N'Lumpini Branch'),
    (N'P6979', N'One Bangkok Branch'),
    (N'P7357', N'Metropolitan Business'),
    (N'P81280', N'Internal Audit Professional Practice Standards and Strategy'),
    (N'P7415', N'Metropolitan Business'),
    (N'P7515', N'Big C Onnut Branch'),
    (N'TADC013', N'Default/Dummy'),
    (N'P7462', N'Retail Collection Management'),
    (N'B563BM', N'One Bangkok Branch'),
    (N'P7424', N'Provincial Business'),
    (N'P7491', N'Provincial Business'),
    (N'P7358', N'Metropolitan Business'),
    (N'P7362', N'Metropolitan Business'),
    (N'P7434', N'Metropolitan Business'),
    (N'P5164', N'Credit Management'),
    (N'P0901', N'Institutional Credit Underwriting 1'),
    (N'P0199', N'Credit Administration'),
    (N'P0691', N'Legal and Compliance'),
    (N'P1330', N'Litigation'),
    (N'P3359', N'Litigation'),
    (N'P3674', N'Institutional Credit Development'),
    (N'P3240', N'Retail Collection Management'),
    (N'P4250', N'Corporate Business'),
    (N'P3522', N'Metropolitan Business'),
    (N'P0809', N'Metropolitan Business'),
    (N'P4663', N'Metropolitan Business'),
    (N'P3081', N'Provincial Business'),
    (N'P4000', N'Metropolitan Business'),
    (N'P3622', N'Provincial Business'),
    (N'P3457', N'Provincial Business'),
    (N'P1707', N'Provincial Business'),
    (N'P4342', N'Metropolitan Business'),
    (N'P4109', N'Provincial Business'),
    (N'P5030', N'Metropolitan Business'),
    (N'P4741', N'Provincial Business'),
    (N'P5316', N'International Business'),
    (N'P0422', N'Secured Lending'),
    (N'P1475', N'Retail Lending Sales 4'),
    (N'P2114', N'RL Operation Management'),
    (N'P3385', N'RL Operation Management'),
    (N'P0502', N'RL Operation Management'),
    (N'P0141', N'Retail Lending Sales 2'),
    (N'P3180', N'RL Operation Management'),
    (N'P3563', N'RL Operation Management'),
    (N'P3072', N'RL Operation Management'),
    (N'P5374', N'IT Security and IT Risk Management'),
    (N'P5356', N'Provincial Business'),
    (N'P0032', N'Credit Review'),
    (N'P3039', N'Credit Review'),
    (N'P1905', N'Conglomerate Business'),
    (N'P5970', N'Central World Branch'),
    (N'P6003', N'Metropolitan Business'),
    (N'P81204', N'Business Audit'),
    (N'P4930', N'Compensation and Benefits'),
    (N'P90407', N'International Business'),
    (N'P6011', N'Metropolitan Business'),
    (N'P5987', N'Lotus Rama 4 Branch'),
    (N'P6025', N'Corporate Business'),
    (N'P81214', N'Credit Review'),
    (N'P6073', N'The Mall Thapra Branch'),
    (N'P2416', N'The Mall Bangkhae Branch'),
    (N'P1057', N'The Mall Bangkhae Branch'),
    (N'P2908', N'Park Lane (Ekkamai) Branch'),
    (N'P5021', N'The Circle Ratchapruk Branch'),
    (N'P4654', N'The Mall Thapra Branch'),
    (N'P5784', N'Central Westgate Branch'),
    (N'P0855', N'Central Pinklao Branch'),
    (N'P2784', N'Bangrak Branch'),
    (N'P4024', N'Lumpini Branch'),
    (N'P1745', N'Retail Lending Sales 1'),
    (N'P2826', N'The Circle Ratchapruk Branch'),
    (N'P4801', N'Lotus North Ratchapruek Branch'),
    (N'P4595', N'Paradise Park Branch'),
    (N'P1784', N'Central Rama 9 Branch'),
    (N'P2664', N'The Crystal Ekamai-Ramindra Branch'),
    (N'P1364', N'Worachak Branch'),
    (N'P4540', N'Yaowaraj Branch'),
    (N'P5974', N'Central Salaya Branch'),
    (N'P2909', N'Central Salaya Branch'),
    (N'P5593', N'Central Salaya Branch'),
    (N'P3706', N'Central Salaya Branch'),
    (N'P5975', N'Big C Bangna Branch'),
    (N'P1230', N'Big C Bangna Branch'),
    (N'P1317', N'Mega Bangna Branch'),
    (N'P4359', N'RL Operation Management'),
    (N'P5308', N'Suksawat Branch'),
    (N'P4344', N'Lotus Rama 4 Branch'),
    (N'P1424', N'Central Rama 9 Branch'),
    (N'P4191', N'Central World Branch'),
    (N'P5303', N'Central World Branch'),
    (N'P4916', N'Lotus Rama 4 Branch'),
    (N'P3791', N'Park Lane (Ekkamai) Branch'),
    (N'P5528', N'Lotus Rama 4 Branch'),
    (N'P4613', N'Lotus Rama 4 Branch'),
    (N'P5469', N'Lotus Rama 4 Branch'),
    (N'P1934', N'Big C Onnut Branch'),
    (N'P3455', N'Central Rama 9 Branch'),
    (N'P3665', N'Big C Onnut Branch'),
    (N'P3350', N'Terminal 21 Branch'),
    (N'P4666', N'Terminal 21 Branch'),
    (N'P3783', N'Saphankhwai Branch'),
    (N'P5595', N'Terminal 21 Branch'),
    (N'P4416', N'The Mall Bangkhae Branch'),
    (N'P5237', N'Lumpini Branch'),
    (N'P4781', N'Park Lane (Ekkamai) Branch'),
    (N'P4491', N'Bangrak Branch'),
    (N'P4069', N'One Bangkok Branch'),
    (N'P4057', N'Lumpini Branch'),
    (N'P5505', N'RL Operation Management'),
    (N'P3102', N'Central Pinklao Branch'),
    (N'P4665', N'Lumpini Branch'),
    (N'P6102', N'Retail Lending Sales 2'),
    (N'P6101', N'Secured Lending'),
    (N'P5921', N'Conglomerate Business'),
    (N'P90378', N'International Business'),
    (N'P90397', N'International Business'),
    (N'P90401', N'International Business'),
    (N'P81194', N'Compensation and Benefits'),
    (N'P6156', N'Yaowaraj Branch'),
    (N'P6147', N'Retail Credit Underwriting'),
    (N'P6160', N'Retail Credit Underwriting'),
    (N'P5865', N'Homepro Saraburi Branch'),
    (N'P6038', N'Homepro Saraburi Branch'),
    (N'P2905', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'P4806', N'Credit Management'),
    (N'P5465', N'Credit Management'),
    (N'P5835', N'Big C Hangdong Branch'),
    (N'P6139', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'P6181', N'Talat Warorot Branch'),
    (N'P6137', N'Phitsanulok Branch'),
    (N'P3629', N'Phitsanulok Branch'),
    (N'P4527', N'Amata City Chonburi Branch'),
    (N'P2868', N'Nakhonsawan Branch'),
    (N'P3498', N'Nakhonsawan Branch'),
    (N'P2803', N'Homepro Lampang Branch'),
    (N'P5788', N'Homepro Lampang Branch'),
    (N'P6118', N'Homepro Lampang Branch'),
    (N'P2503', N'Nakhonpathom Branch'),
    (N'P5642', N'Ayutthaya City Park Branch'),
    (N'P5932', N'Nakhonpathom Branch'),
    (N'P5346', N'Homepro Chonburi Branch'),
    (N'P3815', N'Homepro Chonburi Branch'),
    (N'P4099', N'Homepro Chonburi Branch'),
    (N'P5584', N'Homepro Chonburi Branch'),
    (N'P2848', N'Sriracha Branch'),
    (N'P5357', N'Terminal 21 Pattaya Branch'),
    (N'P5378', N'Homepro Phetchaburi Branch'),
    (N'P3024', N'Hua Hin Branch'),
    (N'P3636', N'Amata City Chonburi Branch'),
    (N'P5898', N'Homepro Chachoengsao Branch'),
    (N'P2972', N'Robinson Ratchaburi Branch'),
    (N'P3578', N'Homepro Phetchaburi Branch'),
    (N'P4686', N'Credit Management'),
    (N'P5443', N'Samutsakhon Branch'),
    (N'P5855', N'Phuket Branch'),
    (N'P2511', N'Credit Management'),
    (N'B006CSR', N'Chiangrai Branch'),
    (N'B012AHCS', N'Homepro Lampang Branch'),
    (N'B012BM', N'Homepro Lampang Branch'),
    (N'B012CSR', N'Homepro Lampang Branch'),
    (N'B012HCSU', N'Homepro Lampang Branch'),
    (N'B101AHC2', N'Khonkaen Branch'),
    (N'B101AHCS', N'Khonkaen Branch'),
    (N'B101BM', N'Khonkaen Branch'),
    (N'B101CSR', N'Khonkaen Branch'),
    (N'B101CSR2', N'Khonkaen Branch'),
    (N'B103AHC2', N'UD Town Udonthani Branch'),
    (N'B103AHCS', N'UD Town Udonthani Branch'),
    (N'B103BM', N'UD Town Udonthani Branch'),
    (N'B103CSR', N'UD Town Udonthani Branch'),
    (N'B103CSR2', N'UD Town Udonthani Branch'),
    (N'B103HCSU', N'UD Town Udonthani Branch'),
    (N'B105AHC2', N'Central KhonKaen Branch'),
    (N'B105AHCS', N'Central KhonKaen Branch'),
    (N'B105BM', N'Central KhonKaen Branch'),
    (N'B105CSR', N'Central KhonKaen Branch'),
    (N'B105CSR2', N'Central KhonKaen Branch'),
    (N'B105HCS2', N'Central KhonKaen Branch'),
    (N'B105HCSU', N'Central KhonKaen Branch'),
    (N'B106AHC2', N'Ubon Ratchathani Branch'),
    (N'B106AHCS', N'Ubon Ratchathani Branch'),
    (N'B106BM', N'Ubon Ratchathani Branch'),
    (N'B106CSR', N'Ubon Ratchathani Branch'),
    (N'B107AHC2', N'Homepro Chaiyaphum Branch'),
    (N'B107AHCS', N'Homepro Chaiyaphum Branch'),
    (N'B107BM', N'Homepro Chaiyaphum Branch'),
    (N'B107CSR', N'Homepro Chaiyaphum Branch'),
    (N'B107HCSU', N'Homepro Chaiyaphum Branch'),
    (N'B109AHC2', N'Homepro Roiet Branch'),
    (N'B109AHCS', N'Homepro Roiet Branch'),
    (N'B109BM', N'Homepro Roiet Branch'),
    (N'B109CSR', N'Homepro Roiet Branch'),
    (N'B109HCSU', N'Homepro Roiet Branch'),
    (N'B116AHCS', N'Homepro Surin Branch'),
    (N'B116BM', N'Homepro Surin Branch'),
    (N'B116CSR', N'Homepro Surin Branch'),
    (N'B116HCSU', N'Homepro Surin Branch'),
    (N'B119AHC2', N'Terminal 21 Korat Branch'),
    (N'B119AHCS', N'Terminal 21 Korat Branch'),
    (N'B119BM', N'Terminal 21 Korat Branch'),
    (N'B119CSR', N'Terminal 21 Korat Branch'),
    (N'B119HCSU', N'Terminal 21 Korat Branch'),
    (N'B120AHC2', N'Pak Chong Branch'),
    (N'B120AHCS', N'Pak Chong Branch'),
    (N'B120BM', N'Pak Chong Branch'),
    (N'B120CSR', N'Pak Chong Branch'),
    (N'B201AHC2', N'Homepro Chonburi Branch'),
    (N'B557CSR2', N'Homepro Suvarnabhumi Branch'),
    (N'B560AHC2', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B560AHCS', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B560BM', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B560CSR', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B560CSR2', N'The Paseo Mall (Ladkrabang) Branch'),
    (N'B561BM', N'Paradise Park Branch'),
    (N'B561CSM', N'Paradise Park Branch'),
    (N'B561CSM2', N'Paradise Park Branch'),
    (N'B561CSM3', N'Paradise Park Branch'),
    (N'B561CSR', N'Paradise Park Branch'),
    (N'B889AHC2', N'Institutional Banking Solutions'),
    (N'B889AHCS', N'Institutional Banking Solutions'),
    (N'B889BM', N'Institutional Banking Solutions'),
    (N'B889CSR', N'Institutional Banking Solutions'),
    (N'B889CSR2', N'Institutional Banking Solutions'),
    (N'B889CSR3', N'Institutional Banking Solutions'),
    (N'B889CSR4', N'Institutional Banking Solutions'),
    (N'B889HCS2', N'Institutional Banking Solutions'),
    (N'B889HCS3', N'Institutional Banking Solutions'),
    (N'B889HCSU', N'Institutional Banking Solutions'),
    (N'B890AHC2', N'Fashion Island Branch'),
    (N'B890AHCS', N'Fashion Island Branch'),
    (N'B890BM', N'Fashion Island Branch'),
    (N'B890CSR', N'Fashion Island Branch'),
    (N'B890CSR2', N'Fashion Island Branch'),
    (N'B890CSR3', N'Fashion Island Branch'),
    (N'P6028', N'Metropolitan Business'),
    (N'P6065', N'Metropolitan Business'),
    (N'P6260', N'Big C Onnut Branch'),
    (N'P6261', N'Central World Branch'),
    (N'P6264', N'Institutional Banking Solutions'),
    (N'P6254', N'Homepro Chachoengsao Branch'),
    (N'P6267', N'Suksawat Branch'),
    (N'P6280', N'Central Rama 9 Branch'),
    (N'P6281', N'Future Park Rangsit Branch'),
    (N'P6241', N'Central Rama3 Branch'),
    (N'P6182', N'Lotus Srinakarin Branch'),
    (N'P81018', N'Compensation and Benefits'),
    (N'B116AHC2', N'Homepro Surin Branch'),
    (N'P6312', N'Terminal 21 Pattaya Branch'),
    (N'P6313', N'Fashion Island Branch'),
    (N'P6317', N'Collateral Appraisal'),
    (N'P6464', N'Homepro Suvarnabhumi Branch'),
    (N'P3880', N'Retail Collection Management'),
    (N'P6252', N'Sriracha Branch'),
    (N'P6475', N'Terminal 21 Pattaya Branch'),
    (N'P6455', N'Metropolitan Business'),
    (N'P6211', N'The Mall Ngamwongwan Branch'),
    (N'P6511', N'One Bangkok Branch'),
    (N'P6518', N'The Circle Ratchapruk Branch'),
    (N'P6512', N'Provincial Business'),
    (N'P6513', N'Metropolitan Business'),
    (N'P90442', N'International Business'),
    (N'P6533', N'Future Park Rangsit Branch'),
    (N'P81295', N'Credit Review'),
    (N'P6545', N'Lotus Phuket Branch'),
    (N'P6547', N'Mega Bangna Branch'),
    (N'P6541', N'IT Security and IT Risk Management'),
    (N'P6018', N'RL Operation Management'),
    (N'P6556', N'Ubon Ratchathani Branch'),
    (N'P6558', N'Homepro Chumphon Branch'),
    (N'P6561', N'IT Security and IT Risk Management'),
    (N'B555ABM', N'Lotus Srinakarin Branch'),
    (N'B505ABM', N'Big C Bangna Branch'),
    (N'B521ABM', N'Big C Onnut Branch'),
    (N'B535ABM', N'Suksawat Branch'),
    (N'B541ABM', N'Park Lane (Ekkamai) Branch'),
    (N'B532ABM', N'Central Rama 9 Branch'),
    (N'B517ABM', N'The Mall Ngamwongwan Branch'),
    (N'B509ABM', N'Future Park Rangsit Branch'),
    (N'B515ABM', N'Lotus North Ratchapruek Branch'),
    (N'B511ABM', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B890ABM', N'Fashion Island Branch'),
    (N'B525ABM', N'The Circle Ratchapruk Branch'),
    (N'B522ABM', N'Saphankhwai Branch'),
    (N'B001ABM', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B002ABM', N'Big C Hangdong Branch'),
    (N'B003ABM', N'Talat Warorot Branch'),
    (N'B005ABM', N'Nakhonsawan Branch'),
    (N'B012ABM', N'Homepro Lampang Branch'),
    (N'B889ABM', N'Institutional Banking Solutions'),
    (N'B538ABM', N'Central Rama3 Branch'),
    (N'B507ABM', N'Central World Branch'),
    (N'B547ABM', N'Lotus Rama 4 Branch'),
    (N'B519ABM', N'Bangrak Branch'),
    (N'B527ABM', N'Terminal 21 Branch'),
    (N'P6606', N'Retail Lending Sales 1'),
    (N'P6620', N'Central Rama3 Branch'),
    (N'P6619', N'Ubon Ratchathani Branch'),
    (N'P6621', N'Big C Bangna Branch'),
    (N'P6564', N'Corporate Business'),
    (N'P6591', N'Retail Credit Underwriting'),
    (N'P6607', N'Retail Credit Underwriting'),
    (N'P6636', N'Kanchanaburi Branch'),
    (N'P6637', N'Phuket Branch'),
    (N'B001HCSU', N'Lotus Ruamchok (Chiangmai) Branch'),
    (N'B101HCSU', N'Khonkaen Branch'),
    (N'B409HCSU', N'Nakhon Si Thammarat Branch'),
    (N'P81070', N'Compensation and Benefits'),
    (N'B002HCSU', N'Big C Hangdong Branch'),
    (N'B003HCSU', N'Talat Warorot Branch'),
    (N'B004HCSU', N'Phitsanulok Branch'),
    (N'B005HCSU', N'Nakhonsawan Branch'),
    (N'B006HCSU', N'Chiangrai Branch'),
    (N'B106HCS2', N'Ubon Ratchathani Branch'),
    (N'B106HCSU', N'Ubon Ratchathani Branch'),
    (N'B120HCSU', N'Pak Chong Branch'),
    (N'B204HCSU', N'Rayong Branch'),
    (N'B301HCSU', N'Hua Hin Branch'),
    (N'B302HCSU', N'Nakhonpathom Branch'),
    (N'B501HCSU', N'The Mall Bangkhae Branch'),
    (N'B503HCSU', N'The Mall Bangkapi Branch'),
    (N'B504HCSU', N'The Old Siam Branch'),
    (N'B504HCS2', N'The Old Siam Branch'),
    (N'B505HCSU', N'Big C Bangna Branch'),
    (N'B505HCS2', N'Big C Bangna Branch'),
    (N'B507HCSU', N'Central World Branch'),
    (N'B509HCS2', N'Future Park Rangsit Branch'),
    (N'B509HCS3', N'Future Park Rangsit Branch'),
    (N'B509HCSU', N'Future Park Rangsit Branch'),
    (N'B511HCSU', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B512HCS2', N'The Mall Thapra Branch'),
    (N'B512HCSU', N'The Mall Thapra Branch'),
    (N'B513HCSU', N'Yaowaraj Branch'),
    (N'B515HCS2', N'Lotus North Ratchapruek Branch'),
    (N'B515HCSU', N'Lotus North Ratchapruek Branch'),
    (N'B517HCS2', N'The Mall Ngamwongwan Branch'),
    (N'B517HCSU', N'The Mall Ngamwongwan Branch'),
    (N'B519HCS2', N'Bangrak Branch'),
    (N'B519HCSU', N'Bangrak Branch'),
    (N'B521HCSU', N'Big C Onnut Branch'),
    (N'B522HCSU', N'Saphankhwai Branch'),
    (N'B524HCS2', N'Worachak Branch'),
    (N'B524HCSU', N'Worachak Branch'),
    (N'P6760', N'Suratthani Branch'),
    (N'P6785', N'Lumpini Branch'),
    (N'P5763', N'Metropolitan Business'),
    (N'P6786', N'Metropolitan Business'),
    (N'P6742', N'Corporate Business'),
    (N'P5527', N'Homepro Surin Branch'),
    (N'P6444', N'The Mall Thapra Branch'),
    (N'P6454', N'UD Town Udonthani Branch'),
    (N'P0632', N'Chiangrai Branch'),
    (N'P6816', N'Retail Lending Sales 1'),
    (N'P6814', N'RL Operation Management'),
    (N'P6838', N'Homepro Roiet Branch'),
    (N'P6833', N'Lotus North Ratchapruek Branch'),
    (N'P6609', N'Metropolitan Business'),
    (N'P6770', N'Corporate Business'),
    (N'P6832', N'Metropolitan Business'),
    (N'P6826', N'Metropolitan Business'),
    (N'P6852', N'Retail Lending Sales 2'),
    (N'P1448', N'Lumpini Branch'),
    (N'P6771', N'Corporate Business'),
    (N'P6842', N'Retail Lending Sales 2'),
    (N'P6878', N'The Mall Thapra Branch'),
    (N'P6372', N'Terminal 21 Branch'),
    (N'P6879', N'Metropolitan Business'),
    (N'P6868', N'Big C Hangdong Branch'),
    (N'P6776', N'Metropolitan Business'),
    (N'P2772', N'Homepro Chachoengsao Branch'),
    (N'P6897', N'Retail Lending Sales 1'),
    (N'P6919', N'The Crystal Ekamai-Ramindra Branch'),
    (N'B562CSM', N'Mega Bangna Branch'),
    (N'B562CSR', N'Mega Bangna Branch'),
    (N'B562SCSR', N'Mega Bangna Branch'),
    (N'B563CSR', N'One Bangkok Branch');

INSERT INTO @Fix (UserName, Department) VALUES
    (N'B563CSM', N'One Bangkok Branch'),
    (N'B208CSR', N'Amata City Chonburi Branch'),
    (N'B208CSM', N'Amata City Chonburi Branch'),
    (N'P90449', N'Provincial Business'),
    (N'P3218', N'Mega Bangna Branch'),
    (N'P6942', N'Retail Lending Sales 4'),
    (N'B563SCS2', N'One Bangkok Branch'),
    (N'P6265', N'RL Operation Management'),
    (N'P7057', N'Credit Management'),
    (N'P6817', N'Metropolitan Business'),
    (N'P7031', N'International Business'),
    (N'P7105', N'The Old Siam Branch'),
    (N'P7094', N'Homepro Suvarnabhumi Branch'),
    (N'P7106', N'Paradise Park Branch'),
    (N'P81378', N'Business Audit'),
    (N'P7093', N'Homepro Chonburi Branch'),
    (N'P6840', N'Metropolitan Business'),
    (N'P6910', N'Metropolitan Business'),
    (N'P7114', N'Phitsanulok Branch'),
    (N'P7060', N'Big C Onnut Branch'),
    (N'P7074', N'Khonkaen Branch'),
    (N'P6907', N'Provincial Business'),
    (N'P90453', N'International Business'),
    (N'P7126', N'Rayong Branch'),
    (N'P7109', N'The Mall Bangkhae Branch'),
    (N'P7128', N'Retail Credit Underwriting'),
    (N'P7149', N'Kanchanaburi Branch'),
    (N'P4362', N'Homepro Roiet Branch'),
    (N'P6932', N'Metropolitan Business'),
    (N'P7007', N'Metropolitan Business'),
    (N'P7168', N'Retail Lending Sales 2'),
    (N'P7180', N'Saphankhwai Branch'),
    (N'P2195', N'Patong Branch'),
    (N'P7174', N'Retail Lending Sales 1'),
    (N'P7190', N'One Bangkok Branch'),
    (N'P7183', N'Lumpini Branch'),
    (N'TPFO002', N'เทคโนโลยีสารสนเทศ'),
    (N'P7176', N'Retail Lending Sales 1'),
    (N'P7132', N'Metropolitan Business'),
    (N'P7211', N'Retail Lending Sales 4'),
    (N'P5420', N'Institutional Credit Development'),
    (N'P7186', N'Credit Review'),
    (N'P7216', N'Credit Management'),
    (N'P7227', N'Suratthani Branch'),
    (N'P7306', N'Retail Lending Sales 2'),
    (N'P7313', N'Retail Lending Sales 1'),
    (N'P5010', N'Lumpini Branch'),
    (N'P0454', N'Park Lane (Ekkamai) Branch'),
    (N'P7309', N'Retail Lending Sales 2'),
    (N'P7339', N'Retail Lending Sales 1'),
    (N'P7318', N'Samutsakhon Branch'),
    (N'P7329', N'Big C Hangdong Branch'),
    (N'P7350', N'Collateral Appraisal'),
    (N'P7323', N'Retail Lending Sales 1'),
    (N'P7200', N'Metropolitan Business'),
    (N'B564SCSR', N'Central Westgate Branch'),
    (N'B564SCS2', N'Central Westgate Branch'),
    (N'B564CSR', N'Central Westgate Branch'),
    (N'B564CSM2', N'Central Westgate Branch'),
    (N'B564CSM', N'Central Westgate Branch'),
    (N'B564BM', N'Central Westgate Branch'),
    (N'B564ABM', N'Central Westgate Branch'),
    (N'P7378', N'Terminal 21 Korat Branch'),
    (N'P7349', N'Sriracha Branch'),
    (N'P7373', N'Future Park Rangsit Branch'),
    (N'P7376', N'Central Pinklao Branch'),
    (N'P7377', N'Suksawat Branch'),
    (N'P1024', N'Hua Hin Branch'),
    (N'P2199', N'Hua Hin Branch'),
    (N'P7399', N'Terminal 21 Branch'),
    (N'P7322', N'Retail Lending Sales 1'),
    (N'P6924', N'Nakhonpathom Branch'),
    (N'P7404', N'Credit Management'),
    (N'P7405', N'Credit Management'),
    (N'P6860', N'Big C Hatyai 2 Branch'),
    (N'P7369', N'Central Rama3 Branch'),
    (N'P7421', N'Lumpini Branch'),
    (N'P7398', N'Nakhonpathom Branch'),
    (N'P7422', N'Pak Chong Branch'),
    (N'P7456', N'Retail Credit Underwriting'),
    (N'P7452', N'Credit Review'),
    (N'B309AHCS', N'Homepro Chachoengsao Branch'),
    (N'B309BM', N'Homepro Chachoengsao Branch'),
    (N'B309CSR', N'Homepro Chachoengsao Branch'),
    (N'B309CSR2', N'Homepro Chachoengsao Branch'),
    (N'B309HCSU', N'Homepro Chachoengsao Branch'),
    (N'B317AHC2', N'Ayutthaya City Park Branch'),
    (N'B317AHC3', N'Ayutthaya City Park Branch'),
    (N'B317AHCS', N'Ayutthaya City Park Branch'),
    (N'B317BM', N'Ayutthaya City Park Branch'),
    (N'B317CSR', N'Ayutthaya City Park Branch'),
    (N'B317HCS2', N'Ayutthaya City Park Branch'),
    (N'B317HCSU', N'Ayutthaya City Park Branch'),
    (N'B401AHC2', N'Phuket Branch'),
    (N'B401AHCS', N'Phuket Branch'),
    (N'B401BM', N'Phuket Branch'),
    (N'B401CSR', N'Phuket Branch'),
    (N'B401CSR2', N'Phuket Branch'),
    (N'B401HCSU', N'Phuket Branch'),
    (N'B402AHC2', N'Lotus Phuket Branch'),
    (N'B402AHCS', N'Lotus Phuket Branch'),
    (N'B402BM', N'Lotus Phuket Branch'),
    (N'B402CSR', N'Lotus Phuket Branch'),
    (N'B402CSR2', N'Lotus Phuket Branch'),
    (N'B402HCS2', N'Lotus Phuket Branch'),
    (N'B402HCSU', N'Lotus Phuket Branch'),
    (N'B404AHC2', N'Suratthani Branch'),
    (N'B404AHCS', N'Suratthani Branch'),
    (N'B404BM', N'Suratthani Branch'),
    (N'B404CSR', N'Suratthani Branch'),
    (N'B404HCSU', N'Suratthani Branch'),
    (N'B405AHC2', N'Hat Yai Branch'),
    (N'B405AHCS', N'Hat Yai Branch'),
    (N'B405BM', N'Hat Yai Branch'),
    (N'B405CSR', N'Hat Yai Branch'),
    (N'B405HCS2', N'Hat Yai Branch'),
    (N'B405HCSU', N'Hat Yai Branch'),
    (N'B406AHC2', N'Big C Hatyai 2 Branch'),
    (N'B406AHCS', N'Big C Hatyai 2 Branch'),
    (N'B406BM', N'Big C Hatyai 2 Branch'),
    (N'B406CSR', N'Big C Hatyai 2 Branch'),
    (N'B406HCSU', N'Big C Hatyai 2 Branch'),
    (N'B408AHC2', N'Homepro Chumphon Branch'),
    (N'B408AHCS', N'Homepro Chumphon Branch'),
    (N'B408BM', N'Homepro Chumphon Branch'),
    (N'B408CSR', N'Homepro Chumphon Branch'),
    (N'B408CSR2', N'Homepro Chumphon Branch'),
    (N'B408HCSU', N'Homepro Chumphon Branch'),
    (N'B409AHCS', N'Nakhon Si Thammarat Branch'),
    (N'B409BM', N'Nakhon Si Thammarat Branch'),
    (N'B409BM2', N'Nakhon Si Thammarat Branch'),
    (N'B409CSR', N'Nakhon Si Thammarat Branch'),
    (N'B501AHC2', N'The Mall Bangkhae Branch'),
    (N'B501AHCS', N'The Mall Bangkhae Branch'),
    (N'B513AHCS', N'Yaowaraj Branch'),
    (N'B513BM', N'Yaowaraj Branch'),
    (N'B513CSR', N'Yaowaraj Branch'),
    (N'B515AHC2', N'Lotus North Ratchapruek Branch'),
    (N'B515AHCS', N'Lotus North Ratchapruek Branch'),
    (N'B515BM', N'Lotus North Ratchapruek Branch'),
    (N'B515CSR', N'Lotus North Ratchapruek Branch'),
    (N'B515CSR2', N'Lotus North Ratchapruek Branch'),
    (N'B515CSR3', N'Lotus North Ratchapruek Branch'),
    (N'B515CSR4', N'Lotus North Ratchapruek Branch'),
    (N'B517AHC2', N'The Mall Ngamwongwan Branch'),
    (N'B517AHC3', N'The Mall Ngamwongwan Branch'),
    (N'B517AHCS', N'The Mall Ngamwongwan Branch'),
    (N'B517BM', N'The Mall Ngamwongwan Branch'),
    (N'B517CSR', N'The Mall Ngamwongwan Branch'),
    (N'B517CSR2', N'The Mall Ngamwongwan Branch'),
    (N'B517CSR3', N'The Mall Ngamwongwan Branch'),
    (N'B519AHC2', N'Bangrak Branch'),
    (N'B519AHC3', N'Bangrak Branch'),
    (N'B519AHCS', N'Bangrak Branch'),
    (N'B519BM', N'Bangrak Branch'),
    (N'B519CSR', N'Bangrak Branch'),
    (N'B521AHCS', N'Big C Onnut Branch'),
    (N'B521BM', N'Big C Onnut Branch'),
    (N'B521CSR', N'Big C Onnut Branch'),
    (N'B521CSR2', N'Big C Onnut Branch'),
    (N'B522AHC2', N'Saphankhwai Branch'),
    (N'B522AHC3', N'Saphankhwai Branch'),
    (N'B522AHCS', N'Saphankhwai Branch'),
    (N'B522BM', N'Saphankhwai Branch'),
    (N'B522CSR', N'Saphankhwai Branch'),
    (N'B522CSR2', N'Saphankhwai Branch'),
    (N'B524AHC2', N'Worachak Branch'),
    (N'B524AHCS', N'Worachak Branch'),
    (N'B524BM', N'Worachak Branch'),
    (N'B524CSR', N'Worachak Branch'),
    (N'B524CSR2', N'Worachak Branch'),
    (N'B525AHC2', N'The Circle Ratchapruk Branch'),
    (N'B525AHC3', N'The Circle Ratchapruk Branch'),
    (N'B525AHCS', N'The Circle Ratchapruk Branch'),
    (N'B525BM', N'The Circle Ratchapruk Branch'),
    (N'B525CSR', N'The Circle Ratchapruk Branch'),
    (N'B525CSR2', N'The Circle Ratchapruk Branch'),
    (N'B527AHC2', N'Terminal 21 Branch'),
    (N'B527AHC3', N'Terminal 21 Branch'),
    (N'B527AHC4', N'Terminal 21 Branch'),
    (N'B527AHCS', N'Terminal 21 Branch'),
    (N'B527BM', N'Terminal 21 Branch'),
    (N'B527CSR', N'Terminal 21 Branch'),
    (N'B527CSR2', N'Terminal 21 Branch'),
    (N'B527CSR3', N'Terminal 21 Branch');

-- Informational: fix-file users that don't exist in the DB (won't be patched).
SELECT f.UserName AS MissingUser
FROM @Fix f
WHERE NOT EXISTS (SELECT 1 FROM auth.AspNetUsers u WHERE u.NormalizedUserName = UPPER(f.UserName));

UPDATE u
SET u.Department = f.Department
FROM auth.AspNetUsers u
JOIN @Fix f ON u.NormalizedUserName = UPPER(f.UserName)
WHERE ISNULL(u.Department, N'') <> f.Department;

SELECT @@ROWCOUNT AS RowsUpdated;   -- first run: number of users whose dept differed

COMMIT TRANSACTION;
