namespace Appraisal.RequestAppraisals.Features.GetAppraisalDetailByCollateralId;

public record GetAppraisalDetailByCollateralIdQuery(long CollateralId) : IQuery<GetAppraisalDetailByCollateralIdResult>;