name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dotnet-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Begin SonarCloud analysis
        run: dotnet sonarscanner begin /k:"immortalgky_collateral-appraisal-system-api" /o:"immortalgky" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore
        run: dotnet restore collateral-appraisal-system-api.sln

      - name: Lint (dotnet format)
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Build
        run: dotnet build collateral-appraisal-system-api.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test collateral-appraisal-system-api.sln --no-restore --verbosity normal

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"