namespace Request.RequestTitles.Features.GetLinkRequestTitleDocumentsByTitleId;

public record GetLinkRequestTitleDocumentsByTitleIdQuery(Guid TitleId) : IQuery<GetLinkRequestTitleDocumentsByTitleIdResult>;